### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by wiqsap** [UnamSanctam/UnamWebPanel#10]
I dropped all the files and changed the password. but I cannot login. 
![image](https://user-images.githubusercontent.com/64809395/141355946-2f6ec50a-3d29-4763-8e8f-e3c794cab8ac.png)
![image](https://user-images.githubusercontent.com/64809395/141357575-2e2037e3-aa27-469c-9b0b-bae0c66953c7.png)

**Comment by UnamSanctam** [comment]
You changed the key instead of the value. It should be `$config['password'] = 'serjo';`
