### ISSUE TITLE
Delete miner

### ISSUE THREAD

**Issue by almeresjev** [UnamSanctam/UnamWebPanel#101]
Hello, thank you for your miner and webpanel, they are great.
I have a question.
Will the miner be deleted from PC if i click on the "Remove Miner" button on the webpanel?

**Comment by UnamSanctam** [comment]
No it just removes the miner for the web panel, you'd need to run the uninstaller on the computer to remove it. The miners themselves don't contain any uninstallation code.

**Comment by almeresjev** [comment]
Thank you for the answer.
