### ISSUE TITLE
Not a big issue just want to say thank you. 

### ISSUE THREAD

**Issue by manves** [UnamSanctam/UnamWebPanel#104]
Is it normal for some miners to just be at 0 h/s ? I feel like they are mining but they might not be reporting correctly. It's not a big issue I'm just curious as it says it is active and not in stealth.

**Comment by UnamSanctam** [comment]
It depends on what miner (XMR or ETH), can you post the settings? It can happen if the miner can't connect to the pool since then it can't mine.

**Comment by manves** [comment]
It was just the PCs had really bad cpus that were extremely old.
