### ISSUE TITLE
feature request: Active Stealth mode

### ISSUE THREAD

**Issue by hidden-69** [UnamSanctam/UnamWebPanel#108]
At the moment its unknown why a worker is online but at 0 h/s, would be cool if it would show it's in stealth mode or if there is some kind of connection error to the pool, or something else.

**Comment by UnamSanctam** [comment]
It does show if it's in stealth mode, it says "Paused (Stealth)". I could try to do something for connection errors though it's usually not that straightforward.

**Comment by hidden-69** [comment]
Oh, then I don't know why some are at 0... Thanks.

**Comment by hidden-69** [comment]
Pherhaps a function to download a recent log or something, i hate guessing why it's at 0

**Comment by UnamSanctam** [comment]
Well currently there is no log so I'd have to create some sort of buffer where it gets saved or something, but can you post a screenshot of the full worker (press '+')?

**Comment by hidden-69** [comment]
![image](https://user-images.githubusercontent.com/102571076/163736367-cd8d575d-f29c-43b7-a26e-415c6c9fcbc8.png)

Also, maybe an option to use the unique id as worker name 👍

**Comment by hidden-69** [comment]
One is active now, but still 0.

**Comment by UnamSanctam** [comment]
The unique ID is currently a temporary fix on the web panel side since the C++ one didn't work very well due to the limited length it used. Though I might implement how it's done inside the miner, it's not the best but it works:
https://github.com/UnamSanctam/UnamWebPanel/blob/67310a2e76f5fb2ddc581edfbfe4893f64b3b7d8/UnamWebPanel/api/endpoint.php#L16

But hmm, the second one having 0 H/s could be understandable since it only has two cores (so both could be busy) so it won't forcibly use one unless told so (`--cpu-no-yield` or `--cpu-priority=5` in the "Advanced Parameters). But the first one seems like it should be able to mine just fine (don't think all 4 cores of that one is being used), could you maybe create a new "Configuration" with these settings and try applying it to that miner? (add your wallet):
```
{
	"algo": "rx/0",
	"pool": "xmr-eu2.nanopool.org",
	"port": 14433,
	"wallet": "YourWallet.HashrateTest",
	"ssltls": true,
	"max-cpu": 20,
	"stealth-targets": "",
	"kill-targets": ""
}
```

**Comment by hidden-69** [comment]
Is there something in the wiki about these? --cpu-no-yield or --cpu-priority=5

I've applied the settings, will allow it some time and update.

**Comment by hidden-69** [comment]
and something like this would be great for workerid!

` $uqhash = substr(md5(getData('computername').getData('cpu')), 0, 16);`

**Comment by UnamSanctam** [comment]
> Is there something in the wiki about these? --cpu-no-yield or --cpu-priority=5
> 
> I've applied the settings, will allow it some time and update.

No it's a normal xmrig command https://xmrig.com/docs/miner/command-line-options

> and something like this would be great for workerid!
> 
> ` $uqhash = substr(md5(getData('computername').getData('cpu')), 0, 16);`

Yes I'll have to code something for it in C++.

**Comment by hidden-69** [comment]
What would be the behaviour of starting the miner every 2 hours, would it restart or ignore the new instance?

**Comment by hidden-69** [comment]
It's still at 0% with the new settings

**Comment by UnamSanctam** [comment]
> What would be the behaviour of starting the miner every 2 hours, would it restart or ignore the new instance?

The miner only starts if it's not already running, so it wouldn't do anything. 

> It's still at 0% with the new settings

Can you try another algorithm/coin then? It could be that the computer barely has any free RAM or something like that, you could try RTM (GhostRider algorithm) since it barely needs any RAM.

**Comment by hidden-69** [comment]
I'll try something else, any lowram coin like RTM on nanopool?

**Comment by UnamSanctam** [comment]
No they don't have any like that, MoneroOcean does have RTM though (and pays out in XMR) if you want to try that.

**Comment by hidden-69** [comment]
I figured out a couple, I build in some debugging, there seems to be some connection issues for some workers, maybe I'll host a proxy somewhere on 443 or something. And maybe I'll mine RTM on low spec clients as well. Thanks!

if (!(Test-NetConnection -ComputerName "xmr-eu1.nanopool.org" -Port "14444").TcpTestSucceeded)

**Comment by UnamSanctam** [comment]
Ah yeah that could be it, good find, hosting a proxy sounds like a good idea. MoneroOcean also has port 443 if you want to try that, mining RTM could also still be more profitable than XMR (I'm not too sure if it is anymore).

**Comment by hidden-69** [comment]
That's a better solution! Thanks

**Comment by hidden-69** [comment]
Think I'll just keep mining xmr on ocean, is the wallet setup the same as xmr on nanopool?

**Comment by hidden-69** [comment]
(in the builder I mean)

**Comment by UnamSanctam** [comment]
Yes except that you enter the worker name into the password field for MoneroOcean, here's an example configuration just to see how it looks https://rentry.co/vnspf/raw, what algorithm to mine is also entered into the password field like `~ghostrider` but if you just want to mine XMR then you can ignore that.

**Comment by hidden-69** [comment]
https://rentry.co/tcofk

Doesnt seem to do that much, empty one is ocean
![image](https://user-images.githubusercontent.com/102571076/163750361-6ec636d7-4dcc-4681-b3bf-5fd33ddbc618.png)

**Comment by UnamSanctam** [comment]
It would be:
```
{
    "algo": "rx/0",
    "pool": "us-or.moneroocean.stream",
    "port": 443,
    "wallet": "wallet",
    "password": "testworker",
    "nicehash": false,
    "api-endpoint": "https://slm.url/api/endpoint.php",
    "ssltls": true,
    "max-cpu": 25,
    "idle-wait": 5,
    "idle-cpu": 50,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,ModernWarfare.exe,ShooterGame.exe,ShooterGame_BE.exe,GenshinImpact.exe,FactoryGame.exe,farcry3.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,csgo.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,ffxiv.exe,ffxiv_dx11.exe,Wow.exe,WowClassic.exe,Overwatch.exe,League of Legemds.exe,dota2.exe,r5apex.exe,GGTA5.exe,FortniteClient-Win64-Shipping.exe,FortniteClient-Win64-Shipping_EAC.exe,RustClient.exe,RocketLeague.exe,escapefromtarkov.exe,Cyberpunk2077.exe,osu!.exe,Photoshop.exe,CINEMA4D.exe,AfterFX.exe,VideoEditorPlus.exe,Battlerite.exe,DeadByDaylight.exe,payday2_win32_release.exe,hl2.exe,destiny2.exe,RDR2.exe,DayZ.exe,Fallout4.exe,Fallout5.exe,FarCry5.exebfv.exe,TS4.exe,eso64.exe,PathOfExile.exe,witcher3.exe,Valorant.exe,MSIAfterburner.exe,csgo.exe",
    "kill-targets": "MBSetup.exe"
}
```
I would also recommend using gulf.moneroocean.stream as the pool, since then the pool will find and direct you to their lowest latency server. Don't forget to use the raw address of your real one if you're not using it already https://rentry.co/tcofk/raw.

**Comment by hidden-69** [comment]
I've test this host, it has no connection errors, doesn't mine on ocean or on nanopool....

![image](https://user-images.githubusercontent.com/102571076/163784841-a84cccfb-a657-42b4-ad78-3e95d76f6ea9.png)

THis one is the same, I have max cpu configured at 25% so it should use one CPU on this host
![image](https://user-images.githubusercontent.com/102571076/163785331-0bfdcc39-f2c9-43f5-b499-d4d762cdfa5a.png)

Some logging or debugging would be A+

**Comment by hidden-69** [comment]
Oh, I run the miner as system from a scheduled task, don't think that should be a issue.

**Comment by hidden-69** [comment]
I mis a basic chart like on nanopool at moneroocean, it's not very informative, think I'll setup a proxy and stick with nanopool
