### ISSUE TITLE
i made 

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/UnamWebPanel#109]
i made domain in godaddy before godaddy i was use 000webhost but saying sleeping website 
so i make domain in godaddy but after  put files in public_html not working even website not appear

**Comment by UnamSanctam** [comment]
Where do you have the hosting? Godaddy or somewhere else?

**Comment by tarekxxx** [comment]
godaddy

**Comment by UnamSanctam** [comment]
Can you take a screenshot of how it looks like? I've bought domains from GoDaddy before but never any hosting from them so I don't know what it looks like.

**Comment by tarekxxx** [comment]
![Screenshot (89)](https://user-images.githubusercontent.com/20240556/163976682-f67fc122-44f8-448d-9a4f-5b9b6cf4deb0.png)
 here we go

**Comment by UnamSanctam** [comment]
And that screenshot is from GoDaddy? If you browse to your domain (visit your website) then what does it say?

**Comment by tarekxxx** [comment]
it didint take any effect xzerox.com

**Comment by UnamSanctam** [comment]
Well you haven't uploaded the web panel yet so nothing like that should be appearing. But it looks like the host you're showing there isn't the same as your website unless you've uploaded something new since then.

**Comment by tarekxxx** [comment]
i will try with ip domain maybe DNS not configure yet let me try

**Comment by tarekxxx** [comment]
i will try with ip domain maybe DNS not configure yet let me try

**Comment by tarekxxx** [comment]
i cant make this any one can help me in this please give want upload my webpanel ?

**Comment by tarekxxx** [comment]
i can build this in wordpress ???

**Comment by UnamSanctam** [comment]
Are you sure that IP is the server where you're uploading the files? And can you show how it looks like after uploading them?
