### ISSUE TITLE
feature request - assign configuration to hardware profile

### ISSUE THREAD

**Issue by hidden-69** [UnamSanctam/UnamWebPanel#110]
It would be cool if I could assign a configuration to a hardware baseline, for example, I want 25% max cpu for I5 and 50% max cpu for I3. Could be on basis of CPU name or number or cores for example.

I tent to assign higher maxcpu on lowspec devices, they don't seem to mine otherwise.

**Comment by UnamSanctam** [comment]
Well the way xmrig calculates the core usage is `round(m_threads * (limit / 100.0))` so if the computer has 2 cores then at a limit of 20% CPU that would be 2\*0.2=0.4 rounded down to 0 cores, so it would then use no cores, but at limit of 30% CPU it would be 2\*0.3=0.6 rounded up to 1, meaning it should then use 1 core (50%).

**Comment by hidden-69** [comment]
That seems to be it!
