### ISSUE TITLE
Miners not shown  in  web

### ISSUE THREAD

**Issue by tarekxxx** [UnamSanctam/UnamWebPanel#112]
![Capture](https://user-images.githubusercontent.com/20240556/164947882-f93316a6-44e4-4f38-982c-4b61389d1672.PNG)

link is currect even try https and http both not working 

any help /?

**Comment by UnamSanctam** [comment]
Can you write to the database? You can test by going into "Configurations" and add a new configuration to see if it gets added successfully.

**Comment by tarekxxx** [comment]
i do successfully put json in default xmr and make button autorefresh on to see if there any changes but nothing change

**Comment by tarekxxx** [comment]
right now should be appear 2 PCS

**Comment by tarekxxx** [comment]
where should the problem ?

**Comment by UnamSanctam** [comment]
I mean does the configuration save? If you refresh does it show the JSON you saved? If so then the reason is most likely that the miners can't reach your site for whatever reason. It's hard for me to know since I don't own your site or anything.

**Comment by tarekxxx** [comment]
yea its saved success and website http://xxzerox.000webhostapp.com/

**Comment by UnamSanctam** [comment]
Ah, make sure to change the PHP to 7.4 or above (preferably PHP 8) if you haven't already https://www.000webhost.com/forum/t/how-to-change-upgrade-or-downgrade-php-version-of-my-website/39336.

**Comment by tarekxxx** [comment]
Done change it to PHP 8

**Comment by tarekxxx** [comment]
any next steps ? i change php 8

**Comment by tarekxxx** [comment]
...

**Comment by UnamSanctam** [comment]
Then they should appear, you shouldn't have to do anything else with 000webhost. Make sure that the URL is correct and that you're using https.

**Comment by tarekxxx** [comment]
yea that's why i ever do it but my sleep they put my old website in sleep mode then when i try do it again it now showing anything then i use https as view link give me this panel useful for me so dispointed its not working :(

**Comment by tarekxxx** [comment]
so next time where i can get bots in web panel i mean where backup where place i should backup it because if i move to another website or something which files i must backup it to keep bots watch it in panel even move to somewhere ?

**Comment by UnamSanctam** [comment]
The unamwebpanel.db contains all the data, but even if you don't backup any data the miners will still get re-added whenever they first connect again.

**Comment by tarekxxx** [comment]
aha thanks sir for make you tired with me Mr Unam
