### ISSUE TITLE
datatables

### ISSUE THREAD

**Issue by hidden-69** [UnamSanctam/UnamWebPanel#113]
Not sure if you're familiar or already using it, but datatables might make things a lot easier: https://datatables.net/examples/api/multi_filter.html

**Comment by UnamSanctam** [comment]
Yes I already use it in the panel to show the miners. Though since all the data is server-sided I have to build the things into the backend myself, the default datatables is only (thoroughly) made for client-sided data.

**Comment by hidden-69** [comment]
Cool I'll close this then
