### ISSUE TITLE
just delete old panel and updated it i  got this eror

### ISSUE THREAD

**Issue by ahmedjafari** [UnamSanctam/UnamWebPanel#117]
just delete old panel and updated it i  got this eror

**Comment by ahmedjafari** [comment]
https://ibb.co/kxcvfmy

**Comment by UnamSanctam** [comment]
Did you make sure to replace all files? unamwebpanel.db included?

**Comment by ahmedjafari** [comment]
i deleted all  and  put new files only

**Comment by UnamSanctam** [comment]
Hmm, I tried rezipping it and reuploaded the .zip in the "Releases" https://github.com/UnamSanctam/UnamWebPanel/releases, try redownloading v1.5.0 incase maybe some file was wrong.

**Comment by ahmedjafari** [comment]
same thing is still happing @UnamSanctam

**Comment by ahmedjafari** [comment]
hey hey
the problem my side
i fixed it

**Comment by ahmedjafari** [comment]
still did not fixed i  tried re downloading and deleting it   zipping and unzipping

still same error showing something about datatables

**Comment by ahmedjafari** [comment]
@UnamSanctam

**Comment by ahmedjafari** [comment]
https://datatables.net/manual/tech-notes/7

**Comment by UnamSanctam** [comment]
Ah, could maybe be the time formatting for old miner? I'll try and reupload one with a null check.

**Comment by ahmedjafari** [comment]
alright ;) take your time bro

**Comment by UnamSanctam** [comment]
You can try and redownload version 1.5.0 now, it should work.

**Comment by ahmedjafari** [comment]
all ok now ... but i think u did bring the old table for now

**Comment by UnamSanctam** [comment]
>all ok now

Ok good.

>but i think u did bring the old table for now

What do you mean?

**Comment by ahmedjafari** [comment]
no it;s ok do not worry  thanks bro
