### ISSUE TITLE
Bot names

### ISSUE THREAD

**Issue by Werlrlivx** [UnamSanctam/UnamWebPanel#122]
if i have multiple bots active with the same name will they show up as the same one on the panel or as multiple bots

**Comment by UnamSanctam** [comment]
Different ones, the unique ID is currently decided by the computer name and CPU name:
https://github.com/UnamSanctam/UnamWebPanel/blob/3426eb84034163dba22a955f37158e524109bfb8/UnamWebPanel/api/endpoint.php#L16
