### ISSUE TITLE
Web Panel

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/UnamWebPanel#126]
Good afternoon Unam. Please tell me, the screenshot shows how all the fields on the panel are mixed and are not displayed beautifully. Why is this happening?
![1](https://user-images.githubusercontent.com/36513967/166677670-f5b807f6-ac4e-4b24-bbbb-55b0aa82c8ee.jpg)

**Comment by UnamSanctam** [comment]
Reload the page, the datatable plugin does that if you zoom or anything (since columns do not get recalculated by that).

**Comment by masterjek** [comment]
Thanks for the answer. I'll ask here so as not to open a new topic. My web panel very often slows down, pages do not open well or cannot load at all. There is one error in the error folder - ERROR:
An error occured:
SQLSTATE[HY000]: General error: 1 no such column: ms_activewindow
Debug Trace:
Could this error be causing the panel to work slowly?

**Comment by UnamSanctam** [comment]
That error would cause a miner not to be added, that would be caused by your database not being updated. But most likely any slowdowns would be caused by your host.

**Comment by masterjek** [comment]
It turns out that some of the miners are not recorded in the database? I noticed that on version 1.4.2 I had 11500 miners. After switching to version 1.5.0, I got 9400 miners.

**Comment by UnamSanctam** [comment]
Yes you need to update your database, endpoint.php is trying to add fields that does not exist in your database version.

**Comment by masterjek** [comment]
So I loaded the empty database that came with version 1.5.0. And after loading version 1.5.0 of the panel along with an empty database, miners quickly began to appear there, but as I understood, many simply were not added.

**Comment by UnamSanctam** [comment]
No if you have the 1.5.0 database all will be added correctly, I don't know if that error appeared before or after you update but most likely before you updated the database if you have the 1.5.0 one currently.

**Comment by masterjek** [comment]
As I understand it, in order to check everything, I'll just now delete the error from the folder on the hosting. And in the future, if an error occurs, the report will appear there again, right?

**Comment by UnamSanctam** [comment]
Yes exactly.

**Comment by masterjek** [comment]
I also wanted to clarify one more question. On hosting, is there a difference to which files to grant rights? I have permissions for most files - 644 for some 755.

**Comment by UnamSanctam** [comment]
You usually have 755 for directories/folder and 644 for files.

**Comment by masterjek** [comment]
So for the operation of the panel is this normal? Or do some files need 777 permissions?

**Comment by masterjek** [comment]
Thanks for the help.

**Comment by masterjek** [comment]
Unam tell me please I'm trying to figure out the problem of the slow work of the web panel on the hosting. I found the following error on the hosting - [Wed May 04 06:11:35.119932 2022] [core:crit] [pid 24349] (13)Permission denied: [client 36.150.60.24:62209] AH00529: /home/controlp/public_html/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/controlp/public_html/' is executable
Could this be the reason why the web panel is slow?

**Comment by UnamSanctam** [comment]
Probably not, but you should make sure that the .htaccess file can be used, make sure that the file has permissions 644 and that the parent folder has permissions 755.

**Comment by masterjek** [comment]
Thank you very much

**Comment by masterjek** [comment]
Unam Please tell me if I have purchased hosting and domain for my panel, I can stop hosting and transfer the panel to my computer where I installed Windows 10 Pro? I just don't know if it's possible to connect a domain on my computer for the web panel to work?

**Comment by UnamSanctam** [comment]
Yes of course, the domain (via the DNS) usually only points to an IP so you can just change that to the web panel computers IP instead.

**Comment by masterjek** [comment]
And I also understand correctly that when I transfer the panel to my computer, I should not turn it off at all for the web panel to work properly?

**Comment by masterjek** [comment]
And I also understand correctly when I transfer the panel to my computer. Should I not turn off the computer so that the panel can work?

**Comment by UnamSanctam** [comment]
Yes it can only connect to the web panel if your computer is running (the webserver is running) so if it's down then eventually it will go to the "Remote Configuration" settings if you have that enabled, if you don't have "Remote Configuration" enabled it will continue using the web panel settings until told otherwise.

**Comment by masterjek** [comment]
I'm still new to this. I installed on my computer php. Launched php - http://localhost:8000. After in the folder with php I am hosting web panel files. When opened in a browser - http://localhost:8000/ - I get an error - The required SQLite PDO driver IS NOT enabled. And I understand that I'm doing something wrong and I'm still far from success?

**Comment by UnamSanctam** [comment]
What exactly did you install? Apache? XAMPP? Nginx? Either you'll have to install php-sqlite or you might have to enable pdo_sqlite inside php.ini.

**Comment by masterjek** [comment]
I have just downloaded the archive from the site - https://windows.php.net/download#php-8.1 and everything unpacked the archive to the root of the system disk in a folder php and copied the web panel files to the same folder. What you listed above, I did not download or install.

**Comment by UnamSanctam** [comment]
Then you'll probably have to uncomment `extension=php_pdo_sqlite.dll` or something similar inside your php.ini file.

**Comment by masterjek** [comment]
I do not have such a line in the file php.ini. I have installed Apachi, MySQL, PHP, phpMYadmin - I placed all this in the root of drive C in a folder called server. I checked that php, mysql, phpmyadmin everything is working properly. But then I can’t figure out where to place the web panel files and how to launch it?

**Comment by UnamSanctam** [comment]
Well I'd much rather recommend using a "real" web server like Apache (personal preference) instead of trying to use the built-in PHP one (especially since it's a single-threaded one only meant for development if I remember correctly).

**Comment by masterjek** [comment]
So I installed on my computer Apache. But I don’t know how to launch the web panel on it.

**Comment by UnamSanctam** [comment]
Usually you simply paste all the files into the `htdocs` folder inside the Apache folder. Then if Apache is running you should be able to visit http://localhost/ to be able to view the web panel.

**Comment by masterjek** [comment]
I did everything as you said above. now at localhost I see I attach a screenshot
![Screenshot_2](https://user-images.githubusercontent.com/36513967/166840110-dee59d3d-2505-4a64-8c95-d21b86b53272.jpg)

**Comment by UnamSanctam** [comment]
I'm not sure how much you've set up but toy also need to set up PHP with the Apache, follow this guide https://www.sitepoint.com/how-to-install-php-on-windows/#installapacheoptional.

**Comment by masterjek** [comment]
Just a huge thank you for the instructions, everything turned out the panel opened at localhost. But then I don’t understand what to do, all miners work with the panel at the address - https://controlpanel29.com/api/endpoint.php. Naturally opening localhost i get just an empty table without miners. It turns out I need it in the builder where API endpoint I have to write localhost. But I end up losing control of all my previous workers who work at https://controlpanel29.com/api/endpoint.php right?

**Comment by UnamSanctam** [comment]
You should redirect the https://controlpanel29.com/ domain to your own (external) IP instead of whatever webhost it's pointing to right now. All a domain is (in simple terms in this context) is an alias for an IP.

**Comment by masterjek** [comment]
Do I understand correctly that I should do this at the domain registrar?

**Comment by UnamSanctam** [comment]
Yes, or technically you change it in your DNS but many domain registrars have their own DNS.

**Comment by UnamSanctam** [comment]
Yes `localhost` is the local computer, if you want to access it from another one then either use the internal or external IP depending on where the other computer is located. Use the internal IP (usually something like 192.168.1.123) if the computer is on the same network or use the external IP (you can find it online) if it's on a computer outside your network.
