### ISSUE TITLE
Bots don't knock

### ISSUE THREAD

**Issue by anbu-squad** [UnamSanctam/UnamWebPanel#13]
Hello Unam, thanks for the updates, waited a long time =)

Panel problems
Bots don't knock
The base file is available via a direct link

Miner build checked - works

Ubuntu 
PHP 8.0.12
Apache2 2.4.29

**Comment by UnamSanctam** [comment]
It works fine, make sure that your host isn't blocking them, and make sure that the URL is 100% correct, also make sure that you use the correct protocol http/https (only use https if you actually have a certificate).

**Comment by anbu-squad** [comment]
work
