### ISSUE TITLE
LocalHost And WebPanel

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/UnamWebPanel#130]
Good evening Unam. Help please, I still don't understand if in the builder in the field API I point - http://localhost:55555/api/endpoint.php. Then the panel displays the miners running on my machine from other computers it does not display working. How do I correctly specify in the field API link to localhost To display workers from other machines?

**Comment by UnamSanctam** [comment]
Localhost is just the local host, meaning your own computer, if you connect to localhost on another computer then that computer will just try to connect to itself. If you want external computers to connect to your own computer then you need to use your external IP instead of localhost (127.0.0.1).

**Comment by masterjek** [comment]
I understand correctly in the builder in the field API i have to point out - http://127.0.0.1/api/endpoint.php
Then opening the panel through localhost on my computer, I will see workers from other machines, right?

**Comment by UnamSanctam** [comment]
No you'll have to point to your external IP, just search for `what's my ip` on Google and many sites will tell you what your IP is, and then enter that into the field, for example http://98.148.67.112/api/endpoint.php (this is just some random IP I wrote). What I meant by `127.0.0.1` is that `localhost` is technically just an alias for `127.0.0.1`.

**Comment by masterjek** [comment]
In the builder in the field API I specified the external ip of my computer. Run the miner on my computer. start the server Apache open - http://localhost/?page=miners&id= and I don't see my worker in the table. I don't understand what I'm doing wrong?

**Comment by UnamSanctam** [comment]
Well yeah you can't connect to your own computer with the external IP, you have to use localhost on your own computer and the external IP for external computers.

**Comment by masterjek** [comment]
Did I understand correctly that in order to check I have to run the miner on another machine with a different ip than my external one? And then the worker will appear in the panel in the table right?

**Comment by UnamSanctam** [comment]
Yes exactly.

**Comment by masterjek** [comment]
I started the miner on another machine with a different IP address than my external one. open in browser - http://localhost/index.php?page=miners&id= the panel opens, but there is no worker in it.
I may not understand. The web panel can generally work through localhost without buying a domain and display workers from other computers? Because I ran the panel through Apache on my PC open http://localhost/index.php?page=miners&id= But no workers.
In the builder in API i said so - http://My external ip/api/endpoint.php.
I looked at the external ip on the site - 2ip.ru
I did everything without errors, but the worker in the panel is not shown.

**Comment by masterjek** [comment]
Thanks for the help. Now at least I understand what the reason is.

**Comment by masterjek** [comment]
Unam I will open the topic again, I thought I understood everything and decided. I installed the server Apache to a dedicated server. I'm scanning port 80 on the server - Port 80 is open on 195.93.172.35. On a dedicated server, I launched the panel - http://localhost/index.php?page=miners&id= I run the miner on my computer And again there is no worker in the web panel. I can't figure out what's wrong here? The port is open. I have a guess. Maybe the worker is not displayed due to the fact that the miner is running on a computer on which port 80 is closed?

**Comment by UnamSanctam** [comment]
If that's the IP then your webserver isn't set up correctly http://195.93.172.35/api/endpoint.php, don't forget to set up PHP and such as well. Ports only have to be open on the server and not on anything else.

**Comment by masterjek** [comment]
In the builder, in the field API I pointed - http://195.93.172.35/api/endpoint.php. Php I configured according to the instructions, you previously sent me a link to the site with the settings. I understand correctly if the web panel opens fully, then everything is set up correctly? The only thing at startup Apache - I am getting a warning - Could not reliably determine the server's fully qualified domain name, using ::1. Set the 'ServerName' directive globally to suppress this message - I do not know if this affects the work of the web panel?

**Comment by UnamSanctam** [comment]
Yes if the web panel opens then it's correct, but it doesn't open externally as you can see if you visit http://195.93.172.35/api/endpoint.php, meaning that some setting is wrong. I have never set up Apache on Windows (all my servers are Linux) so I'm not fully sure about the whole process.

**Comment by masterjek** [comment]
For me, this is the first time. =) In any case, thanks for the help. I will try to find what is wrong.

**Comment by masterjek** [comment]
Unam tell me please. I looked in the error folder of the web panel. There is always the same error. I'm attaching a screenshot of the error. Can this error cause the fact that workers are not displayed in the web panel?
![1](https://user-images.githubusercontent.com/36513967/167930929-4f64b8ab-54f2-4320-a7e6-9e68a2347d0b.jpg)

**Comment by UnamSanctam** [comment]
That's just a warning about the deprecation about FILTER_SANITIZE_STRING, it doesn't affect anything. The reason that no workers appear isn't due to the web panel but due to the server, you won't find any errors inside the web panel for it.

**Comment by masterjek** [comment]
Good afternoon Unam. I was able to set up Apache now the workers are connected to the web panel via an external ip. The problem is that earlier in the builder I have in the field API I have a domain - controlpanel29.com. I remember earlier you told me that I need to redirect the domain to an external ip. Here is what I did in the domain control panel.
![Screenshot_1](https://user-images.githubusercontent.com/36513967/168075058-32b10314-5818-4b2b-97f4-8ce1ece2070f.jpg)
195.93.172.35 - This is the external address of the dedicated server where I'm just running the web panel.
I also added an entry to the file hosts - 195.93.172.35           controlpanel29.com
after all steps my panel is at https://controlpanel29.com stopped opening but all the workers were not transferred to the panel that works on localhost.
Did I redirect something in the domain incorrectly?

**Comment by masterjek** [comment]
Good evening Unam. Please tell me, I was able to set up the web panel on localhost and new workers appear, and I redirected the domain to external ip. But I ran into another problem. some miners are displayed with an error, this happened before, but I created in the configuration JSON with another pool and miners with the status eror connected to the new configuration with JSON and mined already on a new pool. Now after transferring the web panel on localhost, miners with an error switch to another configuration, but they never start mining on a new pool, and remain with an error. There may be a reason for moving the web panel to localhost?

**Comment by UnamSanctam** [comment]
No that shouldn't make a difference, make sure that the configuration is there and make sure that the configuration is correct.

**Comment by masterjek** [comment]
Can you tell me more, they advised me to file hosts Add a note - 195.93.172.35 controlpanel29.com. I can't figure out what is it for?

**Comment by UnamSanctam** [comment]
That would cause the computer you add that into to hosts file to connect to 195.93.172.35 whenever you try to reach controlpanel29.com instead of asking the DNS (where you point where the domain should lead).

**Comment by masterjek** [comment]
Tell me more, does it matter before I had a domain with https and now it has become http And in the builder in the field API given since https

**Comment by UnamSanctam** [comment]
Yes, they are two different protocols, you can get a free certificate for your domain/server using Let's Encrypt.

**Comment by masterjek** [comment]
I bought a certificate from a hosting company. And it's valid for another year. But when I moved the site to VPS  on Apache the certificate has flown I just don't know if it's possible to transfer the certificate that I previously bought there.

**Comment by UnamSanctam** [comment]
You'll need the certificate files to be able to use that certificate inside the webserver (Apache), you can also get a free Let's Encrypt certificate easily (though harder than it would be on Linux) https://commaster.net/posts/how-setup-lets-encrypt-apache-windows/.

**Comment by masterjek** [comment]
Good afternoon Unam. Please tell me if you know the reason. I still launched the panel on a computer with Windows on Open Server. But I ran into a problem writing to the database occurs every 5 minutes i had 10000 workers But now only 67 of them have appeared. And new ones appear every 10-15 minutes. What can cause such a slow write to the database?

**Comment by UnamSanctam** [comment]
Could be a slow internet though it shouldn't really be, could be a slow disk though it shouldn't really be that either. Have you changed/updated the domains DNS again recently or something? In case the computers haven't gotten the new updated DNS. Could also be something like that your Apache is only working single-threaded but by default I don't think any releases will do that, when you installed PHP you did rename `php.ini-production` to `php.ini` correct?

**Comment by masterjek** [comment]
Ip in DNS I updated a couple of hours ago. php.ini-production I renamed to php.ini. The most interesting behavior is that it restores 60 workers in the panel in just 10-20 seconds. And after 60 new workers appear, maybe once every 30 minutes 1 appears. I just don't know in which direction to look for the error? Almost all hostings, and I have already tried 10 of them, will soon ban the panel due to the high load. My friend and I checked her work on Linux 3,000 workers recovered after launch. And after the server with an 8-core processor and 8GB of RAM simply stopped working, it did not have enough resources to ensure the operation of the panel. I don’t know what to do with the panel anymore, 10,000 workers communicate and I have now lost control over them.

**Comment by UnamSanctam** [comment]
You could possibly move to MySQL instead of SQLite, most people with big a large amount of miners do that but that also means you have to set up MySQL and everything (web panel originally used MySQL during development but moved to SQLite since most probably wouldn't be able to set it up). But before doing any of that you could also possibly try this custom web panel, just replace yours with this one: [UnamWebPanel.zip](https://github.com/UnamSanctam/UnamWebPanel/files/8693596/UnamWebPanel.zip), it's a custom version with possible SQLite optimizations that I made for someone for testing.

**Comment by masterjek** [comment]
Thanks for the web panel with settings. I uploaded a new panel, put the database empty. The most interesting thing for me was 75 workers entered into an empty database in a couple of seconds, This is exactly the amount that was in the previous database, which managed to fill up. And all for 76 workers the base stopped and writes down 1-2 workers in 10-15 minutes.

**Comment by UnamSanctam** [comment]
Then it sounds like the problem doesn't have anything to do with that, sounds like they can't/aren't connecting to your web panel. But since you only updated the DNS a couple of hours ago it's possible that they haven't switched yet, DNS propagation usually takes up to 72 hours to reach worldwide.

**Comment by masterjek** [comment]
Does it matter where I take public DNS I use from - dash.cloudflare.com? And there is a mystery for me, yesterday when my friend and I tested on VPS with Linux. I just redirected the ip to the DNS server with Linux 4,000 workers have already returned in a minute. Could this be due to the difference between Linux and Windows?

**Comment by UnamSanctam** [comment]
Could be but the DNS won't update in a minute though it depends on the TTL you have set. I have never set up a webserver on Windows except from using XAMPP for testing, you could temporarily set up XAMPP and see if it's due to your configuration. Just download and install XAMPP, then copy the web panel into `C:/xampp/htdocs` and then in the XAMPP control panel start Apache.

**Comment by masterjek** [comment]
TTL set to auto But there is also option 1 min, and other. Thanks for the advice. I'm going to try now XAMPP.

**Comment by masterjek** [comment]
XAMPP I don't understand what he is asking me to do? Disable UAC?
![1](https://user-images.githubusercontent.com/36513967/168443537-e578bce3-8504-4b4a-a00b-170d4448c68a.jpg)

**Comment by UnamSanctam** [comment]
You should preferably install it directly to the C: drive (C:\xampp) like all other similar things (Apache, msys and many more).

**Comment by masterjek** [comment]
I installed XAMPP. Launched a web panel there and all the same the fastest set of 78 miners. And all at 78 stop and then set one miner at a time at different times 1 minute, 5 minutes, 10 minutes and so on.

**Comment by masterjek** [comment]
There in the line Apache There is a menu - Access.log
so open it - Access.log i see the following lines

172.73.5.47 - - [14/May/2022:22:11:08 +0300] 
88.192.36.230 - - [14/May/2022:22:11:08 +0300]

I didn’t copy everything, but from the records I see that these are miners who connect to the server, do I understand correctly?

But there are just thousands of records, or even more, but now only 80 miners are displayed in the panel.

**Comment by UnamSanctam** [comment]
Try adding `file_put_contents('request.log', file_get_contents('php://input'), FILE_APPEND);` to line 4 of endpoint.php and it will output all connections into request.log.

**Comment by masterjek** [comment]
Yes file request.log created. But in it everything is a solid line. It's hard to figure out how many workers there are.

**Comment by UnamSanctam** [comment]
Then try `file_put_contents('request.log', file_get_contents('php://input').'\r\n', FILE_APPEND);` which will add a line break.

**Comment by masterjek** [comment]
added the line as you said I counted the number \r\n I opened it in a document Microsoft Word And With the command Ctrl+f - To find I was looking for \r\n - I didn’t go through the entire document, but I already counted 150 miners But in the web panel I see only 82.

**Comment by UnamSanctam** [comment]
You'll have to post the request.log somehow since otherwise there's nothing for me to do, also the same miner will of course appear again each time it connects.

**Comment by masterjek** [comment]
Now I see 86 miners in the panel. 
[request.log](https://github.com/UnamSanctam/UnamWebPanel/files/8693773/request.log)

**Comment by masterjek** [comment]
But if you need what the logs show Apache - https://anonfiles.com/t8gb1eg9y4/accesslog_txt

**Comment by UnamSanctam** [comment]
I had to remove duplicates in your request.log and after doing so I can see that your request.log contains 75 different miners.

**Comment by masterjek** [comment]
https://cdn-125.anonfiles.com/N5vc16g8ye/f267dc55-1652561290/accesslog.txt - Try this link checked downloaded

**Comment by UnamSanctam** [comment]
Ah the majority of your access log is from an xmrig-proxy connection so it's a bit hard to see.

**Comment by masterjek** [comment]
xmrig-proxy - I don't have it there at all. Or does it mean that he is working somewhere hidden?

**Comment by UnamSanctam** [comment]
No but you have a lot of miners trying to connect to your server for mining instructions, you might have your domain set a pool somewhere.

**Comment by masterjek** [comment]
I understand everything. These are the miners that I am configuring in the web panel. But now they are not in the panel and they cannot get the configuration from it.

**Comment by masterjek** [comment]
I wanted to ask And if I pay you. You could look at the server, maybe I really configured something wrong. If you can set up and help me, what is the price?

**Comment by UnamSanctam** [comment]
Haha well I won't ask for any money but I can look at the server and see if I can find anything if you want me to.

**Comment by masterjek** [comment]
Yes of course I agree. Tell me just how can I personally send you the data to access the server?

**Comment by UnamSanctam** [comment]
You can email me at unams@protonmail.com.

**Comment by masterjek** [comment]
I sent you a letter. Please write if it worked or not.

**Comment by UnamSanctam** [comment]
I'm checking it right now.

**Comment by masterjek** [comment]
Thank you. I sent you XMR for help. Let me know when I can join the server.

**Comment by UnamSanctam** [comment]
Thank you I appreciate it, you can reconnect to the server now, I remade your certificates and fixed where the XAMPP SSL configuration pointed (and a few other things) and a lot have connected so far. It's currently using XAMPP which is generally unsecure (it's for development environments) but you can still use it just fine, especially since you're only using Apache from it.

**Comment by masterjek** [comment]
Thank you very much. I suffered for 5 days and did not set it up. Once again, thank you very much. I'm just wondering if I made a lot of mistakes in the settings?

**Comment by UnamSanctam** [comment]
No just the certificates and paths for them were weird, everything else was correct.

**Comment by masterjek** [comment]
Understood. Thank you very much for your help.
