### ISSUE TITLE
Unam Web Panel

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/UnamWebPanel#139]
Good afternoon Unam. Please tell me on the page login.php i can change the caption - Unam Web Panel To another entry? If it is possible, then how to do it?

**Comment by UnamSanctam** [comment]
Yes the login page is this file: https://github.com/UnamSanctam/UnamWebPanel/blob/master/UnamWebPanel/login.php, you can change any of the texts there.

**Comment by masterjek** [comment]
Thanks for the help.
