### ISSUE TITLE
Recommended Web Host?

### ISSUE THREAD

**Issue by Smurfboi007** [UnamSanctam/UnamWebPanel#14]
Currently, I'm planing on using Hostinger (Paid), but do you recommend any other web host?

**Comment by UnamSanctam** [comment]
I always host things myself so I've never used any webhosts specifically, but I would recommend either a bulletproof host or a bulletproof domain so that it won't get removed.

**Comment by Smurfboi007** [comment]
Alright, So a SSL Certificate website with cloudflare and a .com domain should do, right?

**Comment by UnamSanctam** [comment]
Yes though none of that is bulletproof so it can be removed of course.

**Comment by Smurfboi007** [comment]
So what makes a website bulletproof?

**Comment by Smurfboi007** [comment]
Oh ok, thanks for the explanation!
