### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by DuyLvzy123** [UnamSanctam/UnamWebPanel#140]
I want to learn more but how to use this?

**Comment by UnamSanctam** [comment]
You first host it somewhere https://github.com/UnamSanctam/UnamWebPanel#setup, and then enter the URL of the site into the miner https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#api-endpoint-url.

**Comment by DuyLvzy123** [comment]
> You first host it somewhere https://github.com/UnamSanctam/UnamWebPanel#setup, and then enter the URL of the site into the miner https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#api-endpoint-url.

<img width="959" alt="image" src="https://user-images.githubusercontent.com/99333895/170816429-ca59602d-7531-45cc-bd7b-77cd6f5a1183.png">
Ayo wtf, french language. Ưhen i switch to english and reload the page, it still shows french text

**Comment by DuyLvzy123** [comment]
> > You first host it somewhere https://github.com/UnamSanctam/UnamWebPanel#setup, and then enter the URL of the site into the miner https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#api-endpoint-url.
> 
> <img alt="image" width="959" src="https://user-images.githubusercontent.com/99333895/170816429-ca59602d-7531-45cc-bd7b-77cd6f5a1183.png">
> 
> Ayo wtf, french language. When i switch to english and reload the page, it still shows french text

**Comment by UnamSanctam** [comment]
Haha it auto-detects the language in your browser that's why, but if you change the language then it should change "forever" unless there's some errors. Since you're using 000webhost make sure that you change the PHP version to 7.4 or above https://www.000webhost.com/forum/t/how-to-change-upgrade-or-downgrade-php-version-of-my-website.

**Comment by DuyLvzy123** [comment]
> Haha it auto-detects the language in your browser that's why, but if you change the language then it should change "forever" unless there's some errors. Since you're using 000webhost make sure that you change the PHP version to 7.4 or above https://www.000webhost.com/forum/t/how-to-change-upgrade-or-downgrade-php-version-of-my-website.

<img width="958" alt="image" src="https://user-images.githubusercontent.com/99333895/170817930-218dda5b-7f7a-4a59-a101-83ac2705f55c.png">
Do I need to wait??

**Comment by UnamSanctam** [comment]
Maybe, but I think I've heard about there being problems with their upload function.

**Comment by DuyLvzy123** [comment]
> Maybe, but I think I've heard about there being problems with their upload function.

omg finally, It works!!

**Comment by DuyLvzy123** [comment]
> Maybe, but I think I've heard about there being problems with their upload function.

I changed my php version from 7.2 to 8.0 by mistake, is it ok?

**Comment by UnamSanctam** [comment]
Yes anything above 7.4 will work.

**Comment by DuyLvzy123** [comment]
> Yes anything above 7.4 will work.

So 8.0 is it better?

**Comment by UnamSanctam** [comment]
Yes sure.

**Comment by DuyLvzy123** [comment]
> Yes sure.

what should I do now??
<img width="956" alt="image" src="https://user-images.githubusercontent.com/99333895/170818249-91807a50-a06e-4501-8fcc-b1e3c9661193.png">

**Comment by UnamSanctam** [comment]
Enter `https://websiteurl/api/endpoint.php` into the "API Endpoint URL" inside the miner builder.

**Comment by DuyLvzy123** [comment]
> Enter `https://websiteurl/api/endpoint.php` into the "API Endpoint URL" inside the miner builder.

can i add servers like monero, etc at the same time?

**Comment by UnamSanctam** [comment]
Yes add the URL into all the miners (XMR and ETC in this case).

**Comment by DuyLvzy123** [comment]
> https://websiteurl/api/endpoint.php

alr thx you again!, What I need most is how to make the virus undetectable, maybe this part I will do it myself.

**Comment by DuyLvzy123** [comment]
> Yes add the URL into all the miners (XMR and ETC in this case).

like this?:https://duylikeminers.000webhostapp.com/api/endpoint.php

**Comment by UnamSanctam** [comment]
> > Yes add the URL into all the miners (XMR and ETC in this case).
> 
> like this?:https://duylikeminers.000webhostapp.com/api/endpoint.php

Yes exactly.

**Comment by DuyLvzy123** [comment]
> > > Yes add the URL into all the miners (XMR and ETC in this case).
> > 
> > 
> > like this?:https://duylikeminers.000webhostapp.com/api/endpoint.php
> 
> Yes exactly.

alright!

**Comment by DuyLvzy123** [comment]
> > > Yes add the URL into all the miners (XMR and ETC in this case).
> > 
> > 
> > like this?:https://duylikeminers.000webhostapp.com/api/endpoint.php
> 
> Yes exactly.

<img width="154" alt="image" src="https://user-images.githubusercontent.com/99333895/170818590-d8476c70-52d0-44c0-b72f-52820aaeb193.png">
.. what is this??

**Comment by UnamSanctam** [comment]
It's a feature to change the configuration/settings remotely using something like pastebin https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration.

**Comment by DuyLvzy123** [comment]
> It's a feature to change the configuration/settings remotely using something like pastebin https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration.

Cool!
for me that part doesn't matter, because it's quite complicated for me. Maybe in the future I will try.
bye man
