### ISSUE TITLE
Possibility to use the subdomain

### ISSUE THREAD

**Issue by elraiqq** [UnamSanctam/UnamWebPanel#141]
Hi bro 
I was asking about the possibility of using the subdomain 
To use a second panel
If it is possible, I have already uploaded the files to a subdomain, but I cannot log in to it The message of Error appears

**Comment by UnamSanctam** [comment]
Sure there's no real difference between a subdomain and a normal domain, make sure that you have PHP 7.4 or newer on the server.

**Comment by elraiqq** [comment]
Www.subdomain.maindomain.com/api/endpoint.php
It will be like this is it true

**Comment by UnamSanctam** [comment]
Technically `subdomain.maindomain.com/api/endpoint.php`, though you can add `www.subdomain.maindomain.com/api/endpoint.php` as well. `www` in front of domains is actually a sub-domain itself so if you want www then you'll have to add that into the DNS records as well.

**Comment by elraiqq** [comment]
Thank you very much I will try it
