### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/UnamWebPanel#142]
Unam please tell me. I'll attach a screenshot with an error, can I disable or remove it? This file with an error becomes 10 GB in a couple of hours and its size keeps growing.
![Screenshot_1](https://user-images.githubusercontent.com/36513967/170842605-59da7141-6097-489b-a5c0-39e3b94e4209.jpg)

**Comment by UnamSanctam** [comment]
It's because you have PHP 8.1 and they have now deprecated that constant, I'm changing it in the next version but you can also replace `__UNAM_LIB\unam_lib.php` with this one [unam_lib.zip](https://github.com/UnamSanctam/UnamWebPanel/files/8791882/unam_lib.zip) in the meantime if you want to.

**Comment by masterjek** [comment]
Thank you very much, everything replaced the file with the error disappeared.
