### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by DogusCyk** [UnamSanctam/UnamWebPanel#143]
![image](https://user-images.githubusercontent.com/81167210/170875969-59180bc5-b865-4810-b28f-cd211b8a243e.png)
what exactly is the error

**Comment by UnamSanctam** [comment]
It means that the miner cannot connect to the pool with the settings you use.

**Comment by DogusCyk** [comment]
These are the settings I always use

**Comment by DogusCyk** [comment]
what should I do

**Comment by UnamSanctam** [comment]
Yes but that's what it means, it says error if there's no active pool. Post your settings here.

**Comment by DogusCyk** [comment]
[settings.zip](https://github.com/UnamSanctam/UnamWebPanel/files/8793583/settings.zip)

**Comment by DogusCyk** [comment]
If the panel shows an error, does it mean that the miner is not working, or is it just related to the panel?

**Comment by UnamSanctam** [comment]
Hmm weird, their pool isn't working for me:
<img src="https://user-images.githubusercontent.com/10323655/170876730-29e5c7cf-0113-4409-853d-69075ea04558.png">

**Comment by DogusCyk** [comment]
okey i am waiting

**Comment by DogusCyk** [comment]
did it work in other pools?

**Comment by UnamSanctam** [comment]
Well I tried with MoneroOcean and it worked there, not sure about others, I'll have to generate an RTM wallet address first.

**Comment by DogusCyk** [comment]
ah if you want i can send you my wallet address

**Comment by DogusCyk** [comment]
so that means the miner didn't mining, right?

**Comment by DogusCyk** [comment]
and its my wallet address
RTXWP4RojCd6tCjuD3QAKDQBLdicqjhF2n

**Comment by DogusCyk** [comment]
oh did you find anything ?

**Comment by UnamSanctam** [comment]
Looks like they have might something wrong with their pool, flockpool isn't even working for me using the normal xmrig 6.17.0, so I copied over some things from the MO xmrig version and it seems to work now, test this https://anonfiles.com/r163h5lfy3/Silent_Crypto_Miner_Builder_zip.

**Comment by DogusCyk** [comment]
ah yes it seems to work in web panel thanks

**Comment by DogusCyk** [comment]
but why does it show as etc 0/h on the panel?

**Comment by UnamSanctam** [comment]
Do you have enough VRAM? Can you expand the information (press the '+') and take a screenshot?

**Comment by DogusCyk** [comment]
![image](https://user-images.githubusercontent.com/81167210/170883830-ece208a3-4b4d-4b36-ae19-cd47fabde518.png)

**Comment by UnamSanctam** [comment]
Can you try changing it to mining Ubqhash (Ubiq) to see if it's due to the VRAM?

**Comment by DogusCyk** [comment]
okey

**Comment by DogusCyk** [comment]
pool and wallet will still work if I put random letters right because I don't have an address on my wallet

**Comment by DogusCyk** [comment]
rip translate

**Comment by UnamSanctam** [comment]
Just use ubiq-eu1.picopool.org:8443 (stratums) as the pool and use your normal wallet, it uses the 0x format for wallets.

**Comment by DogusCyk** [comment]
ubq miner is not working for me

**Comment by UnamSanctam** [comment]
What do you mean by not working?

**Comment by DogusCyk** [comment]
When I open the miner, the explorer comes up but closes back as it came.

**Comment by UnamSanctam** [comment]
Means that some settings were wrong, don't forget to change it to stratums (SSL).

**Comment by DogusCyk** [comment]
oh yes i forget this 🤣

**Comment by DogusCyk** [comment]
but still same

**Comment by UnamSanctam** [comment]
Then post your settings.

**Comment by DogusCyk** [comment]
The problem is from the wallet address, now it's working, I'm waiting for it to come to the panel

**Comment by DogusCyk** [comment]
![image](https://user-images.githubusercontent.com/81167210/170884454-800e21ff-b247-4d1c-837d-7431570addcb.png)

**Comment by DogusCyk** [comment]
it seems to work but why is this happening in etc

**Comment by UnamSanctam** [comment]
Yeah then it's 0 H/s because your GPU doesn't have 3GB of free VRAM to mine.

**Comment by DogusCyk** [comment]
but my video card is 4gb

**Comment by DogusCyk** [comment]
and it was working before

**Comment by UnamSanctam** [comment]
Yeah but that just means that you're using at least 1GB of VRAM already, you'll need to close some things that are using your VRAM.

**Comment by DogusCyk** [comment]
hmm i don't know, when the miner was running, there was nothing that was using the video card anyway

**Comment by UnamSanctam** [comment]
Most things that use hardware acceleration take up VRAM, such as your browser, Discord, Steam, any games, videos and everything else.

**Comment by DogusCyk** [comment]
![image](https://user-images.githubusercontent.com/81167210/170884716-a8a7986f-f4b5-4001-9b2d-ba4fdd7b113c.png)
i think you are talking about this ?

**Comment by DogusCyk** [comment]
![image](https://user-images.githubusercontent.com/81167210/170884737-345df4b7-8273-497a-8121-54b2cfb3771c.png)

**Comment by DogusCyk** [comment]
I will close discord and similar applications and try again.

**Comment by UnamSanctam** [comment]
Yes so it's using 700MB at the moment, try starting the miner and see if it goes up.

**Comment by DogusCyk** [comment]
ah yes, it seems to be working now as you said

**Comment by DogusCyk** [comment]
thanks for your help sorry if i wasted your time

**Comment by UnamSanctam** [comment]
Haha no it's no problem, you helped me find an issue with xmrig (or technically the pool).

**Comment by DogusCyk** [comment]
i'm glad if i helped haha ​​have a nice day
