### ISSUE TITLE
Unknown error.

### ISSUE THREAD

**Issue by Zem0rt** [UnamSanctam/UnamWebPanel#146]
I have some unknown error: (Something went wrong.) what could it lead to? this is after the update.
![IMG_20220602_193523](https://user-images.githubusercontent.com/99068726/171690850-751935fb-e6ff-4cbe-b541-98e64f434154.jpg)

**Comment by UnamSanctam** [comment]
Make sure that you have PHP 7.4 or newer and that you have replaced all the files.

**Comment by berkantdu123** [comment]
> Make sure that you have PHP 7.4 or newer and that you have replaced all the files.

I got that same error, im using php 7.4 and i replaced file per file till it broke, mine somehow broke with the unam_lib.php file, works fine with the old one

**Comment by UnamSanctam** [comment]
Can you check to see if you can find any log file inside `__UNAM_LIB\Logs` or any error.log somewhere (search all folders)?

**Comment by berkantdu123** [comment]
> Can you check to see if you can find any log file inside `__UNAM_LIB\Logs` or any error.log somewhere (search all folders)?

Searched in all folders manually, couldnt find any somehow

**Comment by berkantdu123** [comment]
![image](https://user-images.githubusercontent.com/52573108/171749689-b9659f6f-9ccc-41e8-b3f4-adc832cad0d5.png)
And it works perfectly fine with the old unam_lib.php file on the new version (This is a vpn ip)

**Comment by UnamSanctam** [comment]
Hmm, all I changed was from filter_input to just using strip_tags, I'll install PHP 7.4 (I have PHP 8.0 right now) and test.

**Comment by UnamSanctam** [comment]
Can you try this [UnamWebPanel.zip](https://github.com/UnamSanctam/UnamWebPanel/files/8828264/UnamWebPanel.zip)? Could have been a problem with passing $maxlength to the function.

**Comment by Zem0rt** [comment]
> Can you try this [UnamWebPanel.zip](https://github.com/UnamSanctam/UnamWebPanel/files/8828264/UnamWebPanel.zip)? Could have been a problem with passing $maxlength to the function.

works for me.

**Comment by UnamSanctam** [comment]
Ok great, then that was the problem.

**Comment by berkantdu123** [comment]
> Can you try this [UnamWebPanel.zip](https://github.com/UnamSanctam/UnamWebPanel/files/8828264/UnamWebPanel.zip)? Could have been a problem with passing $maxlength to the function.

Works for me too, thank you sm for your help
