### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by anbu-squad** [UnamSanctam/UnamWebPanel#147]
Unam, hello, thanks for the function of the time, now it’s better to imagine about the work of miners in general

I'll leave here, a few more offers for the panel:

- also conclude the timid time of the miner near the status "Active"

- Add the user privileges table: User or Admin
 
- Add the output of the name of the controlling process to the work of miners: watchdog or root-kit 
(in general, for the sake of outposting the statistics of their survivability)

As far as I understand, the build with a shield, on an account without the rights of the admin, will not start?
That is, you need to collect two separate builds for the admin and for a regular user ??

I spent a bad time on tests and came to the conclusion that for example:

- If the admin account is root-kit + System
- If the user account is the launch of the watchdog in memory

Correct me if, I'm wrong =)

**Comment by UnamSanctam** [comment]
>also conclude the timid time of the miner near the status "Active"

Well the web panel doesn't really know how long it's been "Active" so the miner would have to report that I guess, but would this really be used for anything (and not just theoretically)? 

>Add the user privileges table: User or Admin

Usually you can see from the "Username" whether it's running as a user or administrator.

>Add the output of the name of the controlling process to the work of miners: watchdog or root-kit (in general, for the sake of outposting the statistics of their survivability)

Not sure what you mean by this, the rootkit doesn't watch over the miner like the watchdog does, it just hides things from API calls.

>As far as I understand, the build with a shield, on an account without the rights of the admin, will not start?
That is, you need to collect two separate builds for the admin and for a regular user ??

When you run it then it will just ask for permission to run just like any other program that needs to run as administrator (or any program started with "Run as Administrator"), and if granted then it will install it under the admin user (or the System user if "Run as System" is enabled). If you don't want it to ask for administrator rights then you'd build it without "Run as Administrator" (normal user).

>If the admin account is root-kit + System
If the user account is the launch of the watchdog in memory

No it will always run the watchdog in memory if that is enabled no matter who runs it. Likewise the only thing the rookit does is hide the processes, traffic and such if it is enabled.

**Comment by anbu-squad** [comment]
I was simply confused, I thought that I need to collect the build separately under the admin and separately for the user, because if you enable the request for the "launch from the admin" then the miner will not be set on the account of an ordinary user?

**Comment by UnamSanctam** [comment]
If you enable "Run as Administrator" then it will ask for permission and then run under the admin user, but if you have "Run as System" enabled then it will run as the System user instead which means it will run on all user accounts (normal user included). So if you have "Run as System" enabled then it will also mine on the normal user account.

**Comment by anbu-squad** [comment]
I finally understood that the "launch from the admin" is a launch with an increase in rights, that is, permission to read and write in the system areas
