### ISSUE TITLE
https://websitename.com/UnamWebPanel/api/endpoint.php

### ISSUE THREAD

**Issue by Smurfboi007** [UnamSanctam/UnamWebPanel#15]
Hello, I have Word Press on the site I'm gonna use this, and to access the UnamWebPanel, I have to go to `https://websitename.com/UnamWebPanel` and not just to the home page. I'm just wondering if the `api/endpoint.php` would change to `https://websitename.com/UnamWebPanel/api/endpoint.php` instead of `https://websitename.com/api/endpoint.php`

**Comment by UnamSanctam** [comment]
Yes exactly, if you visit https://websitename.com/UnamWebPanel/api/endpoint.php then it should say something like invalid data if it's working.

**Comment by Smurfboi007** [comment]
Okay, that is what it says so then it works. Thanks!
