### ISSUE TITLE
Date Base Web Panel

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/UnamWebPanel#151]
Good afternoon Unam. Tell me please. I can edit the database with DB Browser (SQLite) Without stopping work Apache And Web Panel? There will be no errors if the web panel itself writes to the database and through the browser I make changes to the configuration of the miners?

**Comment by UnamSanctam** [comment]
Yes that should be fine, it will only write what it needs, but you can temporarily stop Apache if you want since the miners won't care.

**Comment by masterjek** [comment]
Thanks for the help.
