### ISSUE TITLE
Default xmrig

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/UnamWebPanel#153]
Good evening Unam. All miners are connected to the panel according to the default configuration. If i take the configuration for workers and save it as Default xmrig - Workers will accept this configuration as Default xmrig?

**Comment by UnamSanctam** [comment]
Depends on what you mean, if you enter a configuration into the "Default xmrig" (that always exists) then miners set to that (which they are by default) will use that configuration. If you create a new configuration called "Default xmrig" then they won't use that.

**Comment by masterjek** [comment]
That's right, I meant to change it in the configuration Default xmrig which is in the default panel. I understood correctly that all the workers who work on "Default xmrig" continue to work on it, but with the changes made?

**Comment by UnamSanctam** [comment]
Yes if you enter a configuration into "Default xmrig" then all miners who are on that (all miners by default) will use the new configuration/settings.

**Comment by masterjek** [comment]
Thank you very much for your help.
