### ISSUE TITLE
XAMPP And WebPanel

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/UnamWebPanel#162]
Good evening Unam. I had to move the web panel to another vps. I bought a new certificate ssl. But I ran into a problem, all my workers do not appear, they are displayed in total 161 instead of 12000. And I see that there is no normal record in the database. I have already addressed this problem to you and gave you access to the server and you set it up for me there, that everything worked fine. Then you told me I incorrectly specified the path to the certificate. I have already checked 10 times these paths are all correct, but the workers are not filled. If you have time. And I'll email you access to the server, can you please see what I didn't finish there? I am willing to pay for your wasted time.

**Comment by UnamSanctam** [comment]
Open the Apache config and check the SSL paths to make sure they are correct in all locations.

**Comment by masterjek** [comment]
![1](https://user-images.githubusercontent.com/36513967/177212706-aba4c174-4116-4356-8945-df3babbf8266.jpg)
There, only two places in the file indicate the path to the certificate. The screenshot shows that I specified these paths and these paths contain the files of the purchased certificate. Only I can not understand what else is needed to make everything work fine.

**Comment by UnamSanctam** [comment]
Did you restart it? Did you enter the chain as well? Can you access the site through https?

**Comment by masterjek** [comment]
Yes, I rebooted the entire server after the changes. Yes, I go to the site according to the protocol https. But there were 171 workers should be about 12000. And I know that in the folder where the database should quickly appear two files and disappear, but this does not happen.

**Comment by UnamSanctam** [comment]
Is the webserver running right now or is it stopped? I can't access it at least.

**Comment by masterjek** [comment]
Sorry for disturbing. I found my mistake. Thanks for the answer.
