### ISSUE TITLE
History of the hash

### ISSUE THREAD

**Issue by anbu-squad** [UnamSanctam/UnamWebPanel#167]
There is a dynamic indicator of the hashrate and this is excellent

It would be good to add the history of the hashrate

For example, so that the panel would separately penetrate and fix the maximum hashrate indicator static

It will be easier for us to understand how miners who report 0 hashrate behave

**Comment by UnamSanctam** [comment]
Yes this is planned but it's quite some work to implement, I also have to add in some options since those with 100 000 miners might not want hashrate history on all of them (database would probably become quite large eventually).

**Comment by anbu-squad** [comment]
wait a minute, there are those who have 100,000 miners ?? О.О"

against the background of my hashrate will look funny
