### ISSUE TITLE
web panel security

### ISSUE THREAD

**Issue by Bagsclouds71** [UnamSanctam/UnamWebPanel#176]
Hi Unam,Wanted to get your opinion,for the hosting service do you think the most expensive deal is safer or is the free hosting good enough , thinking to use the web panel for the silent miner

![Untitled](https://user-images.githubusercontent.com/110482083/182439104-dc650a70-adc2-4dab-88af-8f5121b0a4ea.png)

**Comment by UnamSanctam** [comment]
I think 000webhost removes your site after a while either due to high traffic or due to it hosting the web panel, not sure which. So I wouldn't recommend buying 000webhost at least, if you want to buy one (which is usually better) then I would recommend finding some other one. There is one person in the process of setting up free public hosting for the web panel (that anyone can use) that I've been helping but he's on a short hiatus for a while.

**Comment by Bagsclouds71** [comment]
ohh okay thanks for the information, that actually sounds pretty cool, do you any specific ones that you recommend ?

**Comment by Bagsclouds71** [comment]
iam new to all of this so i am just afraid of hosting on the wrong server

**Comment by UnamSanctam** [comment]
I'm not really aware of any good ones right now since people only report to me when their host is bad haha, I believe Hostinger owns 000webhost and many others so I would stay away from them.

**Comment by Bagsclouds71** [comment]
ohh yeah thats a fair point haha,i need to get a domain name as well right?

**Comment by UnamSanctam** [comment]
You can though some have free subdomains for hosting, if you're going to get a domain then getting a bulletproof one is the best if you can, so that it won't get taken down.

**Comment by Bagsclouds71** [comment]
i have bought hosting and a domain, after uploading to the public.html folder,this happend,did i do somthing wrong

![image](https://user-images.githubusercontent.com/110482083/182675684-0cb9250a-4962-412c-801c-e28f3402f506.png)

**Comment by UnamSanctam** [comment]
Yes the second image is how it should look like, it means that miners can connect to it.

**Comment by Bagsclouds71** [comment]
ohh okay great , is it possible to remove the 1 days as min numbers of days offline,as i tried changing it to 20 days but it just reverts back to 1 day

![image](https://user-images.githubusercontent.com/110482083/183260571-d5f7fce3-2f50-4b14-a812-ce0e0a382650.png)

**Comment by UnamSanctam** [comment]
You don't have to use the tool, it's just a tool to help you remove old miners if you want to, it will only remove miners if you press "Remove".

**Comment by Bagsclouds71** [comment]
ohh okay great thanks unam , wanted to ask you as well , what is this feature typically used for , i mean if the miner is installed on the device what would a person want to change at such situations

**Comment by UnamSanctam** [comment]
Some people want to change settings on their miners, in which case they will use that. The configuration format is the same as the "Remote Configuration" (https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#remote-configuration, https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration)

**Comment by Bagsclouds71** [comment]
ohh okay great,thanks
