### ISSUE TITLE
Can both domain and hosting get banned?

### ISSUE THREAD

**Issue by culatos** [UnamSanctam/UnamWebPanel#177]
If I have 2 seperate accounts, lets say namecheap and hostinger. Namecheap has the domain and hostinger hosts the webpanel.
I am aware that hostinger might remove the hosting due to a lot of traffic or because they see the webpanel. But is it also possible that namecheap bans my domain? Or is the domain always safe? Like if a website gets reported is it just the hosting that gets taken down, or also the domain?
Because if the domain stays alive then I can just buy hosting again somewhere else and still get the miners connected no problem.

**Comment by UnamSanctam** [comment]
Yes your domain can get taken down, if it gets reported (for example to SpamHaus) then usually the registrar will close your domain (which has happened to me before). Which is why people get bulletproof hosting or domains, since they won't get taken down.

**Comment by culatos** [comment]
Thanks. Are there any bulletproof hosting or domain services you can recommend? And I have heard you host the webpanel yourself. How do you do that without being scared of your IP getting leaked?

**Comment by culatos** [comment]
I understand, thanks.
