### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gresmax** [UnamSanctam/UnamWebPanel#18]
![Screenshot_2](https://user-images.githubusercontent.com/64851092/142267169-290582fc-3751-458a-accb-5fef2ae0496f.png)
What can I be doing wrong?

**Comment by UnamSanctam** [comment]
That's correct, since you don't send any miner data when opening it by yourself in the browser. If you enter that URL into the miner then it will work.

**Comment by gresmax** [comment]
ok, Thanks

**Comment by gresmax** [comment]
Should Ponel appear immediately or after a while? I already have a hash on the pool, but there is still an error on the site.

**Comment by UnamSanctam** [comment]
Don't browse to the endpoint to actually enter the website, the endpoint it just for the miner. Go to your website URL to view the panel.

**Comment by gresmax** [comment]
Everything works. Thanks
![Screenshot_5](https://user-images.githubusercontent.com/64851092/142269700-cefc870c-4953-40c6-9973-849e5da9e630.png)
