### ISSUE TITLE
no miners in the web

### ISSUE THREAD

**Issue by pcflux** [UnamSanctam/UnamWebPanel#182]
hello my miners dont show in the web but the api is working what could be the problem?

**Comment by UnamSanctam** [comment]
Make sure that you have PHP 7.4 or above and that the database file is writable.

**Comment by pcflux** [comment]
I have php 7.4 and the db folder has 755 permissions, but unamwebpanel.db is 644

**Comment by UnamSanctam** [comment]
Are you able to go to the "Configurations" tab and create a new configuration (enter `{}` as the data)? After creating it then check if you can see the configuration in the "Edit Configurations", if it's not there then it's not able to write to the DB.

**Comment by pcflux** [comment]
![image](https://user-images.githubusercontent.com/110896305/184667942-3d9af50b-28f6-4e1c-9587-6435adfa768c.png)
yes i can create new configuration

**Comment by UnamSanctam** [comment]
Then DB is writable, where are you hosting the web panel and what are you entering into "API Endpoint URL"?

**Comment by pcflux** [comment]
I'm hosting it on sprinthost.ru, I saw somewhere here that is free and works , in the api endpoint I enter:
http://mysite/api/endpoint.php

**Comment by UnamSanctam** [comment]
And it's not forcing https when you visit the site or anything?

**Comment by pcflux** [comment]
No I don't think so, its http could that be a problem?

**Comment by UnamSanctam** [comment]
No, the only problem would be if your site is forcing https (redirecting from http to https) without having a certificate, visit your site in the browser and check if it's saying http.

**Comment by pcflux** [comment]
Yeah its saying http, even when I login or go the api page its http

**Comment by UnamSanctam** [comment]
Run your miner and then the checker and post what it returns.

**Comment by pcflux** [comment]
![test](https://user-images.githubusercontent.com/110896305/184672725-95f68a9a-2d05-44b3-8f3f-58d853ffc06e.png)

**Comment by pcflux** [comment]
its been mining for 20 minutes and still nothing on web

**Comment by UnamSanctam** [comment]
Does your host have cloudflare or something that could be blocking it? Also check the `__UNAM_LIB\Logs` directory to see if there are any files other than `dummy`.

**Comment by pcflux** [comment]
I don't think it has anything that could be blocking it, in logs folder there is only dummy
off topic question what other web server that I could use that is not 000webhost?

**Comment by UnamSanctam** [comment]
Not sure, I personally host everything myself and people only tell me when they find a bad web host and usually not when they find a good web host.

Only reasons I can really think of why it wouldn't work is either the https redirect or a security block. Try seeing if you can find any Apache `access.log` or anything somewhere in your web host.

**Comment by pcflux** [comment]
it looks like its working now, I think there was some kind of issue with the miner it would start but die after some time.
By the way can I change my api link with pastebin? (api-endpoint": "url")
Because I tried and no miner is connecting but in pool it shows they are online

**Comment by UnamSanctam** [comment]
Yes you can change the link with "Remote Configuration" with `"api-endpoint": "url"`, don't forget to format the JSON correctly as well with commas and such.

**Comment by pcflux** [comment]
I see, thank you very much for helping.
