### ISSUE TITLE
Duplicate Entries

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/UnamWebPanel#186]
I checked the miner on my computer and noticed that two identical entries were created in the web panel.
![1](https://user-images.githubusercontent.com/36513967/187621697-fe79a48d-8dbf-4f52-9a25-8edc3094b379.jpg)
I don't think this is a critical issue. But I wonder what is the reason?

**Comment by UnamSanctam** [comment]
Either they are two miners you have running with different build IDs, or it wasn't able to read the already existing entry in your database so it created a new one on the connection.

**Comment by masterjek** [comment]
Understood. Thanks for the quick response.
