### ISSUE TITLE
Web Panel Idea

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/UnamWebPanel#187]
Good afternoon Unam. I have an idea, but I don't know if it can be implemented. If the worker sent an error to the web panel, it does not connect to the pool. Is it possible to implement that the web panel automatically switches the worker data to another configuration?

**Comment by UnamSanctam** [comment]
Yes it's possible of course, though making a UI and everything for it is quite complex and would be hard to use probably. The miner itself also have backup settings if you have multiple configurations, the builder settings, "Remote Configuration" and the web panel "Configurations" all get added into the miner as 3 pools it can switch between when the current one doesn't work.
