### ISSUE TITLE
XAMPP Question

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/UnamWebPanel#188]
Good afternoon Unam. My web panel works on XAMPP And in the errors I see this message - **"Server ran out of threads to serve requests. Consider raising the ThreadsPerChild setting"** I want to know if this affects the work of the web panel? If it affects the operation of the web panel, how can this be fixed?

**Comment by UnamSanctam** [comment]
Could be that it's working too long, try replacing these files: [database.zip](https://github.com/UnamSanctam/UnamWebPanel/files/9468412/database.zip) (just unzip into the web panel and overwrite the 2 files), it's a database performance update for the next version.

**Comment by masterjek** [comment]
I replaced the files. Restarted the server, deleted the old file with errors. And in the new error file, everything early, an error appears - [Thu Sep 01 12:13:53.283493 2022] [mpm_winnt:error] [pid 5016:tid 3548] AH00326: Server ran out of threads to serve requests. Consider raising the ThreadsPerChild setting

**Comment by UnamSanctam** [comment]
Yes then try raising ThreadsPerChild in the mpm_winnt_module module (should maybe be in the httpd-mpm.conf file, `xampp/apache/conf/extra/httpd-mpm.conf`)

**Comment by masterjek** [comment]
Default value ThreadsPerChild I bet 1500 The error did not appear immediately, but after a while, But the CPU usage on the VPS has become 100% And he refused to work. As far as I understand I need:
1. meaning ThreadsPerChild deliver more than 1500
2. Change vps because it lacks power.
