### ISSUE TITLE
XAMPP Problem With Web Panel

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/UnamWebPanel#191]
Good evening Unam. I had such a problem I run a web panel on my computer by using XAMPP. There are currently 19000 workers in the web panel. And very often my processor is loaded at 100% And the computer freezes in the task manager, the process that loads 100% is Apache. I can not understand the web panel is not enough resources on my computer?

![3](https://user-images.githubusercontent.com/36513967/189399243-9fcd9f56-3897-4924-89a7-97c25ac3883d.jpg)

My computer: 
1. CPU - intel core i7 11700k - 8 cores 16 threads frequency 3.6 GHz
2. RAM - 64 Gb
3. HDD - Samsung evo 980 Pro
4. Video card - Asus RTX 3080
If with such resources the web panel loads the processor by 100%, then what kind of computer is needed for its operation?
In errors when the processor is loaded at 100%, this appears.
![2](https://user-images.githubusercontent.com/36513967/189397964-0e04581a-fa82-457f-a8fc-3da09c22ea69.jpg)

**Comment by UnamSanctam** [comment]
It's most likely because of the database not being able to read/write fast enough, try extracting this: [database.zip](https://github.com/UnamSanctam/UnamWebPanel/files/9537245/database.zip) and replacing the files. It's configured to load more in the memory.

**Comment by masterjek** [comment]
Thank you. Now I'll do everything and check. I'll post later if it helped or not.

**Comment by masterjek** [comment]
Did not help. The error still remains.
![4](https://user-images.githubusercontent.com/36513967/189403901-f9e1ddaf-1de6-4bf5-a975-9177721e79c4.jpg)
After about a couple of minutes of work, an error appears, and immediately the CPU load is 100%
I didn’t have such problems right away, but when the number of workers reached 18,000

**Comment by UnamSanctam** [comment]
And you're sure that you replaced the files? I changed that for someone else and it worked, your problem might be with your read/write to the database. You can try changing the database settings or you can even change the database to a MySQL database.

**Comment by masterjek** [comment]
Yes, I definitely replaced the files, there was also a message that you definitely want to replace the files in the folder. I'll copy and paste again.
I don’t really understand programming, so I don’t know how to transfer the panel to the database MySQL.

**Comment by UnamSanctam** [comment]
>Yes, I definitely replaced the files, there was also a message that you definitely want to replace the files in the folder. I'll copy and paste again.

Alright.

>I don’t really understand programming, so I don’t know how to transfer the panel to the database MySQL.

Yes it's a bit more work than using SQLite (which is why I changed it to use SQLite instead of the user having to set up their own database).

>Or maybe another reason is that I sometimes edit the workers in the database using - DB Browser (SQLite) - Maybe after use DB Browser (SQLite) the database gets corrupted?

It probably shouldn't be but you can try stopping Apache, then "removing" (move the current database somewhere else) the database and placing down a fresh one and then starting Apache again.

**Comment by masterjek** [comment]
Can you recommend a good database editing program to avoid using DB Browser (SQLite)

**Comment by UnamSanctam** [comment]
>Tell me if I go to MySQL Does it work better with more workers? And to go to MySQL Does it need to rewrite the webpanel code?

Might work better because it's not a file, only the connection part of the db.php file would need to be changed for MySQL. But can you try replacing the files with this: [database.zip](https://github.com/UnamSanctam/UnamWebPanel/files/9538248/database.zip) and see if it changes? I tried upping the limit even more.

**Comment by masterjek** [comment]
Thanks I'll check. True, the problem does not appear immediately, but after reaching 18000 workers in the base.

**Comment by masterjek** [comment]
Now the workers have recovered to the new database up to 13000. There is no overload on the processor yet, but the error has already begun to appear.
![2](https://user-images.githubusercontent.com/36513967/189488569-cf917244-f4ca-4ad1-b034-3c6ff4a654a6.jpg)
And with the database, two files do not disappear at all, they are always there. At the beginning, when the database is empty, these files quickly appear and disappear.
![2](https://user-images.githubusercontent.com/36513967/189488642-9607ce3b-6a32-4d65-91cf-9a8d1a6f4215.jpg)

**Comment by masterjek** [comment]
> Might work better because it's not a file, only the connection part of the db.php file would need to be changed for MySQL. But can you try replacing the files with this: [database.zip](https://github.com/UnamSanctam/UnamWebPanel/files/9538248/database.zip) and see if it changes? I tried upping the limit even more.

Here with this last configuration. Miners with an error status do not switch to another configuration. More precisely, the web panel shows that the miner has been switched to another configuration, but it still remains with an error status.
I copied back the old versions files "endpoint" and "db" And with them, miners with an error status immediately switched to other configurations and began to work successfully.

**Comment by UnamSanctam** [comment]
Hmm interesting, I'll take more of a look after I'm done with the next miner update. After the update I can if you want also remote control the server to change the database settings (until they work) or I can set up the MySQL server for you if I can't find any good settings.

**Comment by masterjek** [comment]
Ok, thanks a lot for the answers and the offered help. If you can't find a good solution. I agree to go to the database MySQL. The web panel works on my computer. So when you succeed, I will install the program Teamviewer, to give you remote access to my computer.

What I managed to find out these days:
1. Is in the settings XAMPP "ThreadsPerChild" - The default value is 150. With the default value, I don't get errors that the database doesn't have time to write values. But I am getting a warning that the server has run out of threads to serve. And the site with the web panel is terribly slow and opens for a very long time. And with the default value of 150, my processor is not overloaded at all and the load on it from the server is 10-12%
2. Apache to serve the web panel asks to set the value "ThreadsPerChild" up to 1920 value. With value 1920 A website with a webpanel opens very quickly. But after a short time, there are many errors at once, that the database is locked and does not have time to write the values. And my processor is loaded at 100%. 
3. By mistake datbase locked I searched for solutions on the internet. There are some options but I don't understand in programming and it's very hard for me to understand. But also due to this error, many write that the database Sqlite, It is not capable of processing a large amount of data that is simultaneously written to it. And many advise to go to Mysql.
4. And my last observation. When the number of workers reaches 25-30k even with meaning ThreadsPerChild - 150. errors appear database is locked. And a site with a web panel sometimes opens for about a minute.

**Comment by masterjek** [comment]
Good afternoon Unam. Please tell me, how long does it take to switch the web panel to work with the database MySQL?

**Comment by UnamSanctam** [comment]
Hmm, maybe 30 minutes or something, the main thing needed is to create the database.

**Comment by masterjek** [comment]
Does the web panel code also need to be changed to work with a different database?

**Comment by UnamSanctam** [comment]
Only the db.php files connection string and executed pragmas.

**Comment by masterjek** [comment]
When you have free time, you can help convert the web panel to a database MySQL?

**Comment by UnamSanctam** [comment]
>I figured out how to make it easier. I will buy a server, transfer a web panel there, you can set up a database MySQL. I have only one question, then I will be able to transfer everything from the server to my computer, the database, as I understand it, is not tied to the server, right?

Yes that's possible, everything for the web panel is in the folder itself so you can simply move the folder.

**Comment by masterjek** [comment]
I bought a server, moved the web panel there. I sent you the data for accessing the server by mail.
