### ISSUE TITLE
 white screen

### ISSUE THREAD

**Issue by Demon4u** [UnamSanctam/UnamWebPanel#2]
Just a white screen and nothing happens next
![Screenshot_2](https://user-images.githubusercontent.com/85320553/140839265-5809894a-db98-4540-aca5-5afa4bd5b11b.jpg)

**Comment by UnamSanctam** [comment]
Did you set it up according to the instructions?

**Comment by Demon4u** [comment]
yes. The file was put separate
![Screenshot_1](https://user-images.githubusercontent.com/85320553/140840426-d22b46ba-7417-4750-937b-faf2bd3fc932.jpg)
ly

**Comment by UnamSanctam** [comment]
Can you check in the __UNAM_LIB\Logs folder and see if there is any files there?

**Comment by Demon4u** [comment]
The folder is empty

**Comment by UnamSanctam** [comment]
Can you try with the new version I released?

**Comment by Demon4u** [comment]
Yes, thank you, everything works!

**Comment by UnamSanctam** [comment]
Great!
