### ISSUE TITLE
Removing miners through Web Panel

### ISSUE THREAD

**Issue by hey000hey** [UnamSanctam/UnamWebPanel#204]
If watchdog is enabled for the miner, is it possible to completely uninstall the miner remotely through the web panel? if not, this is a feature request 🙏 🥺

**Comment by UnamSanctam** [comment]
No there's no way to completely uninstall the miner through the web panel, and it probably won't get added due to this (repost):
> For the uninstall button it probably won't ever really be added, the miners themselves don't have any uninstall code (https://github.com/UnamSanctam/SilentCryptoMiner/blob/master/SilentCryptoMiner/Resources/Code/Uninstaller.cs) inside them and it can't really be added without having to either add a ton of new command line settings that tell the miner about all the different settings chosen in the builder or having to make the miner less hidden so that a generic uninstaller can find and uninstall the miner.

To uninstall it you would need to run the uninstaller that gets created together with the miner.

**Comment by hey000hey** [comment]
thanks!

**Comment by hey000hey** [comment]
bro i swear im in the same time zone as you (GMT-7)

**Comment by UnamSanctam** [comment]
Hahaha, no I'm in GMT+01:00, I just stay up at weird times.
