### ISSUE TITLE
What can we expect in the next panel update

### ISSUE THREAD

**Issue by wnetMC** [UnamSanctam/UnamWebPanel#212]
Also when is the next update going to come?

**Comment by UnamSanctam** [comment]
I haven't fully written the changelog yet so everything is in the changelog but this is the current one:

- Greatly improved database performance
- Greatly improved endpoint performance
- Added "Hide Offline Miners" option
- Improved datatable responsive width scaling
- Fixed status priority for offline and error statuses
- Added Russian translation (marat2509)
- Added Ukrainian translation (Zem0rt)

The most important change being the performance changes, not long ago I asked a miner with 170 000 miners who was experiencing performance issues to test it and with all the 170 000 miners connecting his the web server was only taking 10%-20% CPU with the new changes.

These are the unfinished ones I've been trying to work on:
- Add country flags for IPs
- Add hashrate history

The main issues I've run into is firstly a common one with IP lookup databases, nearly all of the ones out there require the server to either use Composer or to install and configure Phar, both of which would make the web panel setup a lot harder. So I've been trying to find some other way to do it. For the hashrate history the biggest issues are that it takes a lot of space in the database and is hard to find somewhere good to display it.

I'll publish it after I've reached some sort of conclusion for the unfinished points and after testing everything.

**Comment by wnetMC** [comment]
This sounds nice, I wish you a good luck.
