### ISSUE TITLE
How to upgrade to v1.7 from v1.6 without loosing any data in db?

### ISSUE THREAD

**Issue by zaromarco** [UnamSanctam/UnamWebPanel#215]
As the statement, how to correctly update?
Thanks

**Comment by UnamSanctam** [comment]
If you want to migrate your data then follow these steps:

1. Download and Open `DB Browser for SQLite`
2. Open the v1.6 database with it
3. Press `File > Export > Database to SQL file...`
4. Change from `"Export everything"` to `"Export data only"`
5. Press `"Save"` and save the .sql file somewhere
6. Open the new v1.7 database
7. Go to the `"Execute SQL"` tab
8. Enter `DELETE FROM configs;`
9. Press the execute SQL button (blue play button)
10. Press `File > Import > Database from SQL file...`
11. Load your exported .sql file
12. Press "No" on the option box that appears
13. Press "Write Changes" and you're done

**Comment by zaromarco** [comment]
thank's it worked.only a small problem: how to choose the column to show in the table? before i had computername , now i need to expand the configuration of each miner id
![immagine](https://user-images.githubusercontent.com/13431840/209708008-bb10d2b6-5459-4c4a-971d-e2e4b533b172.png)

**Comment by UnamSanctam** [comment]
You can edit the columns in this file: https://github.com/UnamSanctam/UnamWebPanel/blob/master/UnamWebPanel/assets/php/datatables.php, if you want to move it then just move the `computername` key-value up or down.

**Comment by zaromarco** [comment]
thank's , i moved up computername and now i get this:
![immagine](https://user-images.githubusercontent.com/13431840/209990753-621609b3-7c8d-4d7b-afab-13506b576cbf.png)

because i have plenty of space on the right , how can i add more column? to show computername i "lost" pool...

**Comment by UnamSanctam** [comment]
It's because you don't have enough room to show it, so it moves it down into the list, because it's responsive.

**Comment by zaromarco** [comment]
understand ...the problem is in the column user which contains a very long name...i moved down till the end and now i get much more column

**Comment by UnamSanctam** [comment]
Alright great.
