### ISSUE TITLE
Problem with web panel

### ISSUE THREAD

**Issue by faqu1** [UnamSanctam/UnamWebPanel#22]
Hi bro, I set up a connection to the web panel in the miner, put the link as in the instructions, made a build and glued it with other software. A knock on another software goes, but there is nothing in the panel, what could this be connected with?
![image](https://user-images.githubusercontent.com/95179319/143774588-4a84cb63-be68-452a-911d-5f308edd62ea.png)
The link in which I put in the builder comes out this - 
![image](https://user-images.githubusercontent.com/95179319/143774658-50db5df6-5199-422b-afdf-21ae4c63ad34.png)

**Comment by UnamSanctam** [comment]
What URL did you enter into the miner? The panel in your screenshots are working correctly. Since you don't have a certificate make sure that you don't enter https.

**Comment by faqu1** [comment]
> What URL did you enter into the miner? The panel in your screenshots are working correctly. Since you don't have a certificate make sure that you don't enter https.

i'm using http

**Comment by UnamSanctam** [comment]
Run the checker and make sure that the miner is running.

**Comment by faqu1** [comment]
![image](https://user-images.githubusercontent.com/95179319/143775295-5731b5d0-d597-4db8-8da6-7f241bd2d86c.png)
![image](https://user-images.githubusercontent.com/95179319/143775305-0e8b4290-a37c-40bb-8811-789317c70033.png)

**Comment by UnamSanctam** [comment]
And if you copy paste that `--cinit-api` URL into the browser it returns the correct "Error: Invalid data" page?

**Comment by faqu1** [comment]
Miner working, but there is nothing in the panel (

**Comment by faqu1** [comment]
> And if you copy paste that `--cinit-api` URL into the browser it returns the correct "Error: Invalid data" page?

Yes

**Comment by faqu1** [comment]
Exactly

**Comment by faqu1** [comment]
Shouldn't this be?

**Comment by UnamSanctam** [comment]
No that's correct, someone else also had problems with using the IP directly, though it works for me. So that could be the "problem".

**Comment by faqu1** [comment]
> No that's correct, someone else also had problems with using the IP directly, though it works for me. So that could be the "problem".

What should I do to make it work?

**Comment by UnamSanctam** [comment]
The problem in that case could be that you use the IP directly (though it should technically work), so you could get some free domain or something and point it to that IP just to test if that works.

**Comment by faqu1** [comment]
ok. Thank you)

**Comment by faqu1** [comment]
This did not solve the problem (((

**Comment by faqu1** [comment]
![image](https://user-images.githubusercontent.com/95179319/143777111-363ecbb5-1639-4fa8-b8b7-70a5638caf87.png)
![image](https://user-images.githubusercontent.com/95179319/143777192-c404f3b7-a629-4fbe-8dab-d04a083d2615.png)

**Comment by UnamSanctam** [comment]
Hmm, not entirely sure why that doesn't work for you. Are there any `error.log` files in any of the folders?

**Comment by faqu1** [comment]
Do you need to watch it on the server?

**Comment by UnamSanctam** [comment]
Yes, in any directory there might be an error.log file is something went wrong, such as the PHP version being too old or maybe it being unable to connect to the database. Though I don't think the site would have worked if either of those were the case.

**Comment by faqu1** [comment]
I did not find such a file (Maybe I will give you data from the server, will you check? If it does not bother you

**Comment by UnamSanctam** [comment]
Sure but it shouldn't really matter, I can't really easily understand the reason why it doesn't connect, the two scenarios could be: 1) Miner cannot connect to your website for whatever reason, 2) Your host somehow blocks the connection, though it shouldn't really since you can access it from your browser.

**Comment by warnerblue** [comment]
I'm having the same issue, debugging rn ill update when I find the error.

**Comment by warnerblue** [comment]
> Sure but it shouldn't really matter, I can't really easily understand the reason why it doesn't connect, the two scenarios could be: 1) Miner cannot connect to your website for whatever reason, 2) Your host somehow blocks the connection, though it shouldn't really since you can access it from your browser.

Looks like its a problem with sqlite and either file perms or versions: SQLSTATE[HY000]: General error: 8 attempt to write a readonly database

**Comment by warnerblue** [comment]
`$ chown :daemon /path/to/your/sqlite/file
$ chmod 664 /path/to/your/sqlite/file
$ chown :daemon /path/to/your/project
$ chmod 775  /path/to/your/project`

This should fix your panel.

**Comment by UnamSanctam** [comment]
Yeah insufficient permissions could definitely be the problem if it's hosted on a Linux platform.

**Comment by anbu-squad** [comment]
ss -a  
TIME_WAIT 

bots are knocking on the server, but not on the panel

did I understand correctly?
775 per site folder?
664 on unamwebpamel.db?

gave the right that something does not knock

**Comment by faqu1** [comment]
Are there hosts that are not banned for this panel?

**Comment by warnerblue** [comment]
> ss -a TIME_WAIT
> 
> bots are knocking on the server, but not on the panel
> 
> did I understand correctly? 775 per site folder? 664 on unamwebpamel.db?
> 
> gave the right that something does not knock

Yes thats correct. You can also make a folder called Logs inside of __Unam_Lib to get php logs.

**Comment by Sh4r3cat** [comment]
hey i used Hostiger because Crazyrdp blocking some connections because of the bad DDOS Protection now i cant acces my panel and then i log in to Hostiger i get "Unable to continue - your account has been closed" how i can change now my panel or how can i bypass that they ban my acc

**Comment by UnamSanctam** [comment]
Seems like they "ban" accounts when there is too much traffic when you have a free account, which is why bulletproof hosts and/or domains are recommended since they won't be taken down.

**Comment by ducksucker** [comment]
yeah i have the same problem 
![image](https://user-images.githubusercontent.com/73056239/145579967-c4b074a7-e47d-405b-a990-ed62b0824e49.png)
can anyone help me fix it before i start mining?

**Comment by UnamSanctam** [comment]
That message means that it works.

**Comment by ducksucker** [comment]
ohhh so i can use the link

**Comment by stefexec** [comment]
Sadly, same for me. After i figured out the other issue i had the shares started appearing on the pool, but even though i put in http without encryption and get the  "Invalid Data" when i visit the URL from the checker, the miners dont show up on the panel. I'm on a free host atm

**Comment by UnamSanctam** [comment]
And you're sure the link is correct? Everyone has been able to fix it so far by either double-checking the URL they entered into the builder, or by changing the permissions of the files. For some their host has been blocking connections as well (nothing you or the miner can really do about that).

**Comment by stefexec** [comment]
> And you're sure the link is correct? Everyone has been able to fix it so far by either double-checking the URL they entered into the builder, or by changing the permissions of the files. For some their host has been blocking connections as well (nothing you or the miner can really do about that).

I might need to change host then. I tried http as well as https. I can visit the URL i get from --cinit-api and get the Invalid Data response on both.

**Comment by nomad1420** [comment]
> > And you're sure the link is correct? Everyone has been able to fix it so far by either double-checking the URL they entered into the builder, or by changing the permissions of the files. For some their host has been blocking connections as well (nothing you or the miner can really do about that).
> 
> I might need to change host then. I tried http as well as https. I can visit the URL i get from --cinit-api and get the Invalid Data response on both.
> 
> EDIT:
> 
> I tried 2 more obscure Webhosts and none worked, finally i went through the hassle and made an account with 000webhost where everything finally works as intended.

hi bro how you solve the problem ? i am getting the same error

**Comment by zhimiyouwu33** [comment]
When you can't see the miner online, you must not be able to create a remote configuration file. For problems like this, please try
chmod -R 777 webpath/
After that, happy mining
