### ISSUE TITLE
How to disable hash rate history

### ISSUE THREAD

**Issue by zaromarco** [UnamSanctam/UnamWebPanel#220]
As statement, how to do it? Because on my free hosting I have no more disk space

**Comment by UnamSanctam** [comment]
In config.php, set the `hashrate_history_enable` to `false`.

**Comment by zaromarco** [comment]
ok done , in the db folder i have these files:
![immagine](https://user-images.githubusercontent.com/13431840/210221644-04330ba9-4372-4b18-ba43-a36cb5592600.png)
can i delete the .wal and .db-shm ?

**Comment by UnamSanctam** [comment]
Easiest way to clean it up is:

1. Open `index.php`
2. Add `getConn()->exec('PRAGMA wal_checkpoint(TRUNCATE);PRAGMA OPTIMIZE;');` to line 5
3. Visit the web panel once
4. Remove the line again

The wal file should be cleaned up then.

**Comment by zaromarco** [comment]
thank's , i added getConn on line 5 which was empty but i get this error when i try to login: 
![immagine](https://user-images.githubusercontent.com/13431840/210222528-3e671b15-a05f-4943-b9e4-e526d0b75b1b.png)

and this problem comes out also before adding the line...maybe because disk space is completely full ?

**Comment by UnamSanctam** [comment]
No that shouldn't matter, can you take a screenshot of where you added the line?

**Comment by zaromarco** [comment]
![immagine](https://user-images.githubusercontent.com/13431840/210231603-8e39ef6f-95e4-4625-884f-969260a646e2.png)

**Comment by UnamSanctam** [comment]
Alright that should be fine, the error you got is usually from some 500 error, can you take a screeenshot of the config.php that you edited?

**Comment by zaromarco** [comment]
<?php
/* Made by Unam Sanctam https://github.com/UnamSanctam */
$config = [];

/* Change UnamSancam below to change the password. */
$config['password'] = 'xxxxxxx';

/*
 * If your web server uses Apache or IIS then there is no need to
 * change the db file location since the .htaccess or web.config file
 * will protect the database file from being accessed.
 * 
 * You can test if you are vulnerable by visiting the URL
 * WEBSITEURL/unamwebpanel.db (replace WEBSITEURL with your URL),
 * if it returns a 403 Forbidden error then you are protected.
 */
$config['db_file'] = dirname(__FILE__)."/db/unamwebpanel.db";

/*
 * Change to false to disable hashrate history. This option will make the
 * endpoint save the hashrate of each miner connection. This history can be
 * seen on each individual miner or in the miner tab which shows the total
 * hashrate for each algorithm.
 *
 * Warning: if you have a large amount of miners then having this enabled can take
 * a lot of space and/or performance, since the database needs to save and keep track
 * of all the data.
 */
$config['hashrate_history_enable'] = false;
/*
 * The maximum amount of records to keep for each miner, default is 1440 (1 day).
 * A record is saved every time a miner connects, which is once every minute.
 * The web panel will delete any older records when the limit is reached. If set to 0 then
 * it will keep an unlimited amount of hashrate history.
 */
$config['hashrate_history_limit'] = 1440;

$config['failedlogin_blocktime'] = 15;
$config['failedlogin_blocktries'] = 5;

$config['languages'] = [
    'en'=>'English',
    'sv'=>'Swedish',
    'fr'=>'French',
    'de'=>'German',
    'pl'=>'Polish',
    'ru'=>'Russian',
    'uk'=>'Ukrainian'
];

$config['unam_version'] = "1.7.0";

global $config;

**Comment by zaromarco** [comment]
![immagine](https://user-images.githubusercontent.com/13431840/210232151-48ca2789-c83a-4880-be9c-92e41f7a0e2c.png)

**Comment by UnamSanctam** [comment]
That looks correct, do you have any error.log files anywhere? Or any log files inside the `__UNAM_LIB\Logs` folder? Your webserver might not be writing any though. Otherwise you could theoretically delete the .wal file, though it could corrupt your database.

**Comment by zaromarco** [comment]
no logs anywhere...
tried to delete .wal same problem , tried to move away al files related to db and restore backup of a db from v1.7 same error
please let me know.

**Comment by zaromarco** [comment]
tried to download the db that has the wal and i can open with db browser sqlite , for me is not corrupted

**Comment by zaromarco** [comment]
ah , i found log:
[02-Jan-2023 15:25:13 UTC] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on boolean in /storage/ssd4/890/18223890/public_html/__UNAM_LIB/unam_lib.php:29
Stack trace:
#0 /storage/ssd4/890/18223890/public_html/auth-ajax.php(11): unam_lib->unam_dbSelect(false, 'IPBlock', 'ipb_ip, ipb_log...', Array)
#1 {main}
  thrown in /storage/ssd4/890/18223890/public_html/__UNAM_LIB/unam_lib.php on line 29
[02-Jan-2023 15:27:53 UTC] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on boolean in /storage/ssd4/890/18223890/public_html/__UNAM_LIB/unam_lib.php:29
Stack trace:
#0 /storage/ssd4/890/18223890/public_html/auth-ajax.php(11): unam_lib->unam_dbSelect(false, 'IPBlock', 'ipb_ip, ipb_log...', Array)
#1 {main}
  thrown in /storage/ssd4/890/18223890/public_html/__UNAM_LIB/unam_lib.php on line 29

**Comment by UnamSanctam** [comment]
Aha then yes then it's because it cannot access the database.

**Comment by UnamSanctam** [comment]
Try adding `getConn()->exec('PRAGMA wal_checkpoint(TRUNCATE);PRAGMA OPTIMIZE;');` to line 6 in `auth-ajax.php`.

**Comment by zaromarco** [comment]
and i found also this file: db-error-01-02-2023.html

RROR: SQLSTATE[HY000]: General error: 11 database disk image is malformed<br />ERROR: SQLSTATE[HY000]: General error: 11 database disk image is malformed<br />

**Comment by UnamSanctam** [comment]
Yes, it's because your database is corrupt, which is what the previous message is saying.

**Comment by zaromarco** [comment]
but now in the db directory i placed the db backed just after the upgrade to v.1.7

**Comment by zaromarco** [comment]
i don't know why it is creating again the wal file and the db-shm....they are very small

**Comment by UnamSanctam** [comment]
Because that's the database journals, they should be there.

**Comment by zaromarco** [comment]
i delete the db , i download again the v1.7 , extracted only the db and redo the import of data explained in a previous issue but again i have the same problem...i don't understand

**Comment by zaromarco** [comment]
ok found that the web interface of the hosting corrupt the db , upploaded a db from a backup just after v1.7 upgrade via ftp it works but now i get this warning:
![immagine](https://user-images.githubusercontent.com/13431840/210255473-334b2ba7-8dfa-4c35-b66a-b618fa6dd941.png)
this error comes out if i select 50 or all to show entries

**Comment by UnamSanctam** [comment]
Maybe there is some bad value you have somewhere, does it happen if you browse the pages as well (to where that 50/all entry would be)?

**Comment by zaromarco** [comment]
seems it was a problem of the browser cache , deleted everythings back to normal
many thank's
