### ISSUE TITLE
Error in the new version

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/UnamWebPanel#224]
Good evening Unam. Just installed version 1.7.1 In folder Logs file with the following error
ENDPOINT ERROR: SQLSTATE[HY000]: General error: 5 database is locked, LINE: 72
ENDPOINT ERROR: SQLSTATE[HY000]: General error: 5 database is locked, LINE: 72

**Comment by UnamSanctam** [comment]
Hmm I don't get any of them, how many do you get?

**Comment by UnamSanctam** [comment]
And you can also disable hashrate history if you don't need it, since it will speed it up by a ton (since it does not have to save all the history),

**Comment by masterjek** [comment]
Since the launch of the web panel, only two that I have already thrown off do not appear anymore. The web panel works for about 10 minutes. I immediately turned off the hashrate history before launching.

**Comment by UnamSanctam** [comment]
Alright then it shouldn't be a problem, it can happen if your database is temporarily doing something that requires locking for some longer time.

**Comment by masterjek** [comment]
Understood. Thank you. I'll ask here, and the statistics panel should be updated with a delay? At me after 10 minutes of operation looks as follows.
![2](https://user-images.githubusercontent.com/36513967/211096101-3c717a1a-78a3-44b5-90b8-335a1399d201.jpg)

**Comment by UnamSanctam** [comment]
It updates immediately, but maybe it's checking the creation date and not the connection date? Try replacing the statisticsAjax.php file with this one: [statisticsAjax.zip](https://github.com/UnamSanctam/UnamWebPanel/files/10362978/statisticsAjax.zip)

**Comment by masterjek** [comment]
Thank you. This worked for me, now the stats are updated right away.

**Comment by UnamSanctam** [comment]
Alright great!
