### ISSUE TITLE
Webpanel cant login but it seems to be some prermision denied issue

### ISSUE THREAD

**Issue by IfinderCodes** [UnamSanctam/UnamWebPanel#227]
I have a server running debian with apache2 and php 7.4

 php error log: 

` Permission denied in /var/www/html/__UNAM_LIB/unam_lib.php on line 235, referer: http://MYSERVERIP/login.php
[Thu Jan 12 20:44:36.455400 2023] [php7:error] [pid 1847326] [client myip:61892] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on bool in /var/www/html/__UNAM_LIB/unam_lib.php:29\nStack trace:\n#0 /var/www/html/auth-ajax.php(11): unam_lib->unam_dbSelect()\n#1 {main}\n  thrown in /var/www/html/__UNAM_LIB/unam_lib.php on line 29, referer: http://MYSERVERIP/login.php
[Thu Jan 12 20:45:23.815402 2023] [php7:warn] [pid 1847337] [client myip:61950] PHP Warning:  file_put_contents(/var/www/html/__UNAM_LIB/Logs/php-error-01-12-2023.html): failed to open stream: Permission denied in /var/www/html/__UNAM_LIB/unam_lib.php on line 235, referer: http://MYSERVERIP/login.php
[Thu Jan 12 20:45:23.815497 2023] [php7:error] [pid 1847337] [client myip:61950] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on bool in /var/www/html/__UNAM_LIB/unam_lib.php:29\nStack trace:\n#0 /var/www/html/auth-ajax.php(11): unam_lib->unam_dbSelect()\n#1 {main}\n  thrown in /var/www/html/__UNAM_LIB/unam_lib.php on line 29, referer: http://MYSERVERIP/login.php
[Thu Jan 12 20:45:29.137463 2023] [php7:warn] [pid 1847336] [client myip:61951] PHP Warning:  file_put_contents(/var/www/html/__UNAM_LIB/Logs/php-error-01-12-2023.html): failed to open stream: Permission denied in /var/www/html/__UNAM_LIB/unam_lib.php on line 235, referer: http://MYSERVERIP/login.php
[Thu Jan 12 20:45:29.137508 2023] [php7:error] [pid 1847336] [client myip:61951] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on bool in /var/www/html/__UNAM_LIB/unam_lib.php:29\nStack trace:\n#0 /var/www/html/auth-ajax.php(11): unam_lib->unam_dbSelect()\n#1 {main}\n  thrown in /var/www/html/__UNAM_LIB/unam_lib.php on line 29, referer: http://MYSERVERIP/login.php
[Thu Jan 12 20:46:25.284100 2023] [php7:warn] [pid 1847280] [client myip:62016] PHP Warning:  file_put_contents(/var/www/html/__UNAM_LIB/Logs/php-error-01-12-2023.html): failed to open stream: Permission denied in /var/www/html/__UNAM_LIB/unam_lib.php on line 235, referer: http://MYSERVERIP/login.php
[Thu Jan 12 20:46:25.284198 2023] [php7:error] [pid 1847280] [client myip:62016] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on bool in /var/www/html/__UNAM_LIB/unam_lib.php:29\nStack trace:\n#0 /var/www/html/auth-ajax.php(11): unam_lib->unam_dbSelect()\n#1 {main}\n  thrown in /var/www/html/__UNAM_LIB/unam_lib.php on line 29, referer: http://MYSERVERIP/login.php
[Thu Jan 12 20:46:44.275976 2023] [php7:warn] [pid 1847282] [client myip:62051] PHP Warning:  file_put_contents(/var/www/html/__UNAM_LIB/Logs/php-error-01-12-2023.html): failed to open stream: Permission denied in /var/www/html/__UNAM_LIB/unam_lib.php on line 235, referer: http://MYSERVERIP/login.php
[Thu Jan 12 20:46:44.276043 2023] [php7:error] [pid 1847282] [client myip:62051] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on bool in /var/www/html/__UNAM_LIB/unam_lib.php:29\nStack trace:\n#0 /var/www/html/auth-ajax.php(11): unam_lib->unam_dbSelect()\n#1 {main}\n  thrown in /var/www/html/__UNAM_LIB/unam_lib.php on line 29, referer: http://MYSERVERIP/login.php
[Thu Jan 12 20:46:45.985352 2023] [php7:warn] [pid 1847316] [client myip:62057] PHP Warning:  file_put_contents(/var/www/html/__UNAM_LIB/Logs/php-error-01-12-2023.html): failed to open stream: Permission denied in /var/www/html/__UNAM_LIB/unam_lib.php on line 235, referer: http://MYSERVERIP/login.php
[Thu Jan 12 20:46:45.985405 2023] [php7:error] [pid 1847316] [client 178.164.119.42:62057] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on bool in /var/www/html/__UNAM_LIB/unam_lib.php:29\nStack trace:\n#0 /var/www/html/auth-ajax.php(11): unam_lib->unam_dbSelect()\n#1 {main}\n  thrown in /var/www/html/__UNAM_LIB/unam_lib.php on line 29, referer: http://MYSERVERIP/login.php
[Thu Jan 12 20:48:38.030508 2023] [php7:warn] [pid 1847279] [client myip:62189] PHP Warning:  file_put_contents(/var/www/html/__UNAM_LIB/Logs/php-error-01-12-2023.html): failed to open stream: Permission denied in /var/www/html/__UNAM_LIB/unam_lib.php on line 235, referer: http://MYSERVERIP/login.php
[Thu Jan 12 20:48:38.030642 2023] [php7:error] [pid 1847279] [client myip:62189] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on bool in /var/www/html/__UNAM_LIB/unam_lib.php:29\nStack trace:\n#0 /var/www/html/auth-ajax.php(11): unam_lib->unam_dbSelect()\n#1 {main}\n  thrown in /var/www/html/__UNAM_LIB/unam_lib.php on line 29, referer: http://MYSERVERIP/login.php`

**Comment by UnamSanctam** [comment]
You need to give your webserver user access to the files. And give it write access to the `unamwebpanel.db` file (and its parent `db` folder) as well.

**Comment by IfinderCodes** [comment]
Can you give me commands for that? Ive gotten rusty at linux

**Comment by IfinderCodes** [comment]
nevermind i fixed it

**Comment by rethu-git** [comment]
i need the command though.
