### ISSUE TITLE
how can i create a web panel 

### ISSUE THREAD

**Issue by Azzerzz** [UnamSanctam/UnamWebPanel#23]
i tried using many different webhosts but i dont know what do do in them
i was going to use apache but the whole downloads directory is a mess and i dont know what i should download

**Comment by UnamSanctam** [comment]
Download the release https://github.com/UnamSanctam/UnamWebPanel/releases and extract the UnamWebPanel folder into the `public_html` (or the respective folder for that host).

**Comment by Azzerzz** [comment]
> Download the release https://github.com/UnamSanctam/UnamWebPanel/releases and extract the UnamWebPanel folder into the `public_html` (or the respective folder for that host).

thats the thing, i dont know where to find the html folder
im using wix right now ive tried others but had no idea

**Comment by UnamSanctam** [comment]
I don't think WIX is a webhost per say, I think they're a web designing tool. You should get a real webhost and then you can find the public_html folder by using their file manager if they have one or by accessing it with FTP if they have that.

**Comment by Azzerzz** [comment]
> I don't think WIX is a webhost per say, I think they're a web designing tool with a build in webhost. You should get a real webhost and then you can find the public_html folder by using their file manager if they have one or by accessing it with FTP if they have that.

do you know any that are able to do that? the few i saw that i can required me to pay to unlock that feature

**Comment by anbu-squad** [comment]
aws + xampp

**Comment by JayCrax** [comment]
@UnamSanctam Stop helping this scumbag.
