### ISSUE TITLE
Invalid JSON

### ISSUE THREAD

**Issue by Xeneht** [UnamSanctam/UnamWebPanel#232]
I'm trying to save a config on the web panel but i recieve invalid json message. I think the error is because config is too large, deleting some kill targets processes config works, so I think it's limiting it by chars.
My config has almost 1k kill targets now, is there any way to put the config in the website files or when the request is made miner will ignore it because is invalid?
From the pastebin the miner will take the json as invalid too?
And this drugged list will lag the miner or something?
![0x1544da6f421837b19d567a3072284c1d09f93ace](https://user-images.githubusercontent.com/99096857/212469152-0b1aba91-593a-4132-96d5-6d75cf5886f2.png)

**Comment by UnamSanctam** [comment]
No there's no limit to it, most likely I would guess one of the "Stealth Targets" you deleted was invalid in some way. Try pasting it into a JSON validator online and see what it says. I don't think that amount will lag anything in the miner, I've tried to optimize it as much as possible.

**Comment by UnamSanctam** [comment]
Oh, right, it's to stop PoD attacks. You can increase the limit from 10000 characters here:
https://github.com/UnamSanctam/UnamWebPanel/blob/b8b30b7b0412fa2f817fb80df9b561291eddb186/UnamWebPanel/assets/php/session-header.php#L39
