### ISSUE TITLE
Getting "Error: Something went wrong." In login page

### ISSUE THREAD

**Issue by queider** [UnamSanctam/UnamWebPanel#235]
I tried setting the panel on a vps. 
First I installed xampp and putted the content of the UnamWebPanel in the htdocs then fired it up. Anything I'm doign wrong? Thank you.

**Comment by UnamSanctam** [comment]
Can you find any error.log files anywhere? Or any log files inside the `__UNAM_LIB\Logs\` folder?

**Comment by queider** [comment]
didn't find any log files. Maybe some PHP libs are missing?

**Comment by UnamSanctam** [comment]
Shouldn't be, it should work right away with XAMPP without any changes. You didn't accidentally change something you shouldn't in the `config.php` file or anything?

**Comment by queider** [comment]
Yes just used the XAMPP as is. Didn't even changed the password or anything.  I'm using an ubuntu vps server. When I tried to local test it on my windows machine with XAMPP it worked perfectly.

**Comment by UnamSanctam** [comment]
Oh, you're using XAMPP on Linux? I've never tested XAMPP on Linux since setting up Apache and PHP manually is easier than XAMPP (in my opinion), but I would strongly guess it's some form of permission issue for the files.

**Comment by queider** [comment]
Do I jast install apache and php? Do I need anything else?

**Comment by UnamSanctam** [comment]
Yes it's very easy, you could follow https://www.digitalocean.com/community/tutorials/how-to-install-the-apache-web-server-on-ubuntu-22-04. Step 5 of that guide isn't required though doing that could be good.

**Comment by queider** [comment]
Thank you just fixed it. I installed xampp and chmod 777 htdocs/* and it worked. But for some reason when i tested a miner configuration it didn't appear on the panel...

**Comment by UnamSanctam** [comment]
Alright, you could probably also set it to 755 as long as the files are owned by the correct user. Make sure that you're using the correct http or https depending on if you have a certificate or not.

**Comment by queider** [comment]
Failed to open stream: Permission denied in /opt/lampp/htdocs/__UNAM_LIB/unam_lib.php on line 235
I found this in the error.log in the api folder. Maybe that's the reason the api didn't work? What should I do?

**Comment by UnamSanctam** [comment]
Make sure that both the `db` folder and the `unamwebpanel.db` file inside it has the permissions as well. And make sure that your Apache user (www-data usually from what I remember) owns all the folders.

**Comment by queider** [comment]
I gave permissions and it worked! Thanks man your awesome
