### ISSUE TITLE
How soon will the update be? 

### ISSUE THREAD

**Issue by Toxenskiy** [UnamSanctam/UnamWebPanel#24]
I'm just wondering how much you've fixed, that is, there are a lot of bugs in the panel.

**Comment by UnamSanctam** [comment]
Not long, though there's only really the sorting bug in the panel (and a possible bug if the miner reports NULL hashrate).

**Comment by Toxenskiy** [comment]
I think it's worth adding the total hash rate of the algorithm, moving the buttons to navigate the pages upstairs and fixing a couple of visual flaws, for example: 
![image](https://user-images.githubusercontent.com/55586522/144740981-ec7d030b-49aa-4a0c-852d-c1929ef9a7d3.png)

**Comment by Toxenskiy** [comment]
about the move buttons I have, then that they are either higher or lower, depending on the text of the page.

**Comment by Toxenskiy** [comment]
also the search only works on the id of the miner

**Comment by Toxenskiy** [comment]
also it would be possible to make the parameter "show offline miners"

**Comment by anbu-squad** [comment]
+ new miners in the last 24 hours

**Comment by Toxenskiy** [comment]
i dreamed that you released update 1.5 )

**Comment by UnamSanctam** [comment]
I've released the update now, I've had a lot of real life work to do which unfortunately delayed it by a lot.
