### ISSUE TITLE
Bugs in Apache

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/UnamWebPanel#244]
Good afternoon Unam. There were errors in the Apache logs that I had never seen before.
1. [Mon Mar 06 17:38:26.183417 2023] [ssl:error] [pid 26600:tid 14708] [client 34.239.137.81:36224] AH02042: rejecting client initiated renegotiation
2. [Tue Mar 07 12:05:25.253217 2023] [authz_core:error] [pid 26600:tid 15296] [client 106.75.126.212:52554] AH01630: client denied by server configuration: C:/xampp/phpMyAdmin/index.php
3. [Tue Mar 07 12:05:27.217648 2023] [php:error] [pid 26600:tid 15088] [client 106.75.126.212:52758] script 'C:/xampp/htdocs/index_sso.php' not found or unable to stat
Please let me know if these errors are critical. Or can I ignore them?

**Comment by UnamSanctam** [comment]
Doesn't look like those might not have anything to do with the web panel so you should be able to ignore them.
