### ISSUE TITLE
Error. Something went wrong.

### ISSUE THREAD

**Issue by WestHeatGT** [UnamSanctam/UnamWebPanel#245]
I am using 000webhost. I have php version 8. I have the latest version of unamwebpanel.

**Comment by UnamSanctam** [comment]
Make sure that all files were uploaded.

**Comment by WestHeatGT** [comment]
> Make sure that all files were uploaded.

I uploded the zip file and unzipped it with unzipper.php or whatever it is called

**Comment by UnamSanctam** [comment]
Then it should work out of the gate, did you change the config.php? Make sure that everything is correct there if you did.

**Comment by WestHeatGT** [comment]
> Then it should work out of the gate, did you change the config.php? Make sure that everything is correct there if you did.

The only thing I changed at first was the password, but then I tried without changing it and it still didn't work

**Comment by UnamSanctam** [comment]
I just tried it on 000webhost (free) and it worked for me, I only changed the PHP to 8 and uploaded all the files (unzipped them using unzipper.php). Maybe you need to change the permissions on the files (such as the database file) on your account? I didn't but I don't know everything that you did.

**Comment by WestHeatGT** [comment]
> I just tried it on 000webhost (free account) and it worked for me, I only changed the PHP to 8 and uploaded all the files (unzipped them using unzipper.php). Maybe you need to change the permissions on the files (such as the database file) on your account? I didn't but I don't know everything that you did.

I created a new 000webhost account and it worked. Weird, but at least it works now.

**Comment by UnamSanctam** [comment]
Alright great, weird though.
