### ISSUE TITLE
statistics page not work 

### ISSUE THREAD

**Issue by seition322** [UnamSanctam/UnamWebPanel#247]
![Ekran görüntüsü 2023-03-13 043157](https://user-images.githubusercontent.com/126213895/224588498-b1f0495a-6a18-46c7-9672-28f8c951ff9c.png)

**Comment by UnamSanctam** [comment]
What about it doesn't work?

**Comment by gizlbizl** [comment]
show all in offline

**Comment by UnamSanctam** [comment]
What status are they all then actually? I tested it just now and it shows the correct one for me at least. Did you download the files from here https://github.com/UnamSanctam/UnamWebPanel/releases or from the GitHub code directly?

**Comment by gizlbizl** [comment]
actually status online, see that on miner tab. Download from https://github.com/UnamSanctam/UnamWebPanel/releases, then copy on vps

**Comment by gizlbizl** [comment]
reupload helped oO

**Comment by seition322** [comment]
> yeniden yükleme yardımcı oldu oO

thanks @UnamSanctam ı love u
yes reinstalling worked for me too
