### ISSUE TITLE
Part of the statistics is not working

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/UnamWebPanel#249]
Good afternoon Unam. As version 1.7.1 came out, I immediately updated the web panel. Enough time has already passed, but some of the statistics still do not work. I will attach a screenshot, it shows two columns do not work at all - Error And Idle.
Idle - I do not use, But there are enough miners with errors, but they are not displayed.
![1](https://user-images.githubusercontent.com/36513967/227507714-838257f1-48f8-4e87-8239-78939ca94852.jpg)

**Comment by UnamSanctam** [comment]
Well yeah if you don't use Idle then it won't show, but the Error one should work. Could you post a screenshot of a miner having the "Error" status?

**Comment by masterjek** [comment]
![1](https://user-images.githubusercontent.com/36513967/227509371-ad8a7137-97ad-4602-aa50-d0b033844193.jpg)
