### ISSUE TITLE
I think my web panel is not working

### ISSUE THREAD

**Issue by DogusCzk** [UnamSanctam/UnamWebPanel#252]
I sent my miner to someone on the rat, but for some reason it did not appear on the web panel, I am sending you my settings, can you please check
[miningsettings.zip](https://github.com/UnamSanctam/UnamWebPanel/files/11158206/miningsettings.zip)

**Comment by UnamSanctam** [comment]
Are you able to connect any miners to it? Make sure that your PHP is set to at least PHP 8 and that the database is writable. Are you able to create new configurations in the "Configuration" tab without problems?

**Comment by DogusCzk** [comment]
After a while, my miner appeared in the pool I used, but my web panel did not appear, also most of my previous miners are still visible here

**Comment by DogusCzk** [comment]
Endpoint is up and running. This page is shown since no data was posted during the request or the data posted was invalid.

**Comment by DogusCzk** [comment]
Is there anything wrong here?

**Comment by UnamSanctam** [comment]
If you start the miner on your computer does it appear in the web panel?

**Comment by DogusCzk** [comment]
It was working when I tried before, now I build and try again

**Comment by DogusCzk** [comment]
yes it works for me

**Comment by DogusCzk** [comment]
but why is it not working on the person i threw, also the person i threw, etc miner didn't work

**Comment by DogusCzk** [comment]
![image](https://user-images.githubusercontent.com/123574822/230071347-67287f0b-7de1-4487-9d9c-fc7b7e909180.png)

**Comment by DogusCzk** [comment]
Not enough for 3050 etc?

**Comment by DogusCzk** [comment]
My miner is working in that person, I can see that it is working in the pool I am using, but for some reason it did not come to my panel.

**Comment by DogusCzk** [comment]
I asked you this problem before as my miner is not working, but I think the problem is on the panel, I think the people who run my miner do not come to my panel for some reason.

**Comment by DogusCzk** [comment]
also do you have any idea why my etc miner didn't work on him

**Comment by DogusCzk** [comment]
After I threw my miner i threw my checker too and only saw my monero miner working

**Comment by DogusCzk** [comment]
![image](https://user-images.githubusercontent.com/123574822/230073783-6ade2f20-718e-4889-96fb-a6c58fc99186.png)

**Comment by UnamSanctam** [comment]
The ETC miner is further up in the list, you can see the end of the string there in the screenshot "--cinit-idle-gpu=70". Most likely since it's an RTX 3050 Ti Laptop it only has 4GB of VRAM.
