### ISSUE TITLE
ENDPOINT ERROR: SQLSTATE[HY000]: General error: 8 attempt to write a readonly database, LINE: 66

### ISSUE THREAD

**Issue by slezercc** [UnamSanctam/UnamWebPanel#254]
I already did chmod 775 to the whole site folder and I even tried doing chmod 777 on the db folder and unamwebpanel.db but I keep getting this error. I also did chown www-data for the whole site folder.

**Comment by UnamSanctam** [comment]
What distro are you using? Double check the permissions on both the db folder and db file and then make sure that `www-data` is the one actually running the PHP script.
