### ISSUE TITLE
WebPanel gets no stats

### ISSUE THREAD

**Issue by Michiel12378** [UnamSanctam/UnamWebPanel#28]
Like the title says, the web panel get no stats.
I am trying this at home with some computers, i used a extern hosting but i dont receive any stats of the miners. I can see that the computers are mining on the mining pool.

For some reason the webpanel get no miner stats.

**Comment by UnamSanctam** [comment]
I will repost a previous comment
>And you're sure the link is correct? Everyone has been able to fix it so far by either double-checking the URL they entered into the builder, or by changing the permissions of the files. For some their host has been blocking connections as well (nothing you or the miner can really do about that).

**Comment by Michiel12378** [comment]
I will check it to be sure, Thanks for the fast answer

**Comment by Michiel12378** [comment]
I have checked the url and its correct, Tried to paste the url from the endpoint.php in my browser but got an error. (check image)

![Naamloos](https://user-images.githubusercontent.com/20444311/146216209-79418325-8a98-4843-8518-798586c250d1.png)

**Comment by UnamSanctam** [comment]
Yes that's correct, that message means that it's working, are you making sure to use http since you don't have a certificate?
