### ISSUE TITLE
Web Panel And VPS Server

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/UnamWebPanel#281]
Hello Unam. The web panel runs on the VPS server using XMAPP. Processor on the server

![1](https://github.com/UnamSanctam/UnamWebPanel/assets/36513967/03d4e0cc-9002-4416-a38b-f8d2b42458ea)

after some time the web panel has been working I get an error - NetStat TCP service stopped. Please restart the control panel. CPU load reaches 100%. I get an error in the web panel logs - db is locked. Then comes the following error - Apache Stopped. The web panel stops opening. This does not happen immediately, but when the number of workers becomes large. The VPS technical support told me that Apache is not capable of processing a very large number of TCP connection.

**Comment by masterjek** [comment]
File unamwebpanel.db-wal - reaches gigabyte sizes

**Comment by UnamSanctam** [comment]
>Apache is not capable of processing a very large number of TCP connection

Are you able to increase the Apache worker count? Either the CPU reaches 100% because it cannot handle all the connections or because there are just too many connections. But the later shouldn't be the case so I would (hopefully) guess that it's the former that's the cause.

**Comment by masterjek** [comment]
> Are you able to increase the Apache worker count?
This is this parameter - ThreadsPerChild - 1920 and ThreadLimit - 1920

> Either the CPU reaches 100% because it cannot handle all the connections or because there are just too many connections.
I have several web panels on different VPS servers, the second server has a much more powerful processor, but over time it also becomes 100% loaded.

**Comment by UnamSanctam** [comment]
Do you have hashrate history enabled or disabled currently?

**Comment by masterjek** [comment]
> Do you have hashrate history enabled or disabled currently?

No, this option is disabled, I know that it heavily loads the server.
$config['hashrate_history_enable'] = false;

All problems begin when the number of workers reaches approximately 10,000, but of these, approximately 6,000-7,000 are active.
