### ISSUE TITLE
Any Configuration Templates?

### ISSUE THREAD

**Issue by LostMySpirit** [UnamSanctam/UnamWebPanel#289]
Hey are here any configuration templates for json cofig

**Comment by UnamSanctam** [comment]
Either you can get them in the miner builder by pressing the "JSON" tab inside a miner, or you can find them on the wiki: https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#remote-configuration, https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration.

The configuration format and settings are the same as the "Remote Configuration".

**Comment by LostMySpirit** [comment]
![grafik](https://github.com/UnamSanctam/UnamWebPanel/assets/72671296/5e36cb9a-a0c6-4607-928d-f2da88540758)
okey another question so remote config means that i can remote configurate it via pastebin and webpannel right?
what can i exactly setup with api endpoint?

**Comment by UnamSanctam** [comment]
Yes that's partly correct, the "Remote Configuration" is some "document" like Pastebin or other paste sites (or any site that lets you upload text and can be shown "raw"). But the "API Endpoint URL" is for the web panel URL. You can also add multiple URLs by separating them with a comma, so it's possible to have multiple backup "Remote Configurations" and also multiple backup "API Endpoint URLs" (web panel URLs).

**Comment by LostMySpirit** [comment]
so for example if i want to add my webpannel to the api endpoint i add the ip webadress to the endpoint url and incase it get banned i add , and my mining pool right?

**Comment by UnamSanctam** [comment]
If you connect to the webpanel using an IP then you add that yes, like so (example): `http://123.123.123.123/api/endpoint.php` (or https if you have an SSL certificate). Though you shouldn't add your mining pool, the comma is for backup URLs if you have any like so: `http://123.123.123.123/api/endpoint.php,http://124.124.124.124/api/endpoint.php,http://125.125.125.125/api/endpoint.php`

**Comment by LostMySpirit** [comment]
okey got it ty.

btw do i need to configure the pool in the miner or is it enough when i add the pastebin config

**Comment by UnamSanctam** [comment]
It's always good to do that in the miner too so that there's a backup/fallback if anything ever happens to your pastebin and/or web panel. Preferably the pool configuration in the miner should be considered your "final stand", so that if for some reason all the external things like the "Remote Configuration" or web panel stops working then the miner will still mine due to the configuration you entered when you built it.

**Comment by LostMySpirit** [comment]
![grafik](https://github.com/UnamSanctam/UnamWebPanel/assets/72671296/40cd682e-c5ae-4ff8-b461-e238bdc48c5a)
so i configurate it like that but it doesnt appear in the pool and pannel

**Comment by UnamSanctam** [comment]
Do you have an SSL certificate for your site? If not use http and not https. The miner should appear in the pool once it finds a share and the pool statistics update: https://github.com/UnamSanctam/SilentCryptoMiner/wiki#why-is-my-miner-not-showing-up-on-the-pool-even-though-its-mining

**Comment by LostMySpirit** [comment]
idk for some reason i cant see the miners in the pannel

**Comment by UnamSanctam** [comment]
And you changed it to http? If you copy the URL in the checker and enter it in your browser are you able to see the page?

**Comment by LostMySpirit** [comment]
yea in browser its worrking

i set it up via xampp on apache idk is there anything i need to change

**Comment by UnamSanctam** [comment]
Can you reach the page from the computer that you're running the miner on?

**Comment by LostMySpirit** [comment]
yea im am testing it on my main pc i see my pc in the pool but not in that pannel

**Comment by UnamSanctam** [comment]
Are you hosting the site on the same computer as you're running the miner? Since in that case you might need to use the local IP (127.0.0.1) when connecting on that computer. And can you try saving a "Configuration" on the web panel? To make sure that the database is writable.

**Comment by LostMySpirit** [comment]
okey i found the error i set the xampp server on port 84 so i needed to enter the link like 123.123.123.123;84/api/endpoint.php

thank you!
