### ISSUE TITLE
Ajax 500 error when i get table custom-tables.php

### ISSUE THREAD

**Issue by ZoomieOS** [UnamSanctam/UnamWebPanel#29]
Hello, I'm trying to get, and I have a 500 error in the POST

**Comment by UnamSanctam** [comment]
Make sure that your PHP version is somewhere at 7.4 or above.

**Comment by ZoomieOS** [comment]
But php is PHP Version 8.0.12

**Comment by ZoomieOS** [comment]
Alert when i got to main page DataTables warning: table id=miner-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**Comment by UnamSanctam** [comment]
A miner could have sent an invalid hashrate (known problem), you could replace your database with a clean one (backup any configurations if you have made any)

**Comment by ZoomieOS** [comment]
but if I click on the id, then the table is loaded, maybe the fact is that nothing comes to the id from the very beginning?

**Comment by UnamSanctam** [comment]
No (because that's not how it's designed), you can check for an error.log file somewhere among the files to see if it has generated any.

**Comment by ZoomieOS** [comment]
PHP Parse error:  syntax error, unexpected token "$",  in database.php
