### ISSUE TITLE
Enabled Auto Refrese Miners Going Offline

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/UnamWebPanel#298]
Actually Whats Happen in i enabled auto refresh option
after enabled auto refresh Miner hashrates are increseing and after someminutes miners are going offline 
why happen this ?

how many miners are max for webpenal ?

**Comment by UnamSanctam** [comment]
The auto-refresh just refreshes the table every 15 seconds so that you don't have to refresh manually to get update statistics. There is no max miners for the web panel, the only limits are whatever limits your webserver has.

**Comment by DARK-DEVIL-66** [comment]
Do you know any Easy way to spreding my miners ?

**Comment by DARK-DEVIL-66** [comment]
and whats actually happen in idle time mining or pushing ?

**Comment by UnamSanctam** [comment]
>Do you know any Easy way to spreding my miners ?

There aren't really any easy ways, though there are some popular methods, such as program cracks and game cheats.

>and whats actually happen in idle time mining or pushing ?

During idle mining it will use the set "Idle GPU" or "Idle CPU" instead of the "Max GPU" or "Max CPU".

**Comment by DARK-DEVIL-66** [comment]
program cracks and game cheats workout. but no Platform Avilable  for Spreding or Champign Site Still Avilable ?
