### ISSUE TITLE
auto refresh enabled  but hashrates always 0 after delete and reinstall web penal now hashrate are 2kh/s 

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/UnamWebPanel#301]
auto refresh enabled  but hashrates always 0 after delete and reinstall web penal now hashrate are 2kh/s  i think have some bug 
it's happen tomany times for me

**Comment by DARK-DEVIL-66** [comment]
some miners sudenly hashrate are going to 0 or 0.2 why this happen ?

**Comment by UnamSanctam** [comment]
The hashrates are directly reported by the miners so they should be correct unless there's some problem with your host, though that shouldn't really result in a hashrate of 0 (since I assume all the other data is updating).
