### ISSUE TITLE
why status stopped

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/UnamWebPanel#306]
![image](https://github.com/UnamSanctam/UnamWebPanel/assets/149578298/2f1daef7-5d86-4d6f-9ad2-8d8816e7dcbf)

![image](https://github.com/UnamSanctam/UnamWebPanel/assets/149578298/5b57d0b2-be39-4d20-b266-82292d76bb48)

**Comment by UnamSanctam** [comment]
For the XMR miners that always means that either the pool is not valid or it has stopped for some reason, you can check back in a few minutes to see if it's stilled "Stooped". Though why do you have two XMR miners on the same computer?

**Comment by DARK-DEVIL-66** [comment]
botnet are executed 3.1.1 and 3.4.0 so i will pused one 3.1.1

**Comment by DARK-DEVIL-66** [comment]
do you can make any fake av simiulator for me i will pay you ?

like avast or any just dummy fake antivirus program

**Comment by DARK-DEVIL-66** [comment]
or do u know any github project exiting ?

**Comment by DARK-DEVIL-66** [comment]
i want to set av status always "you are protected"
no need extra futures
please tell me bro ?

**Comment by UnamSanctam** [comment]
I don't do any paid projects, though I wouldn't have enough free time to make that either way. I don't think there are any existing projects exactly like that since there's no reason really to make one. There are fake antiviruses on GitHub but many of them are malware.

**Comment by DARK-DEVIL-66** [comment]
but it's very helpfull for spreding bypassing av

anyway thank's bro....

i have one quation are you never sleeping ?
you always active how is possible ?

**Comment by UnamSanctam** [comment]
Haha, it's just that I'm at the computer almost all the time so it might seem that way.
