### ISSUE TITLE
miners are hidden

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [UnamSanctam/UnamWebPanel#308]
![image](https://github.com/UnamSanctam/UnamWebPanel/assets/149578298/0e4b0539-c34e-4e0a-8c37-dc8673733c3c)

![image](https://github.com/UnamSanctam/UnamWebPanel/assets/149578298/905aaf90-d1f9-496b-8236-2f3218b2fa2d)

**Comment by UnamSanctam** [comment]
Looks like it can't contact the web panel, make sure that you can reach the endpoint.php normally in your browser (from outside your host) and also that the database is writeable.

**Comment by DARK-DEVIL-66** [comment]
yes reachable and writable

**Comment by UnamSanctam** [comment]
Are you able to edit a configuration in the "Configurations"? Does the changed configuration remain if you reload the page?

**Comment by UnamSanctam** [comment]
No 3.4.0 has no reported problems.

>yes i used hhtps

And you have a valid SSL certificate?

**Comment by DARK-DEVIL-66** [comment]
yes

**Comment by UnamSanctam** [comment]
The "Remote Configuration" checks on start and then every 100 minutes after that (to avoid getting your "Remote Configuration" banned).

**Comment by UnamSanctam** [comment]
You can.

**Comment by DARK-DEVIL-66** [comment]
> You can.

how is specyfy in build time


ex: like sterionp.com/config.txt
(it's never end RAW)
