### ISSUE TITLE
connection

### ISSUE THREAD

**Issue by iwillcontrol** [UnamSanctam/UnamWebPanel#309]
When I use the domain, I don't see the miner connecting to the panel, but using the ip it works

**Comment by iwillcontrol** [comment]
xampp

**Comment by UnamSanctam** [comment]
And the domain DNS is set up correctly? And are you sure that you're using the correct http or https (only use https if you have a certificate)?

**Comment by iwillcontrol** [comment]
> And the domain DNS is set up correctly? And are you sure that you're using the correct http or https (only use https if you have a certificate)?

I just sent my domain name to your email, please check

**Comment by iwillcontrol** [comment]
![Screenshot_2023-12-12-16-43-33-59](https://github.com/UnamSanctam/UnamWebPanel/assets/153245923/a32c717b-9544-41b0-8bb7-bec2a9674cf1)

**Comment by iwillcontrol** [comment]
> Where are you getting that? And it seems like your certificate can't be verified there. Though your certificate is valid.

..

**Comment by iwillcontrol** [comment]
> Where are you getting that? And it seems like your certificate can't be verified there. Though your certificate is valid.

ahh, it's because I didn't install ca bundle. but what if I put the panel file in the folder? like https://example.com/file/login.php

**Comment by iwillcontrol** [comment]
> Aha. And putting in inside a folder should work just fine.

thank you so much. Have a nice day!
