### ISSUE TITLE
Database broken after one worker

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/UnamWebPanel#316]
Hello Unam. After a certain time, a worker appears in the web panel, screenshot below.
![1](https://github.com/UnamSanctam/UnamWebPanel/assets/36513967/354ab5b0-ef67-417a-b8a4-5a76f1519f4a)
After this worker the database becomes broken. I cannot change the language, select miner configurations, view statistics, or delete workers. When I try to perform one of the above actions, I am simply directed to the authorization window.
I delete the old database, copy a new clean one and everything works fine. But over time, this worker appears again, and the IP address is different each time and after its appearance the database becomes corrupted.
It turns out that someone is hacking the web panel? But the log folder is empty, there are no errors.

**Comment by UnamSanctam** [comment]
It's most likely an XSS attack, you can see more here: https://github.com/UnamSanctam/UnamWebPanel/issues/313.

**Comment by masterjek** [comment]
I downloaded the version of the web panel that you recommended in the discussion. But even in it I got a worker who breaks the web panel. Screenshot below.
![2](https://github.com/UnamSanctam/UnamWebPanel/assets/36513967/da5d4857-8017-4331-95c3-29bc6befceec)

**Comment by UnamSanctam** [comment]
Yes he can still fake a miner connection (since there is of course no way to validate a miner connection as legitimate), but it should not break the web panel since the script isn't being run.

**Comment by masterjek** [comment]
Can I just delete this entry and the database won't break? Although if I delete it, will it come back again?

**Comment by UnamSanctam** [comment]
Yes you can delete it without issue, if he connects again with the fake miner connection then it will appear again, most likely he has a script that contacts your web panel at an interval.

**Comment by gabjohn3** [comment]
check the new Update for that security breach here
#317

**Comment by masterjek** [comment]
> проверьте новое обновление на предмет этого нарушения безопасности здесь [#317.](https://github.com/UnamSanctam/UnamWebPanel/issues/317)

Thank you, I installed a new project and am testing it.
