### ISSUE TITLE
The question that remained after the panel was hacked

### ISSUE THREAD

**Issue by HappyRoM4uK** [UnamSanctam/UnamWebPanel#321]
The other day, my panel was also hacked. And what happens if you don't restore the unamwebpanel.db, will past workers be able to be displayed after they are restarted?

**Comment by UnamSanctam** [comment]
Yes the miners will appear in the web panel once they restart just how they did the first time they connected. (Here's the latest hotfixed version of the web panel [UnamWebPanel.zip](https://github.com/UnamSanctam/UnamWebPanel/files/13891096/UnamWebPanel.zip))
