### ISSUE TITLE
Error #11

### ISSUE THREAD

**Issue by HappyRoM4uK** [UnamSanctam/UnamWebPanel#322]
What can this error mean?
![изображение_2024-01-10_214324002](https://github.com/UnamSanctam/UnamWebPanel/assets/89477015/0c35cbc2-5d62-429d-b5b2-15f2a2ba2068)

**Comment by UnamSanctam** [comment]
Looks like the SQLite database got corrupted for some reason.

**Comment by HappyRoM4uK** [comment]
Is it possible to somehow collect it, that this did not happen?

**Comment by UnamSanctam** [comment]
It can happen for several different reasons, it's theoretically possible to fix it though if you don't want to go through the trouble then you can always replace it with a new database and your miners will then reappear.

**Comment by HappyRoM4uK** [comment]
Is it enough to delete a file to create a new database?

**Comment by UnamSanctam** [comment]
You can do it by removing the unamwebpanel.db files (including db-shm and db-wal) inside the db folder, and then just place a fresh unamwebpanel.db file there https://github.com/UnamSanctam/UnamWebPanel/releases and it should work.
