### ISSUE TITLE
Do they really come back?

### ISSUE THREAD

**Issue by DerXanRam** [UnamSanctam/UnamWebPanel#324]
Hello unam. today when i was reading about the infamous XXS attack on the web panned, i see one weird miner adding him self to my panel and my miners started being offline. i immediately realized the situation and put my website down. then i upgraded to [the newer ](https://github.com/UnamSanctam/UnamWebPanel/issues/317#issuecomment-1884683799)version u provided.

I took the action immediately, but he managed to take ~90Kh/s in less than 1 minutes. My question is, i upgraded the panel and every thing is backing to the normal condition but not the miners he took. I see u mention i[n this issue](https://github.com/UnamSanctam/UnamWebPanel/issues/317), the miners will back on the next restart. however i use your very old miner(V 3.1.0) and i'm not sure version 3.1.0 have the feature or ability to do this. because the attacker changed the API URL and Remote URL  to his own address. Is there any chance they will back home?

**Comment by UnamSanctam** [comment]
Yes all versions of the miner go back to their builder configuration when they start, any configuration changes done while it's running (through either the "Remote Configuration" or web panel) are only in memory and never saved anywhere.

**Comment by DerXanRam** [comment]
> Yes all versions of the miner go back to their builder configuration when they start, any configuration changes done while it's running (through either the "Remote Configuration" or web panel) are only in memory and never saved anywhere.

OK thanks very much. And for information to another miners, this time when he add his miner, he done his best to cover the action. like he wasn't sent weird CPU name. instead he fill very accurate info and send some H/s. as a result every thing seems normal until i see my number of miners and recognize a new one :smiley: . take a look the screenshot 


![photo_5841305181151674681_y](https://github.com/UnamSanctam/UnamWebPanel/assets/101794261/a7923c8b-f2a8-4112-9c4d-b553bff275bc)


if u need to investigate more, i will share the full panel files. 

Thanks. have a nice time. :+1:
