### ISSUE TITLE
statistics error

### ISSUE THREAD

**Issue by anbu-squad** [UnamSanctam/UnamWebPanel#332]
![Screenshot 2024-01-26 at 17-19-51 Unam Web Panel Unam Sanctam](https://github.com/UnamSanctam/UnamWebPanel/assets/88142198/259f7288-9055-4c25-be24-21249c0dfdc0)

I don't know what's wrong
I'll just leave this error here
it may be important to report

**Comment by UnamSanctam** [comment]
It's someone trying to hack your web panel, though they were unsuccessful (hence why you can see the text).

**Comment by anbu-squad** [comment]
Perhaps it’s easier to re-upload the panel to the server to correct the error?

**Comment by UnamSanctam** [comment]
Well it's not an error, the person that tried to hack you just sent in that data to try and hack you. You can remove the miner entry of their fake connection and it will disappear.

**Comment by anbu-squad** [comment]
thanks, I just deleted all offline miners and the page statistics returned to normal
