### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by kevincrafturu2** [UnamSanctam/UnamWebPanel#333]
Hello, how could i run this in an  linux server VPS? i dont want to use 000 webhost, please i need this info

**Comment by kevincrafturu2** [comment]
i saw that i needed to put them at /var/www/html, i put the webapp files there, but nothing happend when i restarted apache, i couldnt start it

**Comment by UnamSanctam** [comment]
If you have set up Apache and PHP correctly then placing the files there and visiting the site in your browser should work. I don't know what distro your VPS has but here's one for Ubuntu: https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu-22-04, you can skip all the MySQL parts of the guide.

**Comment by kevincrafturu2** [comment]
its an normal ubuntu distro, i put the files like this, should it be ok? 
![image](https://github.com/UnamSanctam/UnamWebPanel/assets/48927699/f50e95fd-67ea-48ab-a05d-76e42296c072)

**Comment by kevincrafturu2** [comment]
i do have an domain used for other thing, an nginx  pterodactyl setup, but i will not use it more,  i kinda not get all the stuff about the domain and all that in the sites avilable step

**Comment by UnamSanctam** [comment]
Yes that file structure looks correct. You can skip the virtual hosts step if you want (I guess that's what you mean). You can also use the IP directly if you want without instead of a domain.

**Comment by kevincrafturu2** [comment]
maybe its cuz i just put the files there, maybe i should do an folder called UnamSantactm, so its like /var/www/html/UnamSantctam and in that folder the files

**Comment by UnamSanctam** [comment]
No placing the files like that works fine, as long as your web server is correctly set up the panel will show when you visit the site.

**Comment by kevincrafturu2** [comment]
do i need to make the sites-avilable config  file?

**Comment by kevincrafturu2** [comment]
couldnt seem to fix it, i put the files everything reloaded apache didnt work, put them on an folder then did the conf file with, or without domain tried twice, still does not work

**Comment by kevincrafturu2** [comment]
its there any other way to install it? maybe nginx its easier

**Comment by UnamSanctam** [comment]
Since you use the default html folder you don't need to mess with virtual hosts (sites-available). What exactly isn't working?

**Comment by kevincrafturu2** [comment]
I put the ip, or the domain i used and it does not load

**Comment by kevincrafturu2** [comment]
do you have an nginx guide? maybe its easier from there

**Comment by UnamSanctam** [comment]
Are the ports forwarded on the VPS? Are port 80 and 443 (for https) open? Since it doesn't load at all then the problem is most likely is that your web server isn't reachable. The same thing would happen with nginx (or anything else) in that case.

**Comment by kevincrafturu2** [comment]
Il just do an fresh install on the vps and try again

**Comment by kevincrafturu2** [comment]
Very stupid solution, i reinstalled, tried with nginx, and for some reason as it was linked to an domain, i unlinked it but  google kept redirectioning to  that domain that i dont have anymore, so i put in an incognito tab the ip and  the main nginx thing appeared, do  i just now move the files to nginx thing? or do i need to do the config file? how should i put the nginx config file of /etc/nginx/sites-available/ so it works with only the ip

**Comment by kevincrafturu2** [comment]
i did the config myself  now it appears an error "The required SQLite PDO driver IS NOT enabled." im from linux btw

**Comment by kevincrafturu2** [comment]
Fixed it, now there is an error on the login that says Something Went Wrong

**Comment by kevincrafturu2** [comment]
Sorted.
