### ISSUE TITLE
What Is The Username For The Login Page When Going To The Website?

### ISSUE THREAD

**Issue by Aaron-656** [UnamSanctam/UnamWebPanel#334]
I Cant Find The Username For The Login Page When Going To The Website Ive Looked In The Code And Still Cant Find It

![image](https://github.com/UnamSanctam/UnamWebPanel/assets/147849093/a56fc090-a185-4056-bee9-41486f14fcff)

**Comment by UnamSanctam** [comment]
That isn't from the web panel, the popup might come from your webhost.

**Comment by Aaron-656** [comment]
Oh Ok Do You Know Of Any Free Webhost That I Can Use For This WebPanel?

**Comment by UnamSanctam** [comment]
All webhosts are able to host it but there usually aren't many free webhosts that don't have large restrictions, for example on the amount of traffic, how many hours per day the site can be up and how much they surveil your website to make sure you're not running anything like a web panel. I don't know what webhosts people use so sadly I don't know which are good (if there are any good ones).

**Comment by Aaron-656** [comment]
Thanks For Your Help But I Have Fixed The Problem And It Was The WebHost
