### ISSUE TITLE
risks of selfhosting

### ISSUE THREAD

**Issue by ghost** [UnamSanctam/UnamWebPanel#336]
Hello, I have some doubts about hosting the panel on a physical server through port forwarding and I would like to know if it has any risks and what measures I could use to avoid security problems with the public IP and other stuff, thank you!

**Comment by UnamSanctam** [comment]
Well, the risk is mainly two things: 1) The IP will of course be exposed, as long as this IP is not connected to your identity in any way then this is fine, and 2) The IP address might get blacklisted in a lot of places so it shouldn't be an important IP, or if you're buying/renting the IP address from somewhere (like a VPS or VPN) then they might ban your account or revoke your access (for VPNs this isn't very common).

**Comment by UnamSanctam** [comment]
You can do so but using your real IP is risky so preferably you would use a no-log VPN that allows port forwarding, I also self-host everything but I do use VPNs to do so.
