### ISSUE TITLE
auth error

### ISSUE THREAD

**Issue by h09s** [UnamSanctam/UnamWebPanel#337]
so when trying to login i get this error 
![image](https://github.com/UnamSanctam/UnamWebPanel/assets/72148172/7ede1483-9c51-4c4d-87bb-bf39355f6160)
the password is correct using the latest version

**Comment by UnamSanctam** [comment]
Check the UNAM_LIB\Logs folder for any errors, most likely your database file and folder aren't writable.

**Comment by UnamSanctam** [comment]
You see the permissions under your file in the screenshot.

**Comment by UnamSanctam** [comment]
Just make the db folder and unamwebpanel.db files writable.
