### ISSUE TITLE
is the webpanel working for me personally not idk why it just doesnt connect with the miner

### ISSUE THREAD

**Issue by Bantorbann** [UnamSanctam/UnamWebPanel#347]

**Comment by UnamSanctam** [comment]
What's the URL you're connecting to the web panel with (you can censor the URL/IP if they aren't a local address)? You can run the checker and see. And is the database folder (db) and database file (db/unamwebpanel.db) writable? You can check by creating a new configuration and see if it appears in the edit list.

**Comment by Bantorbann** [comment]
its trustabletechsupport.com/hack .....

**Comment by UnamSanctam** [comment]
And you entered `https://trustabletechsupport.com/hack/api/endpoint.php` into the "API Endpoint URL" in the miner?

**Comment by Bantorbann** [comment]
yes

**Comment by Bantorbann** [comment]
thanks for your help in this one it was a problem with the hoster with the /hack
