### ISSUE TITLE
0H/s

### ISSUE THREAD

**Issue by DogusCyk** [UnamSanctam/UnamWebPanel#35]
Why is the digging speed of most active miners 0 H/s on the panel?

**Comment by UnamSanctam** [comment]
Either their settings are wrong or if they're GPU miners then they most likely don't have enough free VRAM to mine.

**Comment by DogusCyk** [comment]
> Either their settings are wrong or if they're GPU miners then they most likely don't have enough free VRAM to mine.

I understand also will you open a new discord account

**Comment by UnamSanctam** [comment]
Maybe, I'll probably just get banned again eventually though.
