### ISSUE TITLE
I can't make 

### ISSUE THREAD

**Issue by nomad1420** [UnamSanctam/UnamWebPanel#36]
Hi unam. I try different host services (infinity,pro free host etc.) ım make my control panel ım runnıng mıner but ı cant take any information on webpanel ? How can ı make it ? Can you advice any free hosting services ? Thank you for all services <3

**Comment by nomad1420** [comment]
ı need your help Unam Plz help me bro

**Comment by UnamSanctam** [comment]
Most should work that don't block traffic (some block traffic from "unknown" user agents and such), make sure that you're entering the correct URL for the web panel into the miner.

**Comment by nomad1420** [comment]
yea of course ım thinl ı made everything correct. Can you check pictures thats correct or false 
![1](https://user-images.githubusercontent.com/95175778/147418636-239f9e0c-adb6-4986-8c37-b03faf625f3c.jpg)
![2](https://user-images.githubusercontent.com/95175778/147418642-a0093bbc-02e1-4214-808b-4c826b7b881b.jpg)
![3](https://user-images.githubusercontent.com/95175778/147418649-6233fa3e-06fe-485c-88c4-7a118f5edc2b.jpg)
![4](https://user-images.githubusercontent.com/95175778/147418651-2c5b976d-3b91-4679-9110-2409474d348d.jpg)
![5](https://user-images.githubusercontent.com/95175778/147418652-108f5ae3-f17c-4cf6-97af-c2bd178a7947.jpg)
![6](https://user-images.githubusercontent.com/95175778/147418653-2ebcd311-2ab0-4ce5-af33-77d8a481ebb0.jpg)
![7](https://user-images.githubusercontent.com/95175778/147418656-5e3bfabe-b712-44b3-b5dd-ad84f6181c26.jpg)
![8](https://user-images.githubusercontent.com/95175778/147418660-5cd57195-f4fa-44c4-a9f5-965a052a538a.jpg)
![9](https://user-images.githubusercontent.com/95175778/147418661-9010b96d-31c3-4749-8e6f-abfe3f860d26.jpg)
![10](https://user-images.githubusercontent.com/95175778/147418662-1e958117-a973-4838-86a8-ef0a42c0fc0f.jpg)

**Comment by UnamSanctam** [comment]
Yes that all looks correct, make sure that the database has write permissions and everything. You can also try changing it to `http` instead `https` to see if it's something with your certificate. Other than that the host could be blocking the traffic.

**Comment by nomad1420** [comment]
Is there an any host site you can recommend?

**Comment by nomad1420** [comment]
> Yes that all looks correct, make sure that the database has write permissions and everything. You can also try changing it to `http` instead `https` to see if it's something with your certificate. Other than that the host could be blocking the traffic.

Im try in http ıts give me same mistake and ım add my website ssl certifica

**Comment by nomad1420** [comment]
what you think this subject ???

**Comment by nomad1420** [comment]
hey unam , bro can you check my messsages ?

**Comment by UnamSanctam** [comment]
In case you still need to fix it I would try another host since that's what has made it work for most people,
