### ISSUE TITLE
Example Settings for SilentCryptoMiner

### ISSUE THREAD

**Issue by braxx7on** [UnamSanctam/UnamWebPanel#366]
Hi there,

I saw that the SilentCryptoMiner repo has been disabled. I was just curious if I could get the example settings (full) for it? I can't remember exactly how input 2miners settings with SilentCryptoMiner.

Thanks in advance

**Comment by UnamSanctam** [comment]
And think these were the latest example settings, I'm not fully sure.
[ExampleSettings_Lite.zip](https://github.com/user-attachments/files/16039465/ExampleSettings_Lite.zip)
[ExampleSettings_Full.zip](https://github.com/user-attachments/files/16039467/ExampleSettings_Full.zip)
