### ISSUE TITLE
What happened to the SilentCryptoMiner repository?

### ISSUE THREAD

**Issue by norderan** [UnamSanctam/UnamWebPanel#367]
I was looking for it and I couldn't find it. found this instead: https://github.com/SilentCryptoMiner/SilentCryptoMiner
Is this repository valid? Thank you.

**Comment by UnamSanctam** [comment]
It got taken down by GitHub, I have sent in an appeal to try and get it reinstated. The repository you linked is not a valid one.

**Comment by norderan** [comment]
Is there a place I can download it from?

**Comment by braxx7on** [comment]
> Is there a place I can download it from?

https://github.com/UnamSanctam/UnamWebPanel/issues/361#issuecomment-2138323517

**Comment by norderan** [comment]
Thanks!
