### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/UnamWebPanel#37]
yo unam,

i've tried reaching out to you on discord plenty times but you haven't responded? what's up with that, or do you just not use discord anymore.

**Comment by UnamSanctam** [comment]
My Discord account was banned so I cannot see any messages or respond.

**Comment by shainodev** [comment]
ohh that explains much, do u have a new discord account by chance?

**Comment by CarloPonxi** [comment]
Please @UnamSanctam, use this app, completely safe (so far lol),and open source.

https://github.com/qTox/qTox

**Comment by shainodev** [comment]
> 

totally seems legit

**Comment by shainodev** [comment]
> My Discord account was banned so I cannot see any messages or respond.

wanted to ask u if windows 11 is capable of running the miner, or does it have any issues with it also orcus rat (educational purposes) would it be good if i used the UnamBinder for my VM's of course.

**Comment by UnamSanctam** [comment]
I haven't made a new account, I think I might get banned again though. The miner works fine on Windows 11 and you can use a RAT together with it just fine.

**Comment by CarloPonxi** [comment]
@UnamSanctam is Carlo from Discord... So far i believe qtox it's the best alternative to discord, or telegram, but on both you can be banned, please use qtox as it's decentralized and crypted all the way.

**Comment by UnamSanctam** [comment]
> @UnamSanctam is Carlo from Discord... So far i believe qtox it's the best alternative to discord, or telegram, but on both you can be banned, please use qtox as it's decentralized and crypted all the way.

Ah, I might look at it, I've also been looking at Hugin since I do have a few people "added" there as well. Problem is that most people don't really want to use any unfamiliar programs.

**Comment by CarloPonxi** [comment]
Looks really weird, but it's safe and that's the most important part (you can even review the code yourself). No one can be banned either, that's also important. And no 3rd party addons or stuff is needed, Hugin stores messages as its based on blockchain... 

Who may need your help will use it though, as happened before with Discord.

**Comment by CarloPonxi** [comment]
A New Kind of Instant Messaging
With the rise of monitoring programs, qTox provides an easy to use application that allows you to connect with friends and family without anyone else listening in. While other big-name services require you to pay for features, qTox is totally free, and comes without advertising.
 
Taken from: https://qtox.github.io
