### ISSUE TITLE
Date Modified

### ISSUE THREAD

**Issue by dwaor** [UnamSanctam/UnamWebPanel#373]
When the Miner is created with the latest Silent crypto Miner 3.4.1 it modifies the date of the miner and sometimes its even modified at 2021 why does this happen?

**Comment by UnamSanctam** [comment]
Because recently created files often makes them more suspicious for antiviruses and other similar software.

**Comment by dwaor** [comment]
> Because recently created files often makes them more suspicious for antiviruses and other similar software.

Thanks!
