### ISSUE TITLE
Lots of Workers but 10% miners

### ISSUE THREAD

**Issue by dwaor** [UnamSanctam/UnamWebPanel#375]
So I have like 100 workers registered over the days but only 10 are mining of them for example.

Did I do something wrong? Are they not Starting up after pc restart?

**Comment by UnamSanctam** [comment]
The computers could be turned off, how long have they been offline for? Since the majority of people turn off (or put into power saving mode or hibernation) when not using their computer.

**Comment by dwaor** [comment]
> The computers could be turned off, how long have they been offline for? Since the majority of people turn off (or put into power saving mode or hibernation) when not using their computer.

Im not sure since im not using a web panel but on my pool 6 to 24 hours but the inactive miners dont disappear from my pool

**Comment by UnamSanctam** [comment]
On some pools you can click each worker to see when they have been mining, so you can check like that. But if the workers aren't disappearing then that's usually good since it means they have mined within the worker removal interval for that pool.

**Comment by dwaor** [comment]
> On some pools you can click each worker to see when they have been mining, so you can check like that. But if the workers aren't disappearing then that's usually good since it means they have mined within the worker removal interval for that pool.

![Screenshot 2024-07-11 145849](https://github.com/UnamSanctam/UnamWebPanel/assets/175016702/08945fdc-98c4-4a96-bbad-ab7abed1b68c)

This is how my Pool shows it do you think anything is wrong? Do you have miners yourself with similar last seen / mined.

**Comment by UnamSanctam** [comment]
Those offline times don't tell very much yet, it's usually after about 2 days of being offline when one can consider a miner to likely be gone. It mostly depends on what kind of users you have, some people use their computers quite a lot while some only occasionally.

**Comment by dwaor** [comment]
> Those offline times don't tell very much yet, it's usually after about 2 days of being offline when one can consider a miner to likely be gone. It mostly depends on what kind of users you have, some people use their computers quite a lot while some only occasionally.

Afk and Gaming type users

I also dont see any miner that has gone over the 23 hour inactive in my pool maybe raptoreum pool does not show more than a day?

**Comment by UnamSanctam** [comment]
It's possible, not sure since I haven't used any Raptoreum pool before. And you had "Startup" enabled when building the miner?

**Comment by dwaor** [comment]
> It's possible, not sure since I haven't used any Raptoreum pool before. And you had "Startup" enabled when building the miner?

Yeah I enabled Startup and the Watchdog, Windows Updates disabled, Run as Administrator enabled, Add to Windows Defender exclusion enabled.

**Comment by UnamSanctam** [comment]
Alright then that's good.

**Comment by dwaor** [comment]
> Alright then that's good.

Alright thanks alot and good luck to you with your projects
