### ISSUE TITLE
Nanopool question

### ISSUE THREAD

**Issue by LostMySpirit** [UnamSanctam/UnamWebPanel#376]
So i switched pools a couple of days ago to nanopool and have some issues. So is it possible to show the workers pc names and i had issues changing the mining payout because of an email does anyone know how i can eddit that or do i need to paste my email somewhere in the json remote config?

**Comment by UnamSanctam** [comment]
For nanopool the worker name and email/password for changing the withdrawal should be entered inside the "Wallet Address"/"wallet" field, so something like this: `Wallet.{COMPUTERNAME}/WithdrawalPassword`
