### ISSUE TITLE
Another Request For My Man Unam

### ISSUE THREAD

**Issue by DumbStackz4L** [UnamSanctam/UnamWebPanel#379]
unam is there a way for you to add a "disable power button or make it look like its shutting down but it keeps the miner still working" Maybe by muting audio and disconnecting external USB'S of all sorts. Like because I'm finding out that it drastically makes my profits like $90 a month to $15 a month. So if there is a way for you to do that it would make me happy make sure the display is definitely off too if you could work your magic I'd be happy :) your the best man. And I  understand but my targets are pretty dumb and know nothing about computers. So if Unam you could take some time and do it I would be very greatful :) (If you make it ill pay you $50 in bitcoin thats how desperate i am lol)

**Comment by DumbStackz4L** [comment]
what i really mean is if there is a way that you can have the computer shut down as normal but without having the computer stop running so the application can run over night as well if that is possible. Thanks man make sure it works for windows 10/11 especially if possible and other versions of windows if possible thanks man :)

**Comment by UnamSanctam** [comment]
While it could theoretically possibly be done (though I'm unsure about hooking/intercepting the power button and such) that would be quite a massive project, I can try but that would take some time.

**Comment by DumbStackz4L** [comment]
i just want the silent miner that you created to still run even when a user's computer has been shutdown or in sleep mode.  I'm not good at coding but i think that even if you added a .bat that could run these commands and add some registry stuff to have it run while in sleep mode/shutdown that would be awesome. I know that this may be challenging. But I am grateful for you trying you're very good at what you do. (You could even have the whole computer running i just want the physical appearance of the computer off. If that makes sense sorry if I am bad at explaining)

**Comment by DumbStackz4L** [comment]
> While it could theoretically possibly be done (though I'm unsure about hooking/intercepting the power button and such) that would be quite a massive project, I can try but that would take some time.
Sorry if I message a lot I am not sure if you saw it but i also commented "
i just want the silent miner that you created to still run even when a user's computer has been shutdown or in sleep mode. I'm not good at coding but i think that even if you added a .bat that could run these commands and add some registry stuff to have it run while in sleep mode/shutdown that would be awesome. I know that this may be challenging. But I am grateful for you trying you're very good at what you do. (You could even have the whole computer running i just want the physical appearance of the computer off. If that makes sense sorry if I am bad at explaining)" Also I was wondering a eta estimate on how long this would take you.
