### ISSUE TITLE
Source code pls

### ISSUE THREAD

**Issue by DerXanRam** [UnamSanctam/UnamWebPanel#382]
Hello unam can u share the silent miner latest source code and latest build link pls? cause i see the repo is removed 😭

**Comment by alcinzal** [comment]
You can find it in his comment [here](https://github.com/UnamSanctam/UnamWebPanel/issues/361#issuecomment-2208790180).

**Comment by DerXanRam** [comment]
> You can find it in his comment [here](https://github.com/UnamSanctam/UnamWebPanel/issues/361#issuecomment-2208790180).

tnx man
