### ISSUE TITLE
Panel not showing Bots (infinityfree)

### ISSUE THREAD

**Issue by haxful** [UnamSanctam/UnamWebPanel#39]
Hello,

 I have finally got the miner working but when I was testing it on my self I didn't appear on my panel, I've been reading past issues and I think it might be my permissions on the host could you take a look and see if there is something wrong I'll add a screenshot.

Thanks in advance,
![image](https://user-images.githubusercontent.com/96766982/147686627-9b111fe2-35d4-4d6c-baab-d6972a912b4e.png)

**Comment by UnamSanctam** [comment]
Not sure if you need write permissions for the group or not, but also try checking the permissions of the db file itself (unamwebpanel.db).

**Comment by haxful** [comment]
This is what it says, 
![image](https://user-images.githubusercontent.com/96766982/147687774-584f46e4-fe48-4e9a-af17-a64a14b021e7.png)

**Comment by UnamSanctam** [comment]
I'm unsure how your host has set up everything on their side by try changing the "Manual" field to 664.

**Comment by haxful** [comment]
Should this work now?
![image](https://user-images.githubusercontent.com/96766982/147688065-3b0e83a4-3ee0-4e8a-8d31-5834dbbd5196.png)

**Comment by UnamSanctam** [comment]
Yes maybe, make sure that the URL and everything is correct in the miner as well.

**Comment by haxful** [comment]
The miner and everything seem to be working but I'm having an issue connecting to the panel it's just loading I think it might be a host issue would It be better to host it myself?
![image](https://user-images.githubusercontent.com/96766982/147690148-a679698d-227b-48a7-a0df-e4f7c46d7409.png)
