### ISSUE TITLE
uninstaller isn't working

### ISSUE THREAD

**Issue by picklejohndoe** [UnamSanctam/UnamWebPanel#397]
so when I run tests to make sure things work the way they are supposed to and try to uninstall the miner. the miner keeps mining. this has only happened on a few tests not all. i don't mind as a last option having to wipe my computer and delete the os and reinstall it but that would take a bit of time.

**Comment by UnamSanctam** [comment]
It should always work really, if you run the uninstaller and wait for it to finish, and then run the checker does it say that any miners are running? Even then as long as the miners installed service gets uninstalled/removed and as long as the watchdog gets killed then the miner will disappear with just a normal restart.

**Comment by picklejohndoe** [comment]
got it. thank you
