### ISSUE TITLE
I cant find GPU on the webpanel

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/UnamWebPanel#4]
No GPU is shown on miners

Just desktop name

**Comment by UnamSanctam** [comment]
Oh right, I might have forgot to add it into the release version. The miners does send the GPU and CPU data to the panel but it might not be accepting it.

**Comment by Brainshot** [comment]
> 
> 
> Oh right, I might have forgot to add it into the release version. The miners does send the GPU and CPU data to the panel but it might not be writing it into the database.

Alright when will you add it to the database?

**Comment by UnamSanctam** [comment]
I've added it now but I'm thinking if there is anything else I've missed or have to add since I don't want to spam small releases all the time.

**Comment by UnamSanctam** [comment]
I couldn't really find anything I could add quickly so I just released a version with only the GPU and CPU fields added. You will have to replace the database (or add the two fields into a current one though that can be difficult unless you know what you're doing).

**Comment by UnamSanctam** [comment]
Have you made any "Configuration" or anything else like that? If not then you can just replace the .db file with the one from the new version. The miners will simply be added back when they connect to the panel.

**Comment by Brainshot** [comment]
> 
> 
> Have you made any "Configuration" or anything else like that? If not then you can just replace the .db file with the one from the new version. The miners will simply be added back when they connect to the panel.

alright done thanks for help

**Comment by UnamSanctam** [comment]
No problem
