### ISSUE TITLE
webpanel

### ISSUE THREAD

**Issue by obamaklan** [UnamSanctam/UnamWebPanel#40]
Hey! I configured the panel, but the bots are not displayed
![Снимок экрана (98)](https://user-images.githubusercontent.com/84593653/147735021-2dc44ff6-2bcc-4d62-bccc-325cace0da49.png)
![Снимок экрана (97)](https://user-images.githubusercontent.com/84593653/147735032-fcf6a7d1-2312-4c71-86c3-65e0e2282de7.png)

i am using ubuntu 20.04

**Comment by UnamSanctam** [comment]
Make sure the file permissions on the .db file and parent folders have the correct permissions and ownership.
