### ISSUE TITLE
Help with setting everything up 

### ISSUE THREAD

**Issue by Stuntah14** [UnamSanctam/UnamWebPanel#41]
This is just a suggestion but I feel like if there was a video of you showing how to setup and configure the WebPanel in order for everything to work it would greatly help people.Thank you

**Comment by UnamSanctam** [comment]
They way to "set it up" depends entirely what host you use, since technically all you have to do is upload the files to the host and you're done. Unless you also need to update the PHP and/or change permissions of the files but that also depends entirely on what host is used.

**Comment by Stuntah14** [comment]
I apologize for the comment if I’m honest, I just spent an hour and got the webpanel working and the instructions you gave were clear enough. Thanks bro

**Comment by UnamSanctam** [comment]
Ah great, glad to hear it!
