### ISSUE TITLE
Version 3.2.0

### ISSUE THREAD

**Issue by masterjek** [UnamSanctam/UnamWebPanel#419]
Hi Unam. Can you please provide a link to version 3.2.0, but only to the entire project, not to the compiled builder version.

**Comment by alcinzal** [comment]
You can find both the compiled version, but also the source code here: https://github.com/UnamSanctam/UnamWebPanel/issues/361#issuecomment-2208790180

**Comment by masterjek** [comment]
> Вы можете найти как скомпилированную версию, так и исходный код здесь: [#361 (комментарий)](https://github.com/UnamSanctam/UnamWebPanel/issues/361#issuecomment-2208790180)

This is a new version. I don't need it. I need version 3.2.0.

**Comment by alcinzal** [comment]
> This is a new version. I don't need it. I need version 3.2.0.

Ah I see, that's my bad. May I ask why you need exactly that version?

**Comment by masterjek** [comment]
> > Это новая версия. Мне она не нужна. Мне нужна версия 3.2.0.
> 
> А, понял, это моя ошибка. Могу я спросить, зачем вам именно эта версия?

New versions have bugs, especially xmrig, which sends a lot of reject shares. I even got blocked by IP on some pools for a huge number of reject shares. Moreover, I spent a week talking to the pool's technical support, they tested everything on their side, I tested it on mine, and we came to the conclusion that the bug is in xmrig.exe
