### ISSUE TITLE
Panel not showing miner

### ISSUE THREAD

**Issue by Duy0104** [UnamSanctam/UnamWebPanel#42]
Hi Uman. I have got this issue and i had read open and close issues. I had check the /api/endpoint.php and as you said it works correctly
![image](https://user-images.githubusercontent.com/96539207/147880885-51f0e94e-ee71-4356-9485-3b9bf708da94.png)
But it's doesn't show in the panel
![image](https://user-images.githubusercontent.com/96539207/147880914-673dfc72-5272-4484-8d61-e475dc41f8da.png)
And the Miner still working
![image](https://user-images.githubusercontent.com/96539207/147880923-7b34aea2-1dd1-4532-87c2-baaaf3cdcd27.png)
Hope you will reply this.Thanks you alot

**Comment by UnamSanctam** [comment]
Check that unamwebpanel.db has write permissions in your webhost.

**Comment by Duy0104** [comment]
![image](https://user-images.githubusercontent.com/96539207/147881826-bb02570a-ca9e-4d0f-93ff-be5d44435a19.png)
Yes it's said access denied

**Comment by Duy0104** [comment]
![image](https://user-images.githubusercontent.com/96539207/147882647-e33f0114-62b4-4437-b613-022d5d92b5b2.png)
Had give it permissions. But it still access denied

**Comment by UnamSanctam** [comment]
Yes it should say access denied on the web page, also change the permissions on the unamwebpanel.db file itself like you did for the directory. But uncheck the "Public permissions" "Write" and "Execute" boxes I believe.

**Comment by Duy0104** [comment]
![image](https://user-images.githubusercontent.com/96539207/147882859-ccbb9149-3e57-480e-b283-c18491532811.png)
Umm it still not working

**Comment by Duy0104** [comment]
![image](https://user-images.githubusercontent.com/96539207/147882935-ac2991b0-f957-4aa2-907c-0420101bb6ec.png)
Still not working

**Comment by UnamSanctam** [comment]
Can you go to the __UNAM_LIB folder and create a Logs folder in there?

**Comment by Duy0104** [comment]
![image](https://user-images.githubusercontent.com/96539207/147883339-a06f5e52-1dc2-47b2-87da-9ba574ed1843.png)
U mean like this ?

**Comment by UnamSanctam** [comment]
No a folder called Logs and not a file. I would also advice you to move everything from inside the "UnamWebPanel" folder into the root folder of your host (where "UnamWebPanel-master" is located).

**Comment by Duy0104** [comment]
xD i changed different webhost. And it works perfectly
![image](https://user-images.githubusercontent.com/96539207/147883740-fcac21ea-4309-4e2c-9d62-8a81d693fdfa.png)
Thanks for helping me again.

**Comment by UnamSanctam** [comment]
No problem and good job, and yeah some hosts block some connections.
