### ISSUE TITLE
Problems with displaying specifications of the miner 

### ISSUE THREAD

**Issue by Stuntah14** [UnamSanctam/UnamWebPanel#43]
![IMG_5303](https://user-images.githubusercontent.com/96040517/147892345-fefbcc89-ada4-4e20-81a5-aecac8ddf28a.png)
Webpanel won't show pool, port, algorithm and other details but in the Miner Checker it shows everything correctly

**Comment by UnamSanctam** [comment]
Then it haven't created a connection to the pool (no connection is active so it doesn't list any), make sure that the settings are correct.

**Comment by Stuntah14** [comment]
I won’t lie setting this up and configuring everything correctly when starting is extremely confusing

**Comment by UnamSanctam** [comment]
Check the pool for what configuration you should have (pool address, pool port, wallet addres/worker name format and such).

**Comment by Stuntah14** [comment]
If I wanted to use this on multiple computers in my house would I have to create a new exe for each computer or could I just put the same file on each one?

**Comment by UnamSanctam** [comment]
Same file for each one.

**Comment by Stuntah14** [comment]
And would they each appear individually on the webpanel?

**Comment by UnamSanctam** [comment]
Yes it creates a unique ID for each computer based on a few factors.

**Comment by Stuntah14** [comment]
Last question hopefully, is there a limit to how many computers I can connect?

**Comment by UnamSanctam** [comment]
No there's no limit at all for the miner itself, but your web host could limit the connections to the web panel of course (though they would still be mining just fine) and the pool could have a theoretical "limit" where they ban you for believed botnet mining though I haven't ever seen it happen personally yet (and I've been developing the miners for over 2 years now).

**Comment by Stuntah14** [comment]
Thanks for the help my friend

**Comment by UnamSanctam** [comment]
No problem, good luck with everything.

**Comment by Stuntah14** [comment]
I have fully setup the miner now and it is working, but the webpanel still does not show the pool specifications. When I run the miner it shows recent connection correctly, I have confirmed with you that the pool information shown in the miner is correct so I am confused as to why it won't display it

**Comment by UnamSanctam** [comment]
Hmm, only reason it wouldn't show it is if there's no active connection, try replacing the database (unamwebpanel.db) with a "clean" version.

**Comment by Stuntah14** [comment]
![image](https://user-images.githubusercontent.com/96040517/147901042-adfe1e61-1abc-4702-b2e6-d6ec6e711ca5.png)
is it supposed to look like this? looks a bit strange

**Comment by UnamSanctam** [comment]
Yes most likely.

**Comment by Stuntah14** [comment]
I remade the webpanel freshly and it still won't show the pool details

**Comment by UnamSanctam** [comment]
You could have several miners on your computer (from earlier attempts) running that reporting details to the web panel.

**Comment by Stuntah14** [comment]
I just used my laptop and the miner worked as well, although it did not pop up as a seperate device in the panel

**Comment by UnamSanctam** [comment]
It should appear as a separate one as long as the laptops computer name and CPU are different:
https://github.com/UnamSanctam/UnamWebPanel/blob/8690c4b269f305c17ea1fc34dc2e26e107632472/UnamWebPanel/api/endpoint.php#L16
Most likely it couldn't connect to the web panel I guess.

**Comment by Stuntah14** [comment]
Nevermind it has appeared on the webpanel and on my laptop it appears with all the pool config, thank you for your time and help bro!

**Comment by UnamSanctam** [comment]
Great, good job getting it all working.
