### ISSUE TITLE
IMPORTANT - NOT RELATED TO THIS REPO

### ISSUE THREAD

**Issue by Laugny** [UnamSanctam/UnamWebPanel#432]
Can you give me a download of the blocked silent miner pls?

**Comment by alcinzal** [comment]
This? https://github.com/UnamSanctam/UnamWebPanel/issues/361#issuecomment-2208790180

**Comment by Laugny** [comment]
> This? [#361 (comment)](https://github.com/UnamSanctam/UnamWebPanel/issues/361#issuecomment-2208790180)

yehhh tyy
