### ISSUE TITLE
No able to login after webpanel installed

### ISSUE THREAD

**Issue by zaromarco** [UnamSanctam/UnamWebPanel#44]
Hi , i have install the apache addon with php support into home assistant , then i loaded the file into share/htdocs , all files and dirs have rwx property
then i setup my password into config.php , reload the whole apache just to be sure , then i use chrome to navigate to the login page , it show password , i entered the password but in the top right corner everytime appear somethings goes wrong....
i see in the htdocs a error.log file which report these errors:

[03-Jan-2022 21:35:55 UTC] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on bool in /share/htdocs/__UNAM_LIB/unam_lib.php:31
Stack trace:
#0 /share/htdocs/auth-ajax.php(11): unam_lib->unam_dbSelect()
#1 {main}
  thrown in /share/htdocs/__UNAM_LIB/unam_lib.php on line 31
[03-Jan-2022 21:56:55 UTC] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on bool in /share/htdocs/__UNAM_LIB/unam_lib.php:31
Stack trace:
#0 /share/htdocs/auth-ajax.php(11): unam_lib->unam_dbSelect()
#1 {main}
  thrown in /share/htdocs/__UNAM_LIB/unam_lib.php on line 31

please let me know

**Comment by UnamSanctam** [comment]
Looks like it can't connect to the database.

**Comment by zaromarco** [comment]
hmmm these are the file in the htdocs:
![immagine](https://user-images.githubusercontent.com/13431840/147985757-4bbc7689-c0b4-4b9f-8fdf-3fb7c8a52fb2.png)

**Comment by UnamSanctam** [comment]
I would guess unamwebpanel.db needs 755 permissions.

**Comment by zaromarco** [comment]
setup 755 but no luck...

**Comment by UnamSanctam** [comment]
Can you show a screenshot?

**Comment by zaromarco** [comment]
this is the config.php:
<?php
/* Made by Unam Sanctam https://github.com/UnamSanctam */
$config = [];

$config['password'] = 'test1234';

/*
 * If your web server uses Apache then there is no need to
 * change the db file location since the .htaccess file
 * will protect the database file from being accessed.
 * 
 * You can test if you are vulnerable by trying to access
 * WEBSITEURL/unamwebpanel.db (replace WEBSITEURL with your URL),
 * if it returns a 403 Forbidden error then you are protected
 */
$config['db_file'] = dirname(__FILE__)."/unamwebpanel.db";

$config['failedlogin_blocktime'] = 15;
$config['failedlogin_blocktries'] = 5;

$config['api_minreportime'] = 50;

$config['languages'] = ['en', 'sv'];

$config['unam_version'] = "1.3";

global $config;

**Comment by zaromarco** [comment]
[configphp.txt](https://github.com/UnamSanctam/UnamWebPanel/files/7804445/configphp.txt)

**Comment by zaromarco** [comment]
this is the structure of the file and dirs:
![immagine](https://user-images.githubusercontent.com/13431840/147989646-709457fa-d16d-4287-ac4b-0f959e865c0d.png)

**Comment by zaromarco** [comment]
this is the screenshot taken after insert a password:
![immagine](https://user-images.githubusercontent.com/13431840/147989704-f687c142-d445-4d97-b9ec-cd75823e2608.png)

**Comment by UnamSanctam** [comment]
Make sure that the htdocs folder itself also has the correct permissions, but other than that I would otherwise try to temporarily set the unamwebpanel.db permissions to 777 to see if that has anything to do with it.

**Comment by zaromarco** [comment]
with 777 on db file same error

**Comment by zaromarco** [comment]
i gave up with the try to host webpanel on rpi4 and hass.io + apache and php
i used a free apache + php hosting and everythings is ok
