### ISSUE TITLE
whats the meaning of configurations panel?

### ISSUE THREAD

**Issue by zaromarco** [UnamSanctam/UnamWebPanel#45]
as written:
![image](https://user-images.githubusercontent.com/13431840/148090835-2e0c4234-3608-441e-abb0-d81fd1001333.png)

**Comment by UnamSanctam** [comment]
You can enter the same type of miner settings configuration as the "Remote Configuration" (https://github.com/UnamSanctam/SilentCryptoMiner/wiki/ETH-Miner#remote-configuration for ethminer and https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration for xmrig) there and then apply that configuration to a miner in the list.

**Comment by zaromarco** [comment]
ah ok , so this is a more granular way than pastebin where you have only
one config for all silent miner....with pastebin you need to have multiple
paste but you need to build each silent miner with the correct url to that
paste...

Il giorno mar 4 gen 2022 alle ore 20:57 UnamSanctam <
***@***.***> ha scritto:

**Comment by UnamSanctam** [comment]
Yes exactly, it's a more dynamic way to change the configurations compared to the "Remote Configuration".

**Comment by zaromarco** [comment]
sorry forgot to ask these more technical questions:
if in the build i setup all the paramenters and in remote configuration for example i setup a pastebin url , when the new parameters are loaded ? at restart of the .exe or the miner check every x that url?
And these new parameters are saved locally in the pc where miner run or not? because if these are only in ram , if next time pc reboot and for some reason the remote configuration url is not reachable (server down) miner will use the original parameters which maybe are no more valid , for example wallet address.
Second question: if in the build i setup all parameters and in remote configuration a pastebin url and then in the web panel i create a new json configuration associated to a specific miner , which one will be prioritized ? i mean if remote configuration url and config from web panel are routinely checked and these configuration contains diferent parameters i get a continuous change of the paramaters

**Comment by UnamSanctam** [comment]
The "Remote Configuration" settings are loaded on every start and every 100 minutes after that. The settings are only saved in memory and will be reset to the compiled settings at the start of the miner. You can enter any amount of "Remote Configuration" backup URLs into the miner though with a comma (,).

The web panel has a higher authority than the "Remote Configurations" so it will prioritize the settings from the web panel.
