### ISSUE TITLE
required class panel missing

### ISSUE THREAD

**Issue by Aquazarine** [UnamSanctam/UnamWebPanel#46]
Tried to set up the panel, pretty sure I set it up right but when I go to the site I just get "The required class PDO could not be found. " 
not sure what I could do about this help would be appreciated thanks.

**Comment by UnamSanctam** [comment]
I would guess your PHP version is too old, see if you can change it to PHP 7.4 or PHP 8.

**Comment by Aquazarine** [comment]
I'm on php8 using FreeBSD for the OS and "Caddyserver" has the webserver, I can't really see why it isn't working should I be using something like apache or similar?

**Comment by UnamSanctam** [comment]
I would guess that your PHP doesn't have the PDO driver in it, you'd have to find how to get that for your specific version.

**Comment by Aquazarine** [comment]
Hey, I've managed to add the driver but now I'm just getting a blank page, it might just be the permissions but I didn't think that it needed perms other than just what there was there (rx) to display is there something I didn't do right here or~

**Comment by Aquazarine** [comment]
Spent a bit more time working on it, even switched to apache to see if that would work better and now i'm getting this error:

`PHP Fatal error:  Uncaught Error: Call to undefined function session_status() in /usr/local/www/apache24/data/class/class.base.php:7\nStack trace:\n#0 /usr/local/www/apache24/data/assets/php/session-header.php(3): require_once()\n#1 /usr/local/www/apache24/data/security.php(3): require_once('/usr/local/www/...')\n#2 /usr/local/www/apache24/data/index.php(3): require_once('/usr/local/www/...')\n#3 {main}\n  thrown in /usr/local/www/apache24/data/class/class.base.php on line 7`

**Comment by UnamSanctam** [comment]
Sounds like you have PHP 5.3 or earlier installed.

**Comment by Aquazarine** [comment]
php -v returns with php 8.0.13

**Comment by UnamSanctam** [comment]
Yes but the apache or the earlier webserver might use it's own PHP version. `session_status()` was added in PHP 5.4.

**Comment by Aquazarine** [comment]
I'll try to check but not sure where exactly I'd be looking for this

**Comment by UnamSanctam** [comment]
Create a PHP file containing `<?php phpinfo(); ?>` and open that page to see all the PHP information.

**Comment by Aquazarine** [comment]
did that and it looked fine, I also tried updating "Zend" or whichever and now I'm getting this instead:

`PHP Fatal error:  Uncaught Error: Undefined constant "FILTER_SANITIZE_STRING" in /usr/local/www/apache24/data/__UNAM_LIB/unam_lib.php:141\nStack trace:\n#0 /usr/local/www/apache24/data/assets/php/session-header.php(38): unam_lib->unam_filterAllParameters(10000)\n#1 /usr/local/www/apache24/data/security.php(3): require_once('/usr/local/www/...')\n#2 /usr/local/www/apache24/data/index.php(3): require_once('/usr/local/www/...')\n#3 {main}\n  thrown in /usr/local/www/apache24/data/__UNAM_LIB/unam_lib.php on line 141`

**Comment by Aquazarine** [comment]
Hey, wondering if you found anything or the such just am not sure what is going wrong here now so yeah help would be appreciated if you don't mind thanks either way though

**Comment by UnamSanctam** [comment]
No I haven't really seen that error before, did you follow a guide to set it all up or just winged it?

**Comment by Aquazarine** [comment]
Well I mostly did just wing it but all my php dependencies and such should be updated and working, I know with my caddy setup PHP works well so really I'm not sure what I could've done differently

**Comment by UnamSanctam** [comment]
Really weird, I've released a new version now but that shouldn't really change that, `FILTER_SANITIZE_STRING` has gotten deprecated as of PHP 8.1 (though you have 8.0) and even then it's still usable of course.

**Comment by Aquazarine** [comment]
Hey, yeah I tried the update and it seemed to have the same error, I'm not sure what I would've done wrong, is there anything you could think of that might cause this?

**Comment by Aquazarine** [comment]
Just got it fixed somehow thanks for your help with this really appreciate it!
