### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Demon4u** [UnamSanctam/UnamWebPanel#47]
Good afternoon. Such an error pops up and does not show anything in the panel. Maybe it's related to the number of users, I have about 500 of them? how to clear from inactive ones?

**Comment by UnamSanctam** [comment]
That can happen if some miner reports a null hashrate (though none technically shouldn't), it will be fixed in the next update but you can also reset the database as well (replace it with a new one) to fix it (or edit the database manually).

**Comment by UnamSanctam** [comment]
This has been "fixed" in the latest update now, so database "corruption" by null hashrates shouldn't exist now.

**Comment by Demon4u** [comment]
.
