### ISSUE TITLE
hash rate shown

### ISSUE THREAD

**Issue by zaromarco** [UnamSanctam/UnamWebPanel#48]
hi , i have install silent crypto miner to mine monero on moneroocean pool , in your webpanel i see this hash rate:
![immagine](https://user-images.githubusercontent.com/13431840/148644313-9adf3069-c8e1-49d6-a0a6-f0d00d80d801.png)

if i go to https://moneroocean.stream/ and i insert my monero wallet address i get the status of my mining rig but i get a much higher has rate shown:
![immagine](https://user-images.githubusercontent.com/13431840/148644340-55722738-ebdd-48da-aa42-1acfbb22c848.png)

the data is update at the same time but why i get this difference?

**Comment by UnamSanctam** [comment]
Pools calculate hashrate entirely differently from the actual miners so to get the real hashrate you have to mine for a longer time to get a real average, how long have you been mining? After a while the pool hashrate should average out to become the same as the hashrate shown in the web panel.

**Comment by zaromarco** [comment]
I've been mining from December 20th

**Comment by UnamSanctam** [comment]
The web panel shows the average hashrate over like 30 seconds while MoneroOcean shows the average hashrate over 23 hours so if you have "Idle Mining" enabled with a higher Idle CPU then that would also explain it since the pool will average that as well.

**Comment by zaromarco** [comment]
Before taking the screenshot I refresh both and moneroocean says 30 secs ago
I setup mining on idle but I set 2 min of idle and that laptop was not doing nothing else and no one is using it

**Comment by UnamSanctam** [comment]
Check your screenshot, it says "Avg 23 Hrs" underneath the hashrate. The hashrate in the web panel is more accurate than the pool (for obvious reasons) so it's better to use that to know the current hashrate while it's sometimes better to use the pool hashrate to know the average hashrate over a long period of time.

**Comment by zaromarco** [comment]
I was looking at the hash rate in the upper right corner (998,22) which is related to 27 seconds ago
I'm not referring to the avg but to the instantaneous hash rate which I suppose is what I'm compareing to hash rate in the web panel

**Comment by UnamSanctam** [comment]
That shows when the last share was submitted, the only hashrate shown is the average of course.

**Comment by zaromarco** [comment]
ok
