### ISSUE TITLE
Possibility to have another column

### ISSUE THREAD

**Issue by zaromarco** [UnamSanctam/UnamWebPanel#49]
Hi , will it be possible to have a new column in the table shown with the miners?
imagine you have tons of pc , the unique id is not sufficient to instantly find which computer is which , instead with a new column called "Computer Name" will be very usefull

**Comment by UnamSanctam** [comment]
It's already there if you press the '+', the table gets compressed down because your screen isn't big enough to contain all the data, you can zoom out a lot to see all the data without expanding it.

**Comment by zaromarco** [comment]
i see but i need to press ctrl+ many times to see and when i see it , is in the very right part of the screen and with a font very very little.....could be usefull if that column will be the second from the left so is visible immediately

**Comment by zaromarco** [comment]
Just to be sure , I need to modify that php file , changing the order of the column written ?
