### ISSUE TITLE
my site does not work

### ISSUE THREAD

**Issue by law228** [UnamSanctam/UnamWebPanel#5]
hello, my site does not work, I did everything correctly and uploaded it to public_html. But the site doesn't work

**Comment by UnamSanctam** [comment]
Going to need more information than that, what happens when you visit the site? What PHP version are you using?

**Comment by law228** [comment]
php version 7.1 
when I go to the site writes
This page is currently down. Site xxxxxxxxxxx is currently unable to process this request.
HTTP ERROR 500

**Comment by UnamSanctam** [comment]
Hmm, can you try with a higher PHP version? Not sure which host you use but it might also generate an error.log somewhere in the site files.

**Comment by Brainshot** [comment]
> 
> 
> php version 7.1 when I go to the site writes This page is currently down. Site xxxxxxxxxxx is currently unable to process this request. HTTP ERROR 500

go up 8.0 php or higher or else it wont work
