### ISSUE TITLE
New update works on first-time page load, subsequent actions break the panel similar to last update

### ISSUE THREAD

**Issue by Lanikai-B** [UnamSanctam/UnamWebPanel#53]
Hey Unam. I updated the webpanel and initially it looked like a success, as miners were populating the list. However, when I tried to switch the number of miners listed from 5 to All, I got a similar looking error to the previous update: 
![4ynvF6Nqh3](https://user-images.githubusercontent.com/95944334/148875377-f527cf98-b541-4a73-86ba-80fd01adbeac.png)

Upon trying to refresh the page, nothing loaded.
![ZJNPvJ0tao](https://user-images.githubusercontent.com/95944334/148875415-4cd1af1d-f398-4141-bf7d-0dc421dbcd3f.png)

Any ideas? The behavior repeats upon a reinstallation of the panel. Thanks!

**Comment by UnamSanctam** [comment]
Hmm, can you send the unamwebpanel.db (database) here?

**Comment by Lanikai-B** [comment]
[unamwebpanel.zip](https://github.com/UnamSanctam/UnamWebPanel/files/7843456/unamwebpanel.zip)

It should be noted that the miners haven't been updated yet, if that makes an impact.

**Comment by UnamSanctam** [comment]
Aha I found the problem, while the database now supports null hashrates the hashrate formatting doesn't.

**Comment by Lanikai-B** [comment]
Any idea why a miner would be having a null hashrate in the first place? Is it outputting data incorrectly, or is the whole miner idle/inactive? Using the checker, the miner does seem to be installed correctly. 

Cool to hear you found the issue. If you have an update, I'm free to test it on my system

**Comment by Lanikai-B** [comment]
Hm. Well, let's get the web panel working first and then I can see if I need to make an issue post over in the silent miner's page. Because some XMR miners are definitely running, so if any are still reporting null hashrates I'll certainly have to look further into it
