### ISSUE TITLE
how I improve the panel while keeping the cryptominer data

### ISSUE THREAD

**Issue by KAMLEGENDZ** [UnamSanctam/UnamWebPanel#54]

**Comment by UnamSanctam** [comment]
The endpoint.php is what accepts the miner data, it then inserts it into the database. The database can then be read however you want and manipulated in any way freely.

**Comment by KAMLEGENDZ** [comment]
where is the database

**Comment by UnamSanctam** [comment]
The file unamwebpanel.db.

**Comment by KAMLEGENDZ** [comment]
thx
