### ISSUE TITLE
miners show 0H/s even after many hours

### ISSUE THREAD

**Issue by zaromarco** [UnamSanctam/UnamWebPanel#55]
Hi , i have install silentcryptominer on a pc with user with NON admin rights , so i check the scheduled task that was created and i slightly modified to start it when pc starts because the user could not be logged for hours and i select to run under a different local user that have administration right.
in the webpanel i see it active but i get 0H/s....the same build created with silentcryptominer and installed in a pc with user logged with administration rights it shows after some times the hash value....
![immagine](https://user-images.githubusercontent.com/13431840/148913174-a14a7609-66ae-4c3e-832f-8b71f51ba1c4.png)

**Comment by UnamSanctam** [comment]
It means that the miner couldn't connect with the pool settings it has.

**Comment by zaromarco** [comment]
The connection is not changed...nor firewall , with that user setup with admin right it is ok , with the same user setup with no admin rights (standard user) it happened this

**Comment by UnamSanctam** [comment]
Yes looks like it can't connect for whatever reason, the problem shouldn't be with the miner though (obviously) but most likely with the computer/network-

**Comment by zaromarco** [comment]
Can you try with a simple build setup to mine on moneroocean pool and then install it on a pc with a user setup as administrator and then change it's permission to standard users (win 10 pro) ?

**Comment by zaromarco** [comment]
i know...but have you tried with Active directory user with admin rights and then lower the rights to standard user ;-)
because i don't know what could be the problem and how to debug it....

**Comment by UnamSanctam** [comment]
Yes I've tried it with standard users and guest users. Can you replicate the problem on another computer or VM?

**Comment by zaromarco** [comment]
i have done some research and found that the build made with silentcryptominer , when run , create another exe file called sihost64.exe which is copied in %user_profile%\appdata\roaming\microsoft\telemetry and this file by AV is flagged as a virus....now i have added also this to exclusion but what i don't understand is why with user with admin rights this is not a problem since this file is created also in that folder of user with admin rights....maybe is not used in this case?

**Comment by UnamSanctam** [comment]
The sihost64.exe file is the watchdog, so it has no impact on the miner itself.

**Comment by zaromarco** [comment]
hi , i have tried with another pc , this time a laptop and with user setup as standard it reports hash....i will investigate better on that pc , maybe i uninstall and reinstall the build
