### ISSUE TITLE
Datatables issue

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/UnamWebPanel#56]
i even redownloaded and changed the unamwebpanel.db and it still shows me the same error

![cxyxsaxq](https://user-images.githubusercontent.com/93741208/149021260-aff60f0e-8af2-4535-9130-dbd39cbe8fd1.PNG)

**Comment by UnamSanctam** [comment]
Does your web panel say Version 1.4.1 in the bottom right corner?

**Comment by Brainshot** [comment]
> Does your web panel say Version 1.4.1 in the bottom right corner?

Version 1.4

**Comment by UnamSanctam** [comment]
Then download the new version that has that fixed, the hashrate formatting function also had to be fixed.

**Comment by Brainshot** [comment]
> Then download the new version that has that fixed, the hashrate formatting function also had to be fixed.

Yeah its weird, i had replaced the things but it wasnt updated. i am gonna try again redownload things
