### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by Milk8** [UnamSanctam/UnamWebPanel#59]
I assume its obv something im doing wrong, I am not seeing my own pc pop up on the web panel? The miner is 100% running can see it on task manager and the checker, im hosting the panel locally so I should just paste my ipv4 as the site name? I assume I fucked up with the site name but idk how

**Comment by UnamSanctam** [comment]
If you're hosting it locally on the same computer then just do 127.0.0.1 as the IP, you can't access your own computer from your external IP.

**Comment by Milk8** [comment]
Local ip will work even if im having other people run it aswell? I'm trying that now

**Comment by UnamSanctam** [comment]
No the local IP will only work for you locally, to test if you can connect from outside you need to test it on another computer that uses another network (or a VPN).

**Comment by Milk8** [comment]
Yes im aware, but what should I put for the link if I want others to be able to show up on the panel? I take it thats impossible if im locally hosting it?
Also I still never showed up on the panel with 127.0.0.1, does it take 30 min to come up?

**Comment by UnamSanctam** [comment]
For external connections you can put your IPv4 there if the port 80 (or 443 for SSL/HTTPS) is port forwarded but you would be exposing your IP.

Did you enter `http://127.0.0.1/api/endpoint.php` into the "API Endpoint URL"?

**Comment by Milk8** [comment]
Yes, exactly that

**Comment by Milk8** [comment]
![image](https://user-images.githubusercontent.com/77039660/149063854-3fe0f67f-1ff0-4cc8-8b2e-c4a5c1b81866.png)

**Comment by UnamSanctam** [comment]
Are you hosting it on the same computer as you're running the miner (not in a VM or anything like that)? And if you go to `http://127.0.0.1/api/endpoint.php` in the browser does it display a page (should say something like "Error: Invalid Data" if it's working).

**Comment by Milk8** [comment]
It says the url was not found when put in browser, so thats the problem
and yes

**Comment by UnamSanctam** [comment]
How do you visit the panel normally?

**Comment by Milk8** [comment]
using http://localhost/panel/       would I use localhost as the name then?

**Comment by Milk8** [comment]
I'm using xamp and "panel" is the folder in htdocs that contains the source

**Comment by UnamSanctam** [comment]
localhost and 127.0.0.1 are technically the same, but since you use a subfolder called panel the URL would be `http://127.0.0.1/panel/api/endpoint.php`

**Comment by Milk8** [comment]
Made a new build with that, its been a min and still nothing

**Comment by Milk8** [comment]
Nevermind, it just showed up
Thanks for the help, so i'd be better off not locally hosting it I take it
