### ISSUE TITLE
SQLite PDO driver IS NOT enabled

### ISSUE THREAD

**Issue by steeeeefan** [UnamSanctam/UnamWebPanel#61]
Hi,

when i open myserver/index.php than i have a error "The required SQLite PDO driver IS NOT enabled.".

My System:
I have install apache on a debian Linux. I have copy the files in /var/www/html.

**Comment by UnamSanctam** [comment]
Update your PHP, the SQLite driver should automatically get downloaded with PHP, you can also try `sudo apt-get install php-sqlite3`

**Comment by steeeeefan** [comment]
oh nice, thank you very much. It is fine now.
