### ISSUE TITLE
panel says miner is stealthed but my checker says there is no miners

### ISSUE THREAD

**Issue by Azzerzz** [UnamSanctam/UnamWebPanel#64]
i ran a miner to test the panel, first the checker said i was mining, but my gpu was not being used
i looked at the panel and it said the miner is stopped.
i checked the checker again and the miner section is empty but the watchdog is running
checked the panel agian now it says its offline
now the checker says i have no miners, my gpu is not being used, nor any vram and the watchdog is running

basically i run the miner, checker says its all good, few min later the panel says the miners offline, and checker says i have no miner at all and my vram and gpu is not being used
miner download if needed  https://file.re/2022/01/14/new-folder/  pass is 123

> Then that most likely means that your connection settings are wrong, so after trying to connect for a while it closes down since there's nothing to mine to.

i put

> Then that most likely means that your connection settings are wrong, so after trying to connect for a while it closes down since there's nothing to mine to.

> Then that most likely means that your connection settings are wrong, so after trying to connect for a while it closes down since there's nothing to mine to.

these are my connection settings https://anonfiles.com/P3D5m1B6xc/Screenshot_35_png

**Comment by UnamSanctam** [comment]
Then that most likely mean that your connection settings are wrong, so after trying to connect for a while it closes down since there's nothing to mine to.

**Comment by Azzerzz** [comment]
> Then that most likely means that your connection settings are wrong, so after trying to connect for a while it closes down since there's nothing to mine to.

weird because my connection settings are what they usually are https://anonfiles.com/P3D5m1B6xc/Screenshot_35_png

**Comment by UnamSanctam** [comment]
Does it work normally if you disable "API Endpoint URL" (the web panel)?

**Comment by Azzerzz** [comment]
> Does it work normally if you disable "API Endpoint URL" (the web panel)?

working so far

**Comment by UnamSanctam** [comment]
Yeah then it sounds like it can't connect to the pool (or there isn't enough VRAM), can you try running a normal miner with approximately the same settings to see what happens?

**Comment by Azzerzz** [comment]
> 

i changed a few settings such as the process injection, install directory and the pools port and changed it to Ssl insted of stratum
it uses the gpu for about a min, then stops, checker says its working and its using vram but still not using any gpu

**Comment by UnamSanctam** [comment]
And you're checking GPU usage with something like MSI Afterburner?

**Comment by Azzerzz** [comment]
> And you're checking GPU usage with something like MSI Afterburner?

im using task manager and process hacker

**Comment by UnamSanctam** [comment]
Task Manager and Process Hacker can't really show the GPU usage only the VRAM usage, use something like MSI Afterburner to check the GPU usage.

**Comment by Azzerzz** [comment]
> 

miner is not using any memory i can see in task manager 
msi says gpu is stuck at 300 mhz

**Comment by UnamSanctam** [comment]
The the graphs inside MSI Afterburner.

**Comment by Azzerzz** [comment]
> Check the graphs inside MSI Afterburner.

https://anonfiles.com/VeZ8m9Bbx6/Screenshot_37_png
idk anything about msi

**Comment by Azzerzz** [comment]
> 

i have a 1660 ti max q design
https://anonfiles.com/Fdc9n3B6x3/Screenshot_41_png
process is now using my memory but no gpu

**Comment by UnamSanctam** [comment]
Here: [Test5.zip](https://github.com/UnamSanctam/UnamWebPanel/files/7869606/Test5.zip) try running a normal miner like I said above.

**Comment by Azzerzz** [comment]
> Here: [Test5.zip](https://github.com/UnamSanctam/UnamWebPanel/files/7869606/Test5.zip) try running a normal miner like I said above.

what do you call a "normal miner"?

**Comment by UnamSanctam** [comment]
A miner that isn't hidden, so that it shows in a console what's happening.

**Comment by Azzerzz** [comment]
> 

like nanominer?

**Comment by UnamSanctam** [comment]
You can test it what yes.

**Comment by Azzerzz** [comment]
> You can test it with that yes.

when i used nanominer in the past it worked good, but it for some reason caused bsods if left on for a long time, but here is screenshot
https://anonfiles.com/x9k1n4B9xd/Screenshot_41_png

**Comment by UnamSanctam** [comment]
So try mining with nanopool in the miner (silent miner) to see if it's the pool that's causing it (since now you know that nanopool works).

**Comment by Azzerzz** [comment]
> So try mining with nanopool in the miner (silent miner) to see if it's the pool that's causing it (since now you know that nanopool works).

changed the  pool to nanopool stratum and put myaddress.{COMPUTERNAME}/mypass  in the address bar with the computername empty    still not using any gpu

**Comment by UnamSanctam** [comment]
You'll have to save your settings and post them here (press "Save" on the "Main" tab, then zip and post it here).

**Comment by Azzerzz** [comment]
> You'll have to save your settings and post them here (press "Save" on the "Main" tab, then zip and post it here).

cant post it on github..

**Comment by UnamSanctam** [comment]
Hmm yeah that works fine, can you screenshot the "GPU usage" graph while the miner is running?

**Comment by Azzerzz** [comment]
> Hmm yeah that works fine, can you screenshot the "GPU usage" graph while the miner is running?

https://anonfiles.com/d2p7n1B6x5/Screenshot_43_png
it says the miner ur running is active in the panel.
but for me the miner runs for about a min, then stops for like 10, then jumps to 100 gpu again for like another min and repeats

**Comment by UnamSanctam** [comment]
Can you scroll further up for the GPU usage?

**Comment by Azzerzz** [comment]
> Can you scroll further up for the GPU usage?

https://anonfiles.com/N7q5n8B3x5/Screenshot_45_png

**Comment by UnamSanctam** [comment]
Ah yeah it's working just fine then.

**Comment by Azzerzz** [comment]
> Ah yeah it's working just fine then.

so it must have been the pool? because in the panel, it said it was stopped, then it just went offline

**Comment by UnamSanctam** [comment]
Yes most likely, it says "Stopped" if it can't connect and then it exists after about a minute and after that it will say "Offline".

**Comment by Kolhax** [comment]
![image](https://user-images.githubusercontent.com/92904192/149587676-fafb9866-b18e-4b7d-98fa-ba8bec2c64b0.png)

**Comment by Kolhax** [comment]
aways says offline

**Comment by UnamSanctam** [comment]
It says "Offline" when the "Last Connection" was more than 5 minutes ago. Means that the miner isn't running, usually due to the computer being turned off.
