### ISSUE TITLE
last connection time information

### ISSUE THREAD

**Issue by zaromarco** [UnamSanctam/UnamWebPanel#65]
Hi , time shown in last connection time column , is in UTC time ? i'm asking because all connection shown -1 hours than mine
is it possible to show the correct time?

**Comment by UnamSanctam** [comment]
Yes it's in standard time, to change it automatically client-side is actually quite a heavy process, such as using moments.js or something but I can put it on my todo. You can also just change the timezone in the PHP, just add this function into config.php: https://www.php.net/manual/en/function.date-default-timezone-set.php

**Comment by zaromarco** [comment]
thank's , i'm not a php sw engineer but reading that page can i insert in the config.php a line like this before global $config;
date_default_timezone_set('Europe/Rome');
and automatically time will be adjusted?

**Comment by UnamSanctam** [comment]
Yes exactly, just paste it somewhere into config.php (anywhere beneath <?php).

**Comment by zaromarco** [comment]
ok it works
