### ISSUE TITLE
Anyway to get the config in a raw format?

### ISSUE THREAD

**Issue by dingodingo2** [UnamSanctam/UnamWebPanel#66]
Is there anyway to get for example the default xmr config in a raw format (for remote config)? And if yes how often does the silent miner check the config? Thanks :)

**Comment by UnamSanctam** [comment]
Here's an example configuration: https://github.com/UnamSanctam/SilentCryptoMiner/wiki/XMR-Miner#remote-configuration if that's what you want. The miner checks the "Configuration" in the web panel every minute (when it contacts the web panel to give the status), and the normal "Remote Configuration" gets checked at start and then every 100 minutes after that.

**Comment by dingodingo2** [comment]
Hum. Thats strange. At the beginning I tried with "user" and then I saw that the option was named "wallet". So I tried here is my config : https://i.imgur.com/dXUS2AW.png but it doesn't seem to affect the miner (and he is linked)

**Comment by UnamSanctam** [comment]
You need at least a pool, port and wallet address (since it adds a new connection).

**Comment by dingodingo2** [comment]
So I added the pool and the port

`{"pool": "xmr-eu1.nanopool.org","port": 14444,"wallet": "mywallet"}`

But still, it doesn't update... Any idea?

**Comment by UnamSanctam** [comment]
That should work but nanopool is also quite passive in their connection (meaning that the connection is a bit ambiguous). I would try another pool like 2miners just to check.

**Comment by dingodingo2** [comment]
Oh so it works... Hum that's strange. I'm going to try again with nanopool. Thanks

**Comment by dingodingo2** [comment]
Smh. I really can't get it to work with nanopool.

**Comment by dingodingo2** [comment]
Do you have anyway of making it work with nanopool? I don't get what is the issue :(

**Comment by UnamSanctam** [comment]
Issue is probably just how nanopool works, you can try adding `"algo": "rx/0"`

**Comment by dingodingo2** [comment]
Thanks this fixed the issue :)
