### ISSUE TITLE
Increase the number of row

### ISSUE THREAD

**Issue by zaromarco** [UnamSanctam/UnamWebPanel#69]
Is it possible to increase the number of row? I have many device and in one page are shown only 5 leaving my 24 inches display with plenty of space for the rest of the page

**Comment by UnamSanctam** [comment]
Yes there's a "Show X Entries" at the top of the table.

**Comment by zaromarco** [comment]
I mean to show all entry by default and not selecting show x entries each time
I prefer to vertically scroll than click on next (especially on smartphones)

**Comment by UnamSanctam** [comment]
If you select "Show All Entries" then it will stay that way.

**Comment by zaromarco** [comment]
But not across devices and if you clear the cache it come back to 5

**Comment by UnamSanctam** [comment]
Well yeah but it's two clicks per device which will stay that way until you clear the cache.

**Comment by zaromarco** [comment]
....ok

**Comment by zaromarco** [comment]
Hi , i don't know why but every day i need to select to show all entries and to order the miners from first to last...i never clean cache of browser or other....i'm talking about windows pc with firefox

**Comment by UnamSanctam** [comment]
Yes datatables by default expires the "cookies" two hours after the datatables has last been used. https://datatables.net/reference/option/stateDuration.

You can go into https://github.com/UnamSanctam/UnamWebPanel/blob/e77456f9a54e8abccc435ec0107c16b07c706ef6/UnamWebPanel/index.php#L147 and add `stateDuration: 0,` on the line below that and it should never expire.

**Comment by zaromarco** [comment]
yes it works
thank's
