### ISSUE TITLE
impossible to delete a configuration done with a previous version

### ISSUE THREAD

**Issue by zaromarco** [UnamSanctam/UnamWebPanel#72]
Hi , i have done a configuration named test in webpanel v1.3 , then i have upgraded to v1.4.1 , as you can see i cannot delete it because remove button is not enabled.
if i select another configuration made with v1.4.1 that button is enabled
![immagine](https://user-images.githubusercontent.com/13431840/150425825-f9811ec4-e2c7-4168-b1f8-2f7a3e1e2aa5.png)

![immagine](https://user-images.githubusercontent.com/13431840/150426006-69f061c4-3ca2-488a-9903-210b2b291c3e.png)

**Comment by UnamSanctam** [comment]
Because "Default ethminer" should be the second one (not removable), it's because you haven't updated the database.

**Comment by zaromarco** [comment]
when i upgrade to v1.4.1 i just copied over the new files downloaded from github except the .db , how to upgrade the db?

**Comment by UnamSanctam** [comment]
If you don't want to manually move over all the data then you can just replace it, any miner that connects will just reappear.

**Comment by zaromarco** [comment]
do you mean delete the .db and copy the one that comes with v1.4.1 and reapply the conf to the miner ?

**Comment by UnamSanctam** [comment]
Yes exactly, save down your configurations somewhere first (some text documents) and then just re-add them after you've replaced the database. You can backup (copy somewhere safe) your old db first in case you forget to copy over something.

**Comment by zaromarco** [comment]
but this means that this operation must be done everytime there will be an upgrade?

**Comment by UnamSanctam** [comment]
Of course, unless you migrate the data yourself.

**Comment by zaromarco** [comment]
ok done
