### ISSUE TITLE
hey, auth help pls

### ISSUE THREAD

**Issue by monerrrr123** [UnamSanctam/UnamWebPanel#75]
how can I delete authorization? so that when opening it immediately shows miners?

**Comment by UnamSanctam** [comment]
Why would you ever want that? Then anyone that sniffs the traffic to find the URL can change your miners.

**Comment by monerrrr123** [comment]
> Why would you ever want that? Then anyone that sniffs the traffic to find the URL can change your miners.

please tell me, I need this for writing my software for personal use

**Comment by UnamSanctam** [comment]
I guess you'd have to remove the `require('security.php')`; in every file that has it.

**Comment by monerrrr123** [comment]
![image](https://user-images.githubusercontent.com/98605999/151606760-6ba07063-0951-4584-8ea5-dae2c9a75a8c.png)

**Comment by UnamSanctam** [comment]
Check the error logs, though I'd recommend learning PHP before messing around with things.

**Comment by monerrrr123** [comment]
> Check the error logs but most likely you didn't remove it from EVERY file, though I'd recommend learning PHP before messing around with things.

 references to security.php deleted...
![image](https://user-images.githubusercontent.com/98605999/151608218-75d06d91-96bd-4576-9e2f-2b9eebf29220.png)

**Comment by UnamSanctam** [comment]
Yes there's an error, so check any error.log files you have in any folder or check __UNAM_LIB\Logs for any error files there.

**Comment by monerrrr123** [comment]
> Yes there's an error, so check any error.log files you have in any folder or check __UNAM_LIB\Logs for any error files there.

error.log clear, Logs dont have files there

**Comment by UnamSanctam** [comment]
Where are you hosting it, are all the file and folder permissions correct to allow error files to be written?

**Comment by monerrrr123** [comment]
> Where are you hosting it, are all the file and folder permissions correct to allow error files to be written?

of course!

**Comment by UnamSanctam** [comment]
Then you might have to place `require_once 'assets/php/session-header.php';` where all the requires for security.php were before.

**Comment by monerrrr123** [comment]
> Then you might have to place `require_once 'assets/php/session-header.php';` where all the requires for security.php were before. Or place back security.php in all the files but remove all the code except the top line inside security.php.

WORK!!!! THANKS!!!!!
