### ISSUE TITLE
 [BACKDORED ???] SECURITY REQUEST

### ISSUE THREAD

**Issue by FireHack7z** [UnamSanctam/UnamWebPanel#77]
When it's free, you are the product.
the "miner" is not open source,
you've found a billion excuses not to post this one.

you may have put your own hidden miner in the bin.

how to check this? (this is necessarily verifiable.)

**Comment by UnamSanctam** [comment]
Well you know there's no hidden miner since it's not mining twice because then it would be using twice the resources if that's what you mean.

**Comment by UnamSanctam** [comment]
And you can also see what it's mining to and the hashrate it has in the web panel.
