### ISSUE TITLE
Can't see my miner on the webpanel

### ISSUE THREAD

**Issue by ProMate04** [UnamSanctam/UnamWebPanel#79]
My miner is running on another machine, mining XMR on the SupportXMR pool. The pool shows that it is indeed mining. However, in the miner settings, the webpanel is also configured, but it is not working, no matter what I try.

My webpage is running on my home Synology NAS, using Apache 2.4 and Php 7.4. I can access the Panel from outside of my network, port forwarding works aswell, and double checked that I can write to the database file, yet nothing. 

I have also tried using the Remote Config feature in the miner, and added "api-endpoint" to the config, but nothing changed.

The config: 
{
    "algo": "rx/0",
    "pool": "pool.supportxmr.com",
    "port": 5555,
    "wallet": "4AvGE6NxeCfd9c9NMCuQnQ4ZCo8cJ9SGY5B-----MY_WALLET_ADDRESS-----6Yvj7iFfGc5JSVbdAqn1DAToVfh1N7p3qH",
    "password": "Worker1",
    "nicehash": false,
    "ssltls": false,
    "max-cpu": 70,
    "idle-wait": 1,
    "idle-cpu": 100,
    "stealth-targets": "Taskmgr.exe,ProcessHacker.exe,perfmon.exe,procexp.exe,procexp64.exe",
    "kill-targets": "",
    "api-endpoint": "http://MY_ACTUAL_DOMAIN.ddns.net/api/endpoint.php"
}

I don't know what else I could do, I really hope you could help me, thank you in advance!

**Comment by UnamSanctam** [comment]
Does your username or computer name happen to be something other than alphanumeric characters?

**Comment by ProMate04** [comment]
Nope, both are all letters. 

I have tried the webpanel with 000webhosting, and it works, so something must be up with my network. Only thing i can think of is that it does not have SSL, but I don’t know if thats a problem.

Later today I’ll try to host it from my Raspberry pi and see if that works, I would rather not use a webhost service if I don’t have to

**Comment by UnamSanctam** [comment]
Make sure that the unamwebpanel.db has the required permissions, I'm pretty sure the minimum is 644.

**Comment by ProMate04** [comment]
Do I need to any other permissions to any file, or should the .db file be enough?
This is what I have configured right now for the database, the only thing that I could think of is that I have the ownership of the files, maybe I have to change that to the http group?

![82C8189A-30E5-4C16-B03E-37268116EEC3](https://user-images.githubusercontent.com/37308842/152293699-15fbaf19-36e1-48b3-b74a-04d593975d38.jpeg)

![717334E5-2EE5-4C9D-8999-A766C39A6AD7](https://user-images.githubusercontent.com/37308842/152294129-7728e3c3-8f08-49ad-a57c-0cab1fd9fb44.jpeg)

**Comment by UnamSanctam** [comment]
That should be enough, is the other machine you're mining from outside the network or not?

**Comment by ProMate04** [comment]
It’s not, it’s on my local network

**Comment by UnamSanctam** [comment]
Oh, are you then trying to connect to the web panel with the local IP? Since your external IP won't work.

**Comment by ProMate04** [comment]
I have a no-ip DNS set up for my network. Currently, because I had no other idea, port 80 is open to the wide web, and is redirected to the php server that is running on my nas. I am currently not home, and I can access it even from here, using this dynamic DNS. 
I have tried to put this domain into the miner into the api-endpoint filed, but it just wont show up. I also tried to enter the local IP of the NAS, since, yea, they are indeed on the same network. None of those options worked sadly.

**Comment by ProMate04** [comment]
I can access it externally, so I don’t know why the miner can’t
![639BB888-7497-432E-B0F1-698E19BEE6BD](https://user-images.githubusercontent.com/37308842/152296626-8e3a00db-6940-4aeb-a095-93f761492215.jpeg)

**Comment by UnamSanctam** [comment]
Yes the No-IP DNS will work from the outside of course but will never work when visited from your internal network, so using the internal IP should work just fine, for example I do `http://192.168.1.182/api/endpoint.php` when testing on my local network.

**Comment by ProMate04** [comment]
Yes, that also works when I’m home, and I can reach the Panel from the local IP aswell. But the miner can’t do so either way.
Only difference I’m seeing between your link is that you don’t have a port, because you use the default 80. Mine is like this:

http://192.168.2.125:8898/api/endpoint.php

Does that make a difference? Maybe the miner can’t interpret that?

**Comment by ProMate04** [comment]
Also, I don’t quite get why the DDNS would not work from the internal network?

**Comment by UnamSanctam** [comment]
No with a port should work, if you run a miner from an external network with the No-IP URL does it work? Either by using a computer on another network or by using something like a VPN on the computer you're mining on.

> Also, I don’t quite get why the DDNS would not work from the internal network?

Because it directs to your own network, you can't do that since that would require something like NAT hairpinning. You can read up more on how computer networks work if you're interested in it.

**Comment by ProMate04** [comment]
I am gonna test it to see if it works from an external network when I get home today, if all else fails, I’m gonna try to host it on my Raspberry pi instead. That way I’ll know if my network or ports are messed up, or if something is not correct on the NAS. Anyways, thank for all the help for now.

> Because it directs to your own network, you can't do that since that would require something like NAT hairpinning. You can read up more on how computer networks work if you're interested in it.

That is actually interesting, but it did load the webpanel on my internal network aswell when I tried to access it through my DDNS. I really don’t know much about networks, I don’t know if thats normal or not then….

**Comment by ProMate04** [comment]
All right, I am back home and I have tried to use the miner outside of the network, nothing changed. 

Currently I have one more idea, I want to try to run the weserver in a docker container. Only problem is that I have no clue how to do that...

**Comment by UnamSanctam** [comment]
Are you able to create new "Configurations" and save them? And are they then still there if you reload the page? Since then we know that you can write to the database at least. I know you said you added a configuration in the first post but just want to make sure.

**Comment by UnamSanctam** [comment]
Most likely yes, can you see it if you refresh the entire page? If no then most likely it can't write anything, are there any error.log files anywhere or are there any error files inside `__UNAM_LIB\Logs`?

**Comment by ProMate04** [comment]
Nope, just the dummy file.....

**Comment by ProMate04** [comment]
The config still does not show up if I refresh the page

**Comment by ProMate04** [comment]
I solved it, just gave r/w access for the http user for the entire folder.....Why did I not think that the reason that there are no logs is because it can't write anywhere, not just in the .db file? I feel extremely stupid.... Thank you so much for your patience and for your help!

**Comment by UnamSanctam** [comment]
Ah yeah that can be a problem haha, should've asked that first. Glad you got it working!
