### ISSUE TITLE
Updating the Panel

### ISSUE THREAD

**Issue by kinggskral** [UnamSanctam/UnamWebPanel#82]
I am using an older version of the panel. I have null hashrate error and i want to update the panel but how can I ? Can I just replace the new files with the old ones.

**Comment by UnamSanctam** [comment]
Yes if you replace all the files then when the miners connect they will just get re-added.

**Comment by kinggskral** [comment]
Thanks so it will be a nice clean up too. May I also ask how can I bypass windows defender? I am using obfuscators and crypters (which they are free). Do you have a good way to bypass defender?

**Comment by UnamSanctam** [comment]
Well using crypters and obfuscators are really the only way (unless you change the code yourself), you should probably also use "Bypass Windows Defender" if you aren't already just to bypass it after it's already been run, but a crypter/obfuscator will still be needed to make it undetected before it's run (as you probably know).
