### ISSUE TITLE
what is the proper API endpoint link to use

### ISSUE THREAD

**Issue by loadeddypper** [UnamSanctam/UnamWebPanel#84]
I managed to run the server I can't find anything in the docs that mentions the endpoint to use for the API, I exposed the web panel with ngork for testing but the miner does not show up in the panel, I used the link generated by ngrok

**Comment by UnamSanctam** [comment]
You can see it here: https://github.com/UnamSanctam/UnamWebPanel#setup, it should be `http://yourwebsite.com/api/endpoint.php`
