### ISSUE TITLE
Suggestion - Disable or Enable Mining of any connected Miner

### ISSUE THREAD

**Issue by ilikecatgirls** [UnamSanctam/UnamWebPanel#85]
just a suggestion for the web panel to be able to put the miner 'to sleep' and enable it when wanted

**Comment by UnamSanctam** [comment]
You could add `explorer.exe` into "stealth-targets" and it would pause the miner at all times.

**Comment by ilikecatgirls** [comment]
makes a lot of sense thank you will try
