### ISSUE TITLE
DataTables warning: table id=miner-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7

### ISSUE THREAD

**Issue by Soul6666** [UnamSanctam/UnamWebPanel#9]
![1](https://user-images.githubusercontent.com/48898053/141276323-9888d647-a433-4ab1-b43f-92d8b3a67be0.png)

**Comment by Soul6666** [comment]
> 确保您还上传了 unamwebpanel.db。

yes，But he can be downloaded.

**Comment by UnamSanctam** [comment]
It can be downloaded by everyone else? Like if you visit http://yoururl.com/unamwebpanel.db? That error is usually due to it not being able to find unamwebpanel.db (that database).

**Comment by Soul6666** [comment]
yes，Everyone can....

**Comment by UnamSanctam** [comment]
What host do you use? I provide "protection" files for both Apache and IIS but if you use any other sort server then you'll have to figure out how to do the same yourself with that server software. Or you can move the unamwebpanel.db out of the exposed webserver files and then change the .db location in the config.php file.

**Comment by Soul6666** [comment]
Nginx container。

**Comment by Soul6666** [comment]
> 你用什么主机？我为 Apache 和 IIS 提供了“保护”文件，但是如果您使用任何其他排序服务器，那么您必须弄清楚如何使用该服务器软件自己做同样的事情。或者您可以将 unamwebpanel.db 从暴露的网络服务器文件中移出，然后更改 config.php 文件中的 .db 位置。

Will it display the miners normally?

**Comment by Soul6666** [comment]
Will it display the miners normally?

**Comment by UnamSanctam** [comment]
> Nginx container

Ah yes then you'll have to limit access to that file in your Nginx configuration since I cannot provide any default files that works with Nginx (because Nginx doesn't operate in that way).

> Will it display the miners normally?

Yes as long as the PHP can find unamwebpanel.db then everything will work, you can set the location of unamwebpanel.db in the config.php, there is a configuration called $config['db_file'] there.

**Comment by Soul6666** [comment]
Thank you. Can the miners be displayed normally without "unamwebpanel. DB"

**Comment by UnamSanctam** [comment]
No because then there is no database to store the miner data.

**Comment by Soul6666** [comment]
I found that although he prompted this error, it can still be displayed normall
![2](https://user-images.githubusercontent.com/48898053/141292208-4ec1ba66-37a5-4618-a71d-ead94829cba9.png)
y

**Comment by UnamSanctam** [comment]
Clear your cache and reload it, does the error still appear? The datatables plugin will display that if the JSON is an incorrect format.

**Comment by Soul6666** [comment]
OK, if I already have miners working, will silent cryptominer still work? They are eth.

**Comment by UnamSanctam** [comment]
What do you mean? Which kind of miners, Silent ETH Miner?

**Comment by Soul6666** [comment]
yes，Add silent eth miners to the original eth miners

**Comment by UnamSanctam** [comment]
Sure but they would compete for the GPU just like any other program, if you want the Silent Crypto Miners ETH miner (that you add into the "Miners" list) to pause while the normal ETH miner is mining then you can add it into the "Stealth Targets".

**Comment by Soul6666** [comment]
No, I want to add the silent eth miners to the original eth miners and let them run together

**Comment by UnamSanctam** [comment]
If you start two miners at once then you need twice the VRAM (4.5GB*2=9GB for ETH) and can only use 50% on both (obviously). I'm not really sure what you're trying to accomplish.

**Comment by Soul6666** [comment]
Can you limit the silentethminer to 20% of the mining machine, because I have eight GPUs. How should I configure it? I want to add silentethminer to the 8gpu miner.

**Comment by UnamSanctam** [comment]
Yes you can set the "Max GPU" to 20%, but when you mine you need to store the entire DAG of that coin in the VRAM, so if you have one ETH miner then that is around 4.5GB of VRAM, if you have two miners then that is 9GB of VRAM, that is unavoidable since that is how the ethash algorithm (what Ethereum uses) works.

You can make it mine on only one GPU by adding that into the "Advanced Parameters", for example if you have 8 Nvidia GPUs you can make it mine on the first GPU by entering `--cu-devices=0` or make it mine on the 8th GPU by entering `--cu-devices=7`.

**Comment by Soul6666** [comment]
If so set, will only 7gpu be displayed in the original eth miner?

**Comment by Soul6666** [comment]
If 4gpu is set for the silent miner, how should it be set

**Comment by UnamSanctam** [comment]
You will have to disable that GPU in the original miner since otherwise both will mine on that GPU, if you want the 4th GPU in the silent miner then it would be --cu-devices=3, if you want 4 GPUs in the silent miner then it's `--cu-devices=0,1,2,3` (or any other order).

**Comment by Soul6666** [comment]
I'll try. You're really patient! Thank you very much.

**Comment by Brainshot** [comment]
@UnamSanctam i am getting this error now my webpanel was working perfectly fine but after refreshing some mins ago i get this error and cant see miners

**Comment by UnamSanctam** [comment]
> @UnamSanctam i am getting this error now my webpanel was working perfectly fine but after refreshing some mins ago i get this error and cant see miners

Try reloading it, all it means is that the data returned wasn't readable, usually means that it can't contact the database.

**Comment by Brainshot** [comment]
> 
> 
> > @UnamSanctam i am getting this error now my webpanel was working perfectly fine but after refreshing some mins ago i get this error and cant see miners
> 
> Try reloading it, all it means is that the data returned wasn't readable, usually means that it can't contact the database.

i reloaded it multiple times same error

**Comment by UnamSanctam** [comment]
You can check the __UNAM_LIB\Logs folder to see if there are any logs there, or you can check the response of custom-table.php in the browser network tab (in the console).

**Comment by Brainshot** [comment]
> 
> 
> You can check the __UNAM_LIB\Logs folder to see if there are any logs there, or you can check the response of custom-table.php in the browser network tab (in the console).

no logs

**Comment by Brainshot** [comment]
@UnamSanctam should i just redownload the unamwebpanel? since if miners reconnect they will be there on panel again

**Comment by UnamSanctam** [comment]
Can you backup you unamwebpanel.db first and then replace it with a clean one, in case it's the database.

**Comment by Brainshot** [comment]
> 
> 
> Can you backup your unamwebpanel.db first and then replace it with a clean one, in case it's the database. Could be some value from the miners that might make it stop working.

Yes it was database issue i just replaced and got getting back miners

**Comment by Brainshot** [comment]
as if too many miners crashes the database?

**Comment by UnamSanctam** [comment]
Ok good, haven't experienced that yet so I'm not sure what caused it then.
