### ISSUE TITLE
Miners are not displayed

### ISSUE THREAD

**Issue by 4SERGEEV** [UnamSanctam/UnamWebPanel#91]
Good afternoon, 
I've been looking at answers to similar questions all day, but nothing helps me. 
I tried several hosting, set all files and the parent folder - 777. The database is 777. 
On the page: %my_site%/wp/api/endpoint.php - Error: Invalid data. 
There are no errors in the __UNAM_LIB folder. 
In the Endpoint URL API program: http://%my_site%/wp/api/endpoint.php
Http is used

Please help me fix this

**Comment by UnamSanctam** [comment]
Maybe it forces https? You can try https://%my_site%/wp/api/endpoint.php

**Comment by 4SERGEEV** [comment]
> Может быть, это заставляет https? Вы можете попробовать https://%my_site%/wp/api/endpoint.php

I tried it. Unfortunately there is no result

**Comment by UnamSanctam** [comment]
Are you able to go to the "Configuration" tab and create a new configuration (and is it there when you refresh)?

**Comment by 4SERGEEV** [comment]
> Вы можете перейти на вкладку «Конфигурация» и создать новую конфигурацию (и она там при обновлении)?

The green window came out: Success

**Comment by UnamSanctam** [comment]
Ok then it's something on the server side most likely, what PHP version do you have? The site is just a PHP site so it can really be hosted anywhere and with anything.

**Comment by 4SERGEEV** [comment]
> Хорошо, тогда это что-то на стороне сервера, скорее всего, какая у вас версия PHP? Сайт - это просто сайт PHP, поэтому его действительно можно разместить где угодно и с чем угодно.

On the current hosting, PHP version: 7.4

**Comment by UnamSanctam** [comment]
I guess you'd have to log the traffic and see if it reaches the server. But is the computer name or the username of the mining computer written in Cyrillic or just normal alphanumeric?

**Comment by 4SERGEEV** [comment]
> Я думаю, вам придется регистрировать трафик и смотреть, доходит ли он до сервера. Но написано ли имя компьютера или имя пользователя компьютера для майнинга кириллицей или обычными буквами и цифрами?

![image](https://user-images.githubusercontent.com/100921809/158323118-b33ce280-95fd-4ed1-ac64-106041e7a910.png)

Проверьте пожалуйста, здесь все верно? Полный адрес: http://f0644404.xsph.ru/wp/api/endpoint.php

**Comment by UnamSanctam** [comment]
Hmm, only real thing I can think of is that the server might be blocking the miner traffic, do you host it somewhere or do you host it yourself?

**Comment by 4SERGEEV** [comment]
> Хм, единственная реальная вещь, о которой я могу думать, это то, что сервер может блокировать трафик майнера, вы размещаете его где-то или размещаете сами?

I have tried several hosting services:
000webhost
sprinthost

The web panel is not working
![image](https://user-images.githubusercontent.com/100921809/158377049-e20e5fbf-3ea3-4544-abaf-9c4d34b1cb8f.png)

**Comment by UnamSanctam** [comment]
It works fine on 000webhost, all you have to do there is put the PHP version at 7.4 or higher (it's 7.0 by default). Though they have a max limit of connections at 000webhost for the free version.

**Comment by 4SERGEEV** [comment]
> It works fine on 000webhost, all you have to do there is put the PHP version at 7.4 or higher (it's 7.0 by default). Though they have a max limit of connections at 000webhost for the free version.

Maybe I'm doing something wrong.
I have registered on another hosting. PHP version: https://cq63921.tmweb.ru/wp/info.php
I put 777 on unamwebpanel.db, index.php and /api/endpoint.php 
In the builder I put: https://cq63921.tmweb.ru/wp/api/endpoint.php

**Comment by UnamSanctam** [comment]
And can you create a new "Configuration" there? It's the easiest way to know if the database is writable, if it is writable then the reason the miner is not connecting is most likely the server or some setting thereof.

**Comment by 4SERGEEV** [comment]
> А можно создать там новую "Конфигурацию"? Это самый простой способ узнать, доступна ли база данных для записи, если она доступна для записи, то причина, по которой майнер не подключается, скорее всего, связана с сервером или какой-либо его настройкой.

Could it be because I'm using a virtual machine for a test?

**Comment by UnamSanctam** [comment]
Can you reach the endpoint.php inside your virtual machine? Then it shouldn't matter. You can also see the miner when running the checker program as well correct (and the endpoint URL is correct)?

**Comment by 4SERGEEV** [comment]
> Can you reach the endpoint.php webpage inside your virtual machine? Then it shouldn't matter. You can also see the miner when running the checker program as well correct (and the endpoint URL is correct)?

An error has appeared

`ERROR: <br/><b>Date and Time:</b> 2022/03/15 15:55:36<br/><b>In file:</b> /storage/ssd1/019/18613019/public_html/index.php<br/><b>On line:</b> 165<br/><b>Error was: </b> [2] Undefined array key "not_reversible"<br/><details><summary><b>Error context:</b></summary><p></p></details><br/><b>Remote IP:</b> 79.142.66.229<br/><b>Session Data:</b> {"csrf_token":"de0b1a163729aded5780d159ad90d00e774b6acd4427b5f27081f941a704ae44","lang":"en","logged_in":true,"HTTP_USER_AGENT":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/99.0.4844.51 Safari\/537.36"}<br/>Ending Script<hr /> <details><summary><b>Debug Trace: </b></summary><p>[{"file":"\/storage\/ssd1\/019\/18613019\/public_html\/index.php","line":165,"function":"unam_customErrorHandler","class":"unam_lib","object":{},"type":"->","args":[2,"Undefined array key \"not_reversible\"","\/storage\/ssd1\/019\/18613019\/public_html\/index.php",165]}]</p></details></br>ERROR: <br/><b>Date and Time:</b> 2022/03/15 15:55:39<br/><b>In file:</b> /storage/ssd1/019/18613019/public_html/index.php<br/><b>On line:</b> 165<br/><b>Error was: </b> [2] Undefined array key "not_reversible"<br/><details><summary><b>Error context:</b></summary><p></p></details><br/><b>Remote IP:</b> 79.142.66.229<br/><b>Session Data:</b> {"csrf_token":"de0b1a163729aded5780d159ad90d00e774b6acd4427b5f27081f941a704ae44","lang":"sv","logged_in":true,"HTTP_USER_AGENT":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/99.0.4844.51 Safari\/537.36"}<br/>Ending Script<hr /> <details><summary><b>Debug Trace: </b></summary><p>[{"file":"\/storage\/ssd1\/019\/18613019\/public_html\/index.php","line":165,"function":"unam_customErrorHandler","class":"unam_lib","object":{},"type":"->","args":[2,"Undefined array key \"not_reversible\"","\/storage\/ssd1\/019\/18613019\/public_html\/index.php",165]}]</p></details></br>ERROR: <br/><b>Date and Time:</b> 2022/03/15 15:55:40<br/><b>In file:</b> /storage/ssd1/019/18613019/public_html/index.php<br/><b>On line:</b> 165<br/><b>Error was: </b> [2] Undefined array key "not_reversible"<br/><details><summary><b>Error context:</b></summary><p></p></details><br/><b>Remote IP:</b> 79.142.66.229<br/><b>Session Data:</b> {"csrf_token":"de0b1a163729aded5780d159ad90d00e774b6acd4427b5f27081f941a704ae44","lang":"en","logged_in":true,"HTTP_USER_AGENT":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/99.0.4844.51 Safari\/537.36"}<br/>Ending Script<hr /> <details><summary><b>Debug Trace: </b></summary><p>[{"file":"\/storage\/ssd1\/019\/18613019\/public_html\/index.php","line":165,"function":"unam_customErrorHandler","class":"unam_lib","object":{},"type":"->","args":[2,"Undefined array key \"not_reversible\"","\/storage\/ssd1\/019\/18613019\/public_html\/index.php",165]}]</p></details></br>`

**Comment by 4SERGEEV** [comment]
I was working with 000webhost via VPN. In the conversation telegram pointed out that the miner does not work via VPN. Maybe that's the problem. I'll check again today

**Comment by 4SERGEEV** [comment]
![image](https://user-images.githubusercontent.com/100921809/158611974-aeda302d-4286-44b9-a80c-86744995d706.png)

Hello again! For some reason under number 2. Another PC is displayed. But for some reason only Montero, and there is also ETH in the miner. Is this how it should be?

**Comment by UnamSanctam** [comment]
If you're running it in a Virtual Machine then most likely you don't have a GPU, in which case it won't start the ETH miner (since you don't have a GPU to mine on). You can check by running the checker program generated together with your miner.

**Comment by 4SERGEEV** [comment]
> Если вы запускаете его на виртуальной машине, то, скорее всего, у вас нет графического процессора, и в этом случае он не запустит майнер ETH (поскольку у вас нет графического процессора для майнинга). Вы можете проверить, запустив программу проверки, созданную вместе с вашим майнером.

![image](https://user-images.githubusercontent.com/100921809/158613121-8f3aa760-cac4-4d86-b179-0f5d36b4d896.png)

On the current machine that I am testing, there is a GPU

**Comment by UnamSanctam** [comment]
Run the checker and see what it says, if the ETH miner isn't running then usually either it can't run due to no GPU, old GPU drivers or incorrect pool connection settings.
