### ISSUE TITLE
Login Troubleshooting

### ISSUE THREAD

**Issue by xSyloWx** [UnamSanctam/UnamWebPanel#92]
I keep getting the msg "Wrong password" even tho i changed it on apache2 web hosted server. My php ver is 7.4.3 and i also have installed sqlite for it. The folder and the files in /var/www/html also have 777 permissions. what am I doing wrong? Thanks.
![Capture](https://user-images.githubusercontent.com/87567765/159438679-56cbcca0-38a1-4763-a82c-a0dc24355abd.PNG)

**Comment by xSyloWx** [comment]
i also tried doing this in 000webhost and i was getting the same problem so i must be doing something wrong... dk what it is tho.

**Comment by xSyloWx** [comment]
![Capture PNG1](https://user-images.githubusercontent.com/87567765/159439897-a7e10f91-7648-4beb-a332-4f9b94335d2d.PNG)

**Comment by UnamSanctam** [comment]
You changed the key and not the value, it will work if you change it to `$config['password'] = '12345678';`

**Comment by xSyloWx** [comment]
i am so dumb

**Comment by xSyloWx** [comment]
thanks Unam! im going to cry my self to sleep now, have a good day

**Comment by UnamSanctam** [comment]
Haha it can be an easy mistake to make, have a good day.
