### ISSUE TITLE
WebPanel Protection

### ISSUE THREAD

**Issue by xSyloWx** [UnamSanctam/UnamWebPanel#93]
sooo.... I don't think my web panel is portected beacause when i type my url and /unamwebpanel.db it downloads the file.
Is it because of the /var/www/html permissions? and if so what permissions should i have for the panel database? I'm hosting it on apache 2 using ubuntu. Thanks.

**Comment by UnamSanctam** [comment]
The .htaccess file should make Apache block the file from being accessed:
https://github.com/UnamSanctam/UnamWebPanel/blob/master/UnamWebPanel/.htaccess, so maybe it's ignoring the .htaccess file or maybe you're allowing access to everything in your Apache config.

**Comment by xSyloWx** [comment]
I checked the apache2 config
![apache2](https://user-images.githubusercontent.com/87567765/159684864-eb5c8e60-1c50-413c-b2bf-91d253234d1e.PNG)
:

**Comment by UnamSanctam** [comment]
An the web panels .htaccess file is present?

**Comment by xSyloWx** [comment]
I cant find it, no

**Comment by UnamSanctam** [comment]
Try redownloading it.

**Comment by xSyloWx** [comment]
i figured out what happend in the first place, so i have your data base in zip on the desktop version of ubuntu right at the desktop. when i try to unzip it as sudo unzip and then destination, the .htaccess file doesnt unzip, only the rest of the files, even tho its present in the zipped folder.

**Comment by UnamSanctam** [comment]
Have you enabled showing hidden files? Since files beginning with a dot are treated as hidden files, can you see it with `ls -a`?

**Comment by xSyloWx** [comment]
ok so i just checked that and yea the file was there all the time hehe, but still i just tried and i can still download it
![1](https://user-images.githubusercontent.com/87567765/159688351-d07deeae-7368-4338-9136-a542fe784f96.PNG)
![2](https://user-images.githubusercontent.com/87567765/159688355-3828b981-4ba3-46d8-a5f4-7ed5229b13b5.PNG)
.

**Comment by UnamSanctam** [comment]
What apache do you have? Apache 2.4? Make sure that `mod_authz_core` is being loaded as well.

**Comment by xSyloWx** [comment]
Yes it is apache 2.4.44 nad how do check that?

**Comment by xSyloWx** [comment]
2.4.41 actually my bad

**Comment by UnamSanctam** [comment]
Make sure that `LoadModule authz_core_module modules/mod_authz_core.so` is uncommented in the configuration, though I've never heard of it not being enabled before. How did you set up your apache? You can check this to see if you did anything different (setting up virtual hosts and such isn't required) https://www.digitalocean.com/community/tutorials/how-to-install-the-apache-web-server-on-ubuntu-20-04

**Comment by xSyloWx** [comment]
I saw online that apache can have multiple locations for it's conf file such as:

/etc/apache2/httpd.conf
/etc/apache2/apache2.conf
/etc/httpd/httpd.conf
/etc/httpd/conf/httpd.conf

Could this be the problem? Every time I install it it only comes with /etc/apache2/apache2.conf as the main .conf file placed in the highest hierarchy of all .conf files.

**Comment by xSyloWx** [comment]
I'm going to CentOS and see if i can get it to work there.

**Comment by xSyloWx** [comment]
when i set it up on 000.webhost everything works fine i get the 403, idk

**Comment by xSyloWx** [comment]
I cant even do it properly on xampp, unamwebpanel.db still downloads, maybe im doing the port fowarding wrong?

**Comment by UnamSanctam** [comment]
Hmm no that shouldn't affect it since it's the Apache that's blocking it, I just tried it with XAMPP and I get a 403 with it.

**Comment by xSyloWx** [comment]
NAH BUT LIKE IM ACTUALY DUMB ASF.

**Comment by xSyloWx** [comment]
it was the port fowarding

**Comment by xSyloWx** [comment]
for 3 days ive been trying to figure out what it was, i was going insane
so many os created just to later find out this was the issue im dumb asf

**Comment by xSyloWx** [comment]
I gotta give a big thank you for all your repositories and the work and support youve been putting onto them. Not only are these projects fun and exciting for a dumb and newbie person like me, but ive also learned quite a lot so big thanks!

**Comment by UnamSanctam** [comment]
Haha thank you, good job getting everything work.
