### ISSUE TITLE
Incorrect Password

### ISSUE THREAD

**Issue by PandoricGalaxy** [UnamSanctam/UnamWebPanel#96]
Ive entered write password but always shows wrong. Even changed it and tried but still wrong
![image](https://user-images.githubusercontent.com/86944806/160883546-d46b44c6-a562-4d1c-bed3-387e446c8251.png)

**Comment by UnamSanctam** [comment]
Then it's the wrong password, you might've changed the key instead of the value in the config.php.

**Comment by PandoricGalaxy** [comment]
> Then it's the wrong password, you might've changed the key instead of the value in the config.php.

![image](https://user-images.githubusercontent.com/86944806/160887010-17627d4b-4c8d-428c-97d6-bf04452d8afd.png)
I entered this same password pandoric
